# This file was generated by liblab | https://liblab.com/

from typing import Union
from .services.control import ControlService
from .services.global_ import GlobalService
from .services.event import EventService
from .services.config import ConfigService
from .services.experimental import ExperimentalService
from .services.file import FileService
from .services.instance import InstanceService
from .services.mcp import McpService
from .services.project import ProjectService
from .services.pty import PtyService
from .services.question import QuestionService
from .services.permission import PermissionService
from .services.provider import ProviderService
from .services.session import SessionService
from .services.sync import SyncService
from .services.v2 import V2Service
from .services.v2_messages import V2MessagesService
from .services.v2_models import V2ModelsService
from .services.v2_providers import V2ProvidersService
from .services.tui import TuiService
from .services.workspace import WorkspaceService
from .net.environment import Environment


class Opencode:
    """
    Main SDK client class for Opencode.
    Provides centralized configuration and access to all service endpoints.
    Supports authentication, environment management, and global timeout settings.
    """

    def __init__(
        self,
        access_token: str = None,
        base_url: Union[Environment, str, None] = None,
        timeout: int = 60000,
    ):
        """
        Initializes Opencode the SDK class.
        """

        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )
        self.control = ControlService(base_url=self._base_url)
        self.global_ = GlobalService(base_url=self._base_url)
        self.event = EventService(base_url=self._base_url)
        self.config = ConfigService(base_url=self._base_url)
        self.experimental = ExperimentalService(base_url=self._base_url)
        self.file = FileService(base_url=self._base_url)
        self.instance = InstanceService(base_url=self._base_url)
        self.mcp = McpService(base_url=self._base_url)
        self.project = ProjectService(base_url=self._base_url)
        self.pty = PtyService(base_url=self._base_url)
        self.question = QuestionService(base_url=self._base_url)
        self.permission = PermissionService(base_url=self._base_url)
        self.provider = ProviderService(base_url=self._base_url)
        self.session = SessionService(base_url=self._base_url)
        self.sync = SyncService(base_url=self._base_url)
        self.v2 = V2Service(base_url=self._base_url)
        self.v2_messages = V2MessagesService(base_url=self._base_url)
        self.v2_models = V2ModelsService(base_url=self._base_url)
        self.v2_providers = V2ProvidersService(base_url=self._base_url)
        self.tui = TuiService(base_url=self._base_url)
        self.workspace = WorkspaceService(base_url=self._base_url)
        self.set_access_token(access_token)
        self.set_timeout(timeout)

    def set_base_url(self, base_url: Union[Environment, str]):
        """
        Sets the base URL for the entire SDK.

        :param Union[Environment, str] base_url: The base URL to be set.
        :return: The SDK instance.
        """
        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )

        self.control.set_base_url(self._base_url)
        self.global_.set_base_url(self._base_url)
        self.event.set_base_url(self._base_url)
        self.config.set_base_url(self._base_url)
        self.experimental.set_base_url(self._base_url)
        self.file.set_base_url(self._base_url)
        self.instance.set_base_url(self._base_url)
        self.mcp.set_base_url(self._base_url)
        self.project.set_base_url(self._base_url)
        self.pty.set_base_url(self._base_url)
        self.question.set_base_url(self._base_url)
        self.permission.set_base_url(self._base_url)
        self.provider.set_base_url(self._base_url)
        self.session.set_base_url(self._base_url)
        self.sync.set_base_url(self._base_url)
        self.v2.set_base_url(self._base_url)
        self.v2_messages.set_base_url(self._base_url)
        self.v2_models.set_base_url(self._base_url)
        self.v2_providers.set_base_url(self._base_url)
        self.tui.set_base_url(self._base_url)
        self.workspace.set_base_url(self._base_url)

        return self

    def set_access_token(self, access_token: str):
        """
        Sets the access token for the entire SDK.
        """
        self.control.set_access_token(access_token)
        self.global_.set_access_token(access_token)
        self.event.set_access_token(access_token)
        self.config.set_access_token(access_token)
        self.experimental.set_access_token(access_token)
        self.file.set_access_token(access_token)
        self.instance.set_access_token(access_token)
        self.mcp.set_access_token(access_token)
        self.project.set_access_token(access_token)
        self.pty.set_access_token(access_token)
        self.question.set_access_token(access_token)
        self.permission.set_access_token(access_token)
        self.provider.set_access_token(access_token)
        self.session.set_access_token(access_token)
        self.sync.set_access_token(access_token)
        self.v2.set_access_token(access_token)
        self.v2_messages.set_access_token(access_token)
        self.v2_models.set_access_token(access_token)
        self.v2_providers.set_access_token(access_token)
        self.tui.set_access_token(access_token)
        self.workspace.set_access_token(access_token)

        return self

    def set_timeout(self, timeout: int):
        """
        Sets the timeout for the entire SDK.

        :param int timeout: The timeout (ms) to be set.
        :return: The SDK instance.
        """
        self.control.set_timeout(timeout)
        self.global_.set_timeout(timeout)
        self.event.set_timeout(timeout)
        self.config.set_timeout(timeout)
        self.experimental.set_timeout(timeout)
        self.file.set_timeout(timeout)
        self.instance.set_timeout(timeout)
        self.mcp.set_timeout(timeout)
        self.project.set_timeout(timeout)
        self.pty.set_timeout(timeout)
        self.question.set_timeout(timeout)
        self.permission.set_timeout(timeout)
        self.provider.set_timeout(timeout)
        self.session.set_timeout(timeout)
        self.sync.set_timeout(timeout)
        self.v2.set_timeout(timeout)
        self.v2_messages.set_timeout(timeout)
        self.v2_models.set_timeout(timeout)
        self.v2_providers.set_timeout(timeout)
        self.tui.set_timeout(timeout)
        self.workspace.set_timeout(timeout)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
