# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, Union
from .utils.to_async import to_async
from ..config import ConfigService
from ...models.utils.sentinel import SENTINEL
from ...models import Config, ConfigProvidersOkResponse


class ConfigServiceAsync(ConfigService):
    """
    Async Wrapper for ConfigServiceAsync
    """

    def config_get(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[Config]:
        return to_async(super().config_get)(directory, workspace)

    def config_update(
        self,
        request_body: Config = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[Config]:
        return to_async(super().config_update)(request_body, directory, workspace)

    def config_providers(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[ConfigProvidersOkResponse]:
        return to_async(super().config_providers)(directory, workspace)
