# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, AsyncGenerator
from .utils.to_async import to_async
from ..event import EventService
from ...models.utils.sentinel import SENTINEL
from ...models import Event


class EventServiceAsync(EventService):
    """
    Async Wrapper for EventServiceAsync
    """

    def event_subscribe(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> AsyncGenerator[Event, None]:
        sync_generator = super().event_subscribe(directory, workspace)

        async def async_generator():
            for item in sync_generator:
                yield item

        return async_generator()
