# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, List
from .utils.to_async import to_async
from ..file import FileService
from ...models.utils.sentinel import SENTINEL
from ...models import (
    FindTextOkResponse,
    Dirs,
    FindFilesType,
    Symbol,
    FileNode,
    FileContent,
    File,
)


class FileServiceAsync(FileService):
    """
    Async Wrapper for FileServiceAsync
    """

    def find_text(
        self, pattern: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[FindTextOkResponse]]:
        return to_async(super().find_text)(pattern, directory, workspace)

    def find_files(
        self,
        query: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        dirs: Dirs = SENTINEL,
        type_: FindFilesType = SENTINEL,
        limit: int = SENTINEL,
    ) -> Awaitable[List[str]]:
        return to_async(super().find_files)(
            query, directory, workspace, dirs, type_, limit
        )

    def find_symbols(
        self, query: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[Symbol]]:
        return to_async(super().find_symbols)(query, directory, workspace)

    def file_list(
        self, path: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[FileNode]]:
        return to_async(super().file_list)(path, directory, workspace)

    def file_read(
        self, path: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[FileContent]:
        return to_async(super().file_read)(path, directory, workspace)

    def file_status(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[File]]:
        return to_async(super().file_status)(directory, workspace)
