# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, AsyncGenerator, Union
from .utils.to_async import to_async
from ..global_ import GlobalService
from ...models import (
    GlobalHealthOkResponse,
    GlobalEvent,
    Config,
    GlobalUpgradeOkResponse,
    GlobalUpgradeRequest,
)


class GlobalServiceAsync(GlobalService):
    """
    Async Wrapper for GlobalServiceAsync
    """

    def global_health(self) -> Awaitable[GlobalHealthOkResponse]:
        return to_async(super().global_health)()

    def global_event(self) -> AsyncGenerator[GlobalEvent, None]:
        sync_generator = super().global_event()

        async def async_generator():
            for item in sync_generator:
                yield item

        return async_generator()

    def global_config_get(self) -> Awaitable[Config]:
        return to_async(super().global_config_get)()

    def global_config_update(self, request_body: Config = None) -> Awaitable[Config]:
        return to_async(super().global_config_update)(request_body)

    def global_dispose(self) -> Awaitable[bool]:
        return to_async(super().global_dispose)()

    def global_upgrade(
        self, request_body: GlobalUpgradeRequest = None
    ) -> Awaitable[GlobalUpgradeOkResponse]:
        return to_async(super().global_upgrade)(request_body)
