# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, List, Union
from .utils.to_async import to_async
from ..question import QuestionService
from ...models.utils.sentinel import SENTINEL
from ...models import QuestionRequest, QuestionReplyRequest


class QuestionServiceAsync(QuestionService):
    """
    Async Wrapper for QuestionServiceAsync
    """

    def question_list(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[QuestionRequest]]:
        return to_async(super().question_list)(directory, workspace)

    def question_reply(
        self,
        request_id: str,
        request_body: QuestionReplyRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().question_reply)(
            request_id, request_body, directory, workspace
        )

    def question_reject(
        self, request_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().question_reject)(request_id, directory, workspace)
