# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, Union
from .utils.to_async import to_async
from ..tui import TuiService
from ...models.utils.sentinel import SENTINEL
from ...models import (
    TuiAppendPromptRequest,
    TuiExecuteCommandRequest,
    TuiShowToastRequest,
    TuiPublishRequest,
    TuiSelectSessionRequest,
    TuiControlNextOkResponse,
)


class TuiServiceAsync(TuiService):
    """
    Async Wrapper for TuiServiceAsync
    """

    def tui_append_prompt(
        self,
        request_body: TuiAppendPromptRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_append_prompt)(request_body, directory, workspace)

    def tui_open_help(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_open_help)(directory, workspace)

    def tui_open_sessions(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_open_sessions)(directory, workspace)

    def tui_open_themes(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_open_themes)(directory, workspace)

    def tui_open_models(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_open_models)(directory, workspace)

    def tui_submit_prompt(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_submit_prompt)(directory, workspace)

    def tui_clear_prompt(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[bool]:
        return to_async(super().tui_clear_prompt)(directory, workspace)

    def tui_execute_command(
        self,
        request_body: TuiExecuteCommandRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_execute_command)(request_body, directory, workspace)

    def tui_show_toast(
        self,
        request_body: TuiShowToastRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_show_toast)(request_body, directory, workspace)

    def tui_publish(
        self,
        request_body: TuiPublishRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_publish)(request_body, directory, workspace)

    def tui_select_session(
        self,
        request_body: TuiSelectSessionRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_select_session)(request_body, directory, workspace)

    def tui_control_next(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[TuiControlNextOkResponse]:
        return to_async(super().tui_control_next)(directory, workspace)

    def tui_control_response(
        self,
        request_body: any = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[bool]:
        return to_async(super().tui_control_response)(
            request_body, directory, workspace
        )
