# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, Union, List
from .utils.to_async import to_async
from ..v2 import V2Service
from ...models.utils.sentinel import SENTINEL
from ...models import (
    V2SessionsResponse,
    V2SessionListOrder,
    V2SessionListRoots,
    SessionMessage,
    V2SessionPromptRequest,
)


class V2ServiceAsync(V2Service):
    """
    Async Wrapper for V2ServiceAsync
    """

    def v2_session_list(
        self,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        limit: float = SENTINEL,
        order: V2SessionListOrder = SENTINEL,
        path: str = SENTINEL,
        roots: V2SessionListRoots = SENTINEL,
        start: float = SENTINEL,
        search: str = SENTINEL,
        cursor: str = SENTINEL,
    ) -> Awaitable[V2SessionsResponse]:
        return to_async(super().v2_session_list)(
            directory, workspace, limit, order, path, roots, start, search, cursor
        )

    def v2_session_prompt(
        self,
        session_id: str,
        request_body: V2SessionPromptRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> Awaitable[SessionMessage]:
        return to_async(super().v2_session_prompt)(
            session_id, request_body, directory, workspace
        )

    def v2_session_compact(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[None]:
        return to_async(super().v2_session_compact)(session_id, directory, workspace)

    def v2_session_wait(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[None]:
        return to_async(super().v2_session_wait)(session_id, directory, workspace)

    def v2_session_context(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Awaitable[List[SessionMessage]]:
        return to_async(super().v2_session_context)(session_id, directory, workspace)
