# This file was generated by liblab | https://liblab.com/

from opencode_api import Opencode

sdk = Opencode(access_token="YOUR_ACCESS_TOKEN", timeout=10000)

result = sdk.global_.global_health()

print(result)
