# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class AgentPartType(Enum):
    """An enumeration representing different categories.

    :cvar AGENT: "agent"
    :vartype AGENT: str
    """

    AGENT = "agent"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AgentPartType._member_map_.values()))


@JsonMap({})
class AgentPartSource(BaseModel):
    """AgentPartSource

    :param value: value
    :type value: str
    :param start: start
    :type start: int
    :param end: end
    :type end: int
    """

    def __init__(self, value: str, start: int, end: int, **kwargs):
        """AgentPartSource

        :param value: value
        :type value: str
        :param start: start
        :type start: int
        :param end: end
        :type end: int
        """
        self.value = self._define_str("value", value)
        self.start = self._define_number("start", start, ge=0)
        self.end = self._define_number("end", end, ge=0)
        self._kwargs = kwargs


@JsonMap(
    {"id_": "id", "session_id": "sessionID", "message_id": "messageID", "type_": "type"}
)
class AgentPart(BaseModel):
    """AgentPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: AgentPartType
    :param name: name
    :type name: str
    :param source: source, defaults to None
    :type source: AgentPartSource, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: AgentPartType,
        name: str,
        source: AgentPartSource = SENTINEL,
        **kwargs
    ):
        """AgentPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: AgentPartType
        :param name: name
        :type name: str
        :param source: source, defaults to None
        :type source: AgentPartSource, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, AgentPartType.list(), "type_")
        self.name = self._define_str("name", name)
        if source is not SENTINEL:
            self.source = self._define_object(source, AgentPartSource)
        self._kwargs = kwargs
