# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .utils.sentinel import SENTINEL
from .permission_config import PermissionConfig, PermissionConfigGuard
from .permission_action_config import PermissionActionConfig


class AgentConfigMode(Enum):
    """An enumeration representing different categories.

    :cvar SUBAGENT: "subagent"
    :vartype SUBAGENT: str
    :cvar PRIMARY: "primary"
    :vartype PRIMARY: str
    :cvar ALL: "all"
    :vartype ALL: str
    """

    SUBAGENT = "subagent"
    PRIMARY = "primary"
    ALL = "all"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AgentConfigMode._member_map_.values()))


class Color2(Enum):
    """An enumeration representing different categories.

    :cvar PRIMARY: "primary"
    :vartype PRIMARY: str
    :cvar SECONDARY: "secondary"
    :vartype SECONDARY: str
    :cvar ACCENT: "accent"
    :vartype ACCENT: str
    :cvar SUCCESS: "success"
    :vartype SUCCESS: str
    :cvar WARNING: "warning"
    :vartype WARNING: str
    :cvar ERROR: "error"
    :vartype ERROR: str
    :cvar INFO: "info"
    :vartype INFO: str
    """

    PRIMARY = "primary"
    SECONDARY = "secondary"
    ACCENT = "accent"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"
    INFO = "info"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Color2._member_map_.values()))


class ColorGuard(OneOfBaseModel):
    class_list = {"str": str, "Color2Enum": str}


Color = Union[str, str]


@JsonMap({"max_steps": "maxSteps"})
class AgentConfig(BaseModel):
    """AgentConfig

    :param model: model, defaults to None
    :type model: str, optional
    :param variant: variant, defaults to None
    :type variant: str, optional
    :param temperature: temperature, defaults to None
    :type temperature: float, optional
    :param top_p: top_p, defaults to None
    :type top_p: float, optional
    :param prompt: prompt, defaults to None
    :type prompt: str, optional
    :param tools: tools, defaults to None
    :type tools: dict, optional
    :param disable: disable, defaults to None
    :type disable: bool, optional
    :param description: description, defaults to None
    :type description: str, optional
    :param mode: mode, defaults to None
    :type mode: AgentConfigMode, optional
    :param hidden: hidden, defaults to None
    :type hidden: bool, optional
    :param options: options, defaults to None
    :type options: dict, optional
    :param color: Hex color code (e.g., #FF5733) or theme color (e.g., primary), defaults to None
    :type color: Color, optional
    :param steps: steps, defaults to None
    :type steps: int, optional
    :param max_steps: max_steps, defaults to None
    :type max_steps: int, optional
    :param permission: permission, defaults to None
    :type permission: PermissionConfig, optional
    """

    def __init__(
        self,
        model: str = SENTINEL,
        variant: str = SENTINEL,
        temperature: float = SENTINEL,
        top_p: float = SENTINEL,
        prompt: str = SENTINEL,
        tools: dict = SENTINEL,
        disable: bool = SENTINEL,
        description: str = SENTINEL,
        mode: AgentConfigMode = SENTINEL,
        hidden: bool = SENTINEL,
        options: dict = SENTINEL,
        color: Color = SENTINEL,
        steps: int = SENTINEL,
        max_steps: int = SENTINEL,
        permission: PermissionConfig = SENTINEL,
        **kwargs,
    ):
        """AgentConfig

        :param model: model, defaults to None
        :type model: str, optional
        :param variant: variant, defaults to None
        :type variant: str, optional
        :param temperature: temperature, defaults to None
        :type temperature: float, optional
        :param top_p: top_p, defaults to None
        :type top_p: float, optional
        :param prompt: prompt, defaults to None
        :type prompt: str, optional
        :param tools: tools, defaults to None
        :type tools: dict, optional
        :param disable: disable, defaults to None
        :type disable: bool, optional
        :param description: description, defaults to None
        :type description: str, optional
        :param mode: mode, defaults to None
        :type mode: AgentConfigMode, optional
        :param hidden: hidden, defaults to None
        :type hidden: bool, optional
        :param options: options, defaults to None
        :type options: dict, optional
        :param color: Hex color code (e.g., #FF5733) or theme color (e.g., primary), defaults to None
        :type color: Color, optional
        :param steps: steps, defaults to None
        :type steps: int, optional
        :param max_steps: max_steps, defaults to None
        :type max_steps: int, optional
        :param permission: permission, defaults to None
        :type permission: PermissionConfig, optional
        """
        if model is not SENTINEL:
            self.model = self._define_str("model", model)
        if variant is not SENTINEL:
            self.variant = self._define_str("variant", variant)
        if temperature is not SENTINEL:
            self.temperature = self._define_number("temperature", temperature)
        if top_p is not SENTINEL:
            self.top_p = self._define_number("top_p", top_p)
        if prompt is not SENTINEL:
            self.prompt = self._define_str("prompt", prompt)
        if tools is not SENTINEL:
            self.tools = tools
        if disable is not SENTINEL:
            self.disable = disable
        if description is not SENTINEL:
            self.description = self._define_str("description", description)
        if mode is not SENTINEL:
            self.mode = self._enum_matching(mode, AgentConfigMode.list(), "mode")
        if hidden is not SENTINEL:
            self.hidden = hidden
        if options is not SENTINEL:
            self.options = options
        if color is not SENTINEL:
            self.color = ColorGuard.return_one_of(color)
        if steps is not SENTINEL:
            self.steps = self._define_number("steps", steps)
        if max_steps is not SENTINEL:
            self.max_steps = self._define_number("max_steps", max_steps)
        if permission is not SENTINEL:
            self.permission = PermissionConfigGuard.return_one_of(permission)
        self._kwargs = kwargs
