# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class ApiErrorName(Enum):
    """An enumeration representing different categories.

    :cvar APIERROR: "APIError"
    :vartype APIERROR: str
    """

    APIERROR = "APIError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ApiErrorName._member_map_.values()))


@JsonMap(
    {
        "status_code": "statusCode",
        "is_retryable": "isRetryable",
        "response_headers": "responseHeaders",
        "response_body": "responseBody",
    }
)
class ApiErrorData(BaseModel):
    """ApiErrorData

    :param message: message
    :type message: str
    :param status_code: status_code, defaults to None
    :type status_code: int, optional
    :param is_retryable: is_retryable
    :type is_retryable: bool
    :param response_headers: response_headers, defaults to None
    :type response_headers: dict, optional
    :param response_body: response_body, defaults to None
    :type response_body: str, optional
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(
        self,
        message: str,
        is_retryable: bool,
        status_code: int = SENTINEL,
        response_headers: dict = SENTINEL,
        response_body: str = SENTINEL,
        metadata: dict = SENTINEL,
        **kwargs
    ):
        """ApiErrorData

        :param message: message
        :type message: str
        :param status_code: status_code, defaults to None
        :type status_code: int, optional
        :param is_retryable: is_retryable
        :type is_retryable: bool
        :param response_headers: response_headers, defaults to None
        :type response_headers: dict, optional
        :param response_body: response_body, defaults to None
        :type response_body: str, optional
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.message = self._define_str("message", message)
        if status_code is not SENTINEL:
            self.status_code = self._define_number("status_code", status_code, ge=0)
        self.is_retryable = is_retryable
        if response_headers is not SENTINEL:
            self.response_headers = response_headers
        if response_body is not SENTINEL:
            self.response_body = self._define_str("response_body", response_body)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs


@JsonMap({})
class ApiError(BaseModel):
    """ApiError

    :param name: name
    :type name: ApiErrorName
    :param data: data
    :type data: ApiErrorData
    """

    def __init__(self, name: ApiErrorName, data: ApiErrorData, **kwargs):
        """ApiError

        :param name: name
        :type name: ApiErrorName
        :param data: data
        :type data: ApiErrorData
        """
        self.name = self._enum_matching(name, ApiErrorName.list(), "name")
        self.data = self._define_object(data, ApiErrorData)
        self._kwargs = kwargs
