# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class BadRequestErrorName(Enum):
    """An enumeration representing different categories.

    :cvar BADREQUEST: "BadRequest"
    :vartype BADREQUEST: str
    """

    BADREQUEST = "BadRequest"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, BadRequestErrorName._member_map_.values()))


class DataKind(Enum):
    """An enumeration representing different categories.

    :cvar PARAMS: "Params"
    :vartype PARAMS: str
    :cvar HEADERS: "Headers"
    :vartype HEADERS: str
    :cvar QUERY: "Query"
    :vartype QUERY: str
    :cvar BODY: "Body"
    :vartype BODY: str
    :cvar PAYLOAD: "Payload"
    :vartype PAYLOAD: str
    """

    PARAMS = "Params"
    HEADERS = "Headers"
    QUERY = "Query"
    BODY = "Body"
    PAYLOAD = "Payload"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, DataKind._member_map_.values()))


@JsonMap({})
class BadRequestErrorData(BaseModel):
    """BadRequestErrorData

    :param message: message
    :type message: str
    :param kind: kind, defaults to None
    :type kind: DataKind, optional
    """

    def __init__(self, message: str, kind: DataKind = SENTINEL, **kwargs):
        """BadRequestErrorData

        :param message: message
        :type message: str
        :param kind: kind, defaults to None
        :type kind: DataKind, optional
        """
        self.message = self._define_str("message", message)
        if kind is not SENTINEL:
            self.kind = self._enum_matching(kind, DataKind.list(), "kind")
        self._kwargs = kwargs


@JsonMap({})
class BadRequestError(ApiError):
    """BadRequestError

    :param name: name
    :type name: BadRequestErrorName
    :param data: data
    :type data: BadRequestErrorData
    """

    def __init__(self, name: BadRequestErrorName, data: BadRequestErrorData, **kwargs):
        """BadRequestError

        :param name: name
        :type name: BadRequestErrorName
        :param data: data
        :type data: BadRequestErrorData
        """
        self.name = self._enum_matching(name, BadRequestErrorName.list(), "name")
        self.data = self._define_object(data, BadRequestErrorData)
        self._kwargs = kwargs
