# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class CompactionPartType(Enum):
    """An enumeration representing different categories.

    :cvar COMPACTION: "compaction"
    :vartype COMPACTION: str
    """

    COMPACTION = "compaction"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, CompactionPartType._member_map_.values()))


@JsonMap(
    {"id_": "id", "session_id": "sessionID", "message_id": "messageID", "type_": "type"}
)
class CompactionPart(BaseModel):
    """CompactionPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: CompactionPartType
    :param auto: auto
    :type auto: bool
    :param overflow: overflow, defaults to None
    :type overflow: bool, optional
    :param tail_start_id: tail_start_id, defaults to None
    :type tail_start_id: str, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: CompactionPartType,
        auto: bool,
        overflow: bool = SENTINEL,
        tail_start_id: str = SENTINEL,
        **kwargs
    ):
        """CompactionPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: CompactionPartType
        :param auto: auto
        :type auto: bool
        :param overflow: overflow, defaults to None
        :type overflow: bool, optional
        :param tail_start_id: tail_start_id, defaults to None
        :type tail_start_id: str, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, CompactionPartType.list(), "type_")
        self.auto = auto
        if overflow is not SENTINEL:
            self.overflow = overflow
        if tail_start_id is not SENTINEL:
            self.tail_start_id = self._define_str(
                "tail_start_id", tail_start_id, pattern="^msg"
            )
        self._kwargs = kwargs
