# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class ContextOverflowErrorName(Enum):
    """An enumeration representing different categories.

    :cvar CONTEXTOVERFLOWERROR: "ContextOverflowError"
    :vartype CONTEXTOVERFLOWERROR: str
    """

    CONTEXTOVERFLOWERROR = "ContextOverflowError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, ContextOverflowErrorName._member_map_.values())
        )


@JsonMap({"response_body": "responseBody"})
class ContextOverflowErrorData(BaseModel):
    """ContextOverflowErrorData

    :param message: message
    :type message: str
    :param response_body: response_body, defaults to None
    :type response_body: str, optional
    """

    def __init__(self, message: str, response_body: str = SENTINEL, **kwargs):
        """ContextOverflowErrorData

        :param message: message
        :type message: str
        :param response_body: response_body, defaults to None
        :type response_body: str, optional
        """
        self.message = self._define_str("message", message)
        if response_body is not SENTINEL:
            self.response_body = self._define_str("response_body", response_body)
        self._kwargs = kwargs


@JsonMap({})
class ContextOverflowError(BaseModel):
    """ContextOverflowError

    :param name: name
    :type name: ContextOverflowErrorName
    :param data: data
    :type data: ContextOverflowErrorData
    """

    def __init__(
        self, name: ContextOverflowErrorName, data: ContextOverflowErrorData, **kwargs
    ):
        """ContextOverflowError

        :param name: name
        :type name: ContextOverflowErrorName
        :param data: data
        :type data: ContextOverflowErrorData
        """
        self.name = self._enum_matching(name, ContextOverflowErrorName.list(), "name")
        self.data = self._define_object(data, ContextOverflowErrorData)
        self._kwargs = kwargs
