# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .prompt import Prompt


class EventSessionNextPromptedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTPROMPTED: "session.next.prompted"
    :vartype SESSIONNEXTPROMPTED: str
    """

    SESSIONNEXTPROMPTED = "session.next.prompted"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventSessionNextPromptedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID"})
class EventSessionNextPromptedProperties(BaseModel):
    """EventSessionNextPromptedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param prompt: prompt
    :type prompt: Prompt
    """

    def __init__(self, timestamp: float, session_id: str, prompt: Prompt, **kwargs):
        """EventSessionNextPromptedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param prompt: prompt
        :type prompt: Prompt
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.prompt = self._define_object(prompt, Prompt)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextPrompted(BaseModel):
    """EventSessionNextPrompted

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextPromptedType
    :param properties: properties
    :type properties: EventSessionNextPromptedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextPromptedType,
        properties: EventSessionNextPromptedProperties,
        **kwargs,
    ):
        """EventSessionNextPrompted

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextPromptedType
        :param properties: properties
        :type properties: EventSessionNextPromptedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextPromptedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextPromptedProperties
        )
        self._kwargs = kwargs
