# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextShellStartedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTSHELLSTARTED: "session.next.shell.started"
    :vartype SESSIONNEXTSHELLSTARTED: str
    """

    SESSIONNEXTSHELLSTARTED = "session.next.shell.started"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextShellStartedType._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class EventSessionNextShellStartedProperties(BaseModel):
    """EventSessionNextShellStartedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param command: command
    :type command: str
    """

    def __init__(
        self, timestamp: float, session_id: str, call_id: str, command: str, **kwargs
    ):
        """EventSessionNextShellStartedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param command: command
        :type command: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.command = self._define_str("command", command)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextShellStarted(BaseModel):
    """EventSessionNextShellStarted

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextShellStartedType
    :param properties: properties
    :type properties: EventSessionNextShellStartedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextShellStartedType,
        properties: EventSessionNextShellStartedProperties,
        **kwargs
    ):
        """EventSessionNextShellStarted

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextShellStartedType
        :param properties: properties
        :type properties: EventSessionNextShellStartedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextShellStartedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextShellStartedProperties
        )
        self._kwargs = kwargs
