# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionCompactedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONCOMPACTED: "session.compacted"
    :vartype SESSIONCOMPACTED: str
    """

    SESSIONCOMPACTED = "session.compacted"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventSessionCompactedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID"})
class EventSessionCompactedProperties(BaseModel):
    """EventSessionCompactedProperties

    :param session_id: session_id
    :type session_id: str
    """

    def __init__(self, session_id: str, **kwargs):
        """EventSessionCompactedProperties

        :param session_id: session_id
        :type session_id: str
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionCompacted(BaseModel):
    """EventSessionCompacted

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionCompactedType
    :param properties: properties
    :type properties: EventSessionCompactedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionCompactedType,
        properties: EventSessionCompactedProperties,
        **kwargs
    ):
        """EventSessionCompacted

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionCompactedType
        :param properties: properties
        :type properties: EventSessionCompactedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionCompactedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionCompactedProperties
        )
        self._kwargs = kwargs
