# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventWorkspaceFailedType(Enum):
    """An enumeration representing different categories.

    :cvar WORKSPACEFAILED: "workspace.failed"
    :vartype WORKSPACEFAILED: str
    """

    WORKSPACEFAILED = "workspace.failed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventWorkspaceFailedType._member_map_.values())
        )


@JsonMap({})
class EventWorkspaceFailedProperties(BaseModel):
    """EventWorkspaceFailedProperties

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """EventWorkspaceFailedProperties

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventWorkspaceFailed(BaseModel):
    """EventWorkspaceFailed

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventWorkspaceFailedType
    :param properties: properties
    :type properties: EventWorkspaceFailedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventWorkspaceFailedType,
        properties: EventWorkspaceFailedProperties,
        **kwargs
    ):
        """EventWorkspaceFailed

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventWorkspaceFailedType
        :param properties: properties
        :type properties: EventWorkspaceFailedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventWorkspaceFailedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventWorkspaceFailedProperties
        )
        self._kwargs = kwargs
