# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .message import Message, MessageGuard
from .user_message import UserMessage
from .assistant_message import AssistantMessage


class EventMessageUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar MESSAGEUPDATED: "message.updated"
    :vartype MESSAGEUPDATED: str
    """

    MESSAGEUPDATED = "message.updated"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventMessageUpdatedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID"})
class EventMessageUpdatedProperties(BaseModel):
    """EventMessageUpdatedProperties

    :param session_id: session_id
    :type session_id: str
    :param info: info
    :type info: Message
    """

    def __init__(self, session_id: str, info: Message, **kwargs):
        """EventMessageUpdatedProperties

        :param session_id: session_id
        :type session_id: str
        :param info: info
        :type info: Message
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.info = MessageGuard.return_one_of(info)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventMessageUpdated(BaseModel):
    """EventMessageUpdated

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventMessageUpdatedType
    :param properties: properties
    :type properties: EventMessageUpdatedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventMessageUpdatedType,
        properties: EventMessageUpdatedProperties,
        **kwargs,
    ):
        """EventMessageUpdated

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventMessageUpdatedType
        :param properties: properties
        :type properties: EventMessageUpdatedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventMessageUpdatedType.list(), "type_")
        self.properties = self._define_object(properties, EventMessageUpdatedProperties)
        self._kwargs = kwargs
