# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .utils.sentinel import SENTINEL
from .tool_text_content import ToolTextContent
from .tool_file_content import ToolFileContent


class EventSessionNextToolSuccessType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTTOOLSUCCESS: "session.next.tool.success"
    :vartype SESSIONNEXTTOOLSUCCESS: str
    """

    SESSIONNEXTTOOLSUCCESS = "session.next.tool.success"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, EventSessionNextToolSuccessType._member_map_.values()
            )
        )


class PropertiesContent2Guard(OneOfBaseModel):
    class_list = {
        "ToolTextContent": ToolTextContent,
        "ToolFileContent": ToolFileContent,
    }


PropertiesContent2 = Union[ToolTextContent, ToolFileContent]


@JsonMap({})
class PropertiesProvider2(BaseModel):
    """PropertiesProvider2

    :param executed: executed
    :type executed: bool
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(self, executed: bool, metadata: dict = SENTINEL, **kwargs):
        """PropertiesProvider2

        :param executed: executed
        :type executed: bool
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.executed = executed
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class EventSessionNextToolSuccessProperties(BaseModel):
    """EventSessionNextToolSuccessProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param structured: structured
    :type structured: dict
    :param content: content
    :type content: List[PropertiesContent2]
    :param provider: provider
    :type provider: PropertiesProvider2
    """

    def __init__(
        self,
        timestamp: float,
        session_id: str,
        call_id: str,
        structured: dict,
        content: List[PropertiesContent2],
        provider: PropertiesProvider2,
        **kwargs,
    ):
        """EventSessionNextToolSuccessProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param structured: structured
        :type structured: dict
        :param content: content
        :type content: List[PropertiesContent2]
        :param provider: provider
        :type provider: PropertiesProvider2
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.structured = structured
        self.content = self._define_list(content, PropertiesContent2)
        self.provider = self._define_object(provider, PropertiesProvider2)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextToolSuccess(BaseModel):
    """EventSessionNextToolSuccess

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextToolSuccessType
    :param properties: properties
    :type properties: EventSessionNextToolSuccessProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextToolSuccessType,
        properties: EventSessionNextToolSuccessProperties,
        **kwargs,
    ):
        """EventSessionNextToolSuccess

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextToolSuccessType
        :param properties: properties
        :type properties: EventSessionNextToolSuccessProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextToolSuccessType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextToolSuccessProperties
        )
        self._kwargs = kwargs
