# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventCommandExecutedType(Enum):
    """An enumeration representing different categories.

    :cvar COMMANDEXECUTED: "command.executed"
    :vartype COMMANDEXECUTED: str
    """

    COMMANDEXECUTED = "command.executed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventCommandExecutedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID", "message_id": "messageID"})
class EventCommandExecutedProperties(BaseModel):
    """EventCommandExecutedProperties

    :param name: name
    :type name: str
    :param session_id: session_id
    :type session_id: str
    :param arguments: arguments
    :type arguments: str
    :param message_id: message_id
    :type message_id: str
    """

    def __init__(
        self, name: str, session_id: str, arguments: str, message_id: str, **kwargs
    ):
        """EventCommandExecutedProperties

        :param name: name
        :type name: str
        :param session_id: session_id
        :type session_id: str
        :param arguments: arguments
        :type arguments: str
        :param message_id: message_id
        :type message_id: str
        """
        self.name = self._define_str("name", name)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.arguments = self._define_str("arguments", arguments)
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventCommandExecuted(BaseModel):
    """EventCommandExecuted

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventCommandExecutedType
    :param properties: properties
    :type properties: EventCommandExecutedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventCommandExecutedType,
        properties: EventCommandExecutedProperties,
        **kwargs
    ):
        """EventCommandExecuted

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventCommandExecutedType
        :param properties: properties
        :type properties: EventCommandExecutedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventCommandExecutedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventCommandExecutedProperties
        )
        self._kwargs = kwargs
