# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .project import Project


class EventProjectUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar PROJECTUPDATED: "project.updated"
    :vartype PROJECTUPDATED: str
    """

    PROJECTUPDATED = "project.updated"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventProjectUpdatedType._member_map_.values())
        )


@JsonMap({"id_": "id", "type_": "type"})
class EventProjectUpdated(BaseModel):
    """EventProjectUpdated

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventProjectUpdatedType
    :param properties: properties
    :type properties: Project
    """

    def __init__(
        self, id_: str, type_: EventProjectUpdatedType, properties: Project, **kwargs
    ):
        """EventProjectUpdated

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventProjectUpdatedType
        :param properties: properties
        :type properties: Project
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventProjectUpdatedType.list(), "type_")
        self.properties = self._define_object(properties, Project)
        self._kwargs = kwargs
