# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .session_status import SessionStatus, SessionStatusGuard


class EventSessionStatusType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONSTATUS: "session.status"
    :vartype SESSIONSTATUS: str
    """

    SESSIONSTATUS = "session.status"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventSessionStatusType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID"})
class EventSessionStatusProperties(BaseModel):
    """EventSessionStatusProperties

    :param session_id: session_id
    :type session_id: str
    :param status: status
    :type status: SessionStatus
    """

    def __init__(self, session_id: str, status: SessionStatus, **kwargs):
        """EventSessionStatusProperties

        :param session_id: session_id
        :type session_id: str
        :param status: status
        :type status: SessionStatus
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.status = SessionStatusGuard.return_one_of(status)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionStatus(BaseModel):
    """EventSessionStatus

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionStatusType
    :param properties: properties
    :type properties: EventSessionStatusProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionStatusType,
        properties: EventSessionStatusProperties,
        **kwargs,
    ):
        """EventSessionStatus

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionStatusType
        :param properties: properties
        :type properties: EventSessionStatusProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventSessionStatusType.list(), "type_")
        self.properties = self._define_object(properties, EventSessionStatusProperties)
        self._kwargs = kwargs
