# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextReasoningStartedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTREASONINGSTARTED: "session.next.reasoning.started"
    :vartype SESSIONNEXTREASONINGSTARTED: str
    """

    SESSIONNEXTREASONINGSTARTED = "session.next.reasoning.started"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextReasoningStartedType._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID", "reasoning_id": "reasoningID"})
class EventSessionNextReasoningStartedProperties(BaseModel):
    """EventSessionNextReasoningStartedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param reasoning_id: reasoning_id
    :type reasoning_id: str
    """

    def __init__(self, timestamp: float, session_id: str, reasoning_id: str, **kwargs):
        """EventSessionNextReasoningStartedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param reasoning_id: reasoning_id
        :type reasoning_id: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.reasoning_id = self._define_str("reasoning_id", reasoning_id)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextReasoningStarted(BaseModel):
    """EventSessionNextReasoningStarted

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextReasoningStartedType
    :param properties: properties
    :type properties: EventSessionNextReasoningStartedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextReasoningStartedType,
        properties: EventSessionNextReasoningStartedProperties,
        **kwargs
    ):
        """EventSessionNextReasoningStarted

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextReasoningStartedType
        :param properties: properties
        :type properties: EventSessionNextReasoningStartedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextReasoningStartedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextReasoningStartedProperties
        )
        self._kwargs = kwargs
