# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventInstallationUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar INSTALLATIONUPDATED: "installation.updated"
    :vartype INSTALLATIONUPDATED: str
    """

    INSTALLATIONUPDATED = "installation.updated"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventInstallationUpdatedType._member_map_.values())
        )


@JsonMap({})
class EventInstallationUpdatedProperties(BaseModel):
    """EventInstallationUpdatedProperties

    :param version: version
    :type version: str
    """

    def __init__(self, version: str, **kwargs):
        """EventInstallationUpdatedProperties

        :param version: version
        :type version: str
        """
        self.version = self._define_str("version", version)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventInstallationUpdated(BaseModel):
    """EventInstallationUpdated

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventInstallationUpdatedType
    :param properties: properties
    :type properties: EventInstallationUpdatedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventInstallationUpdatedType,
        properties: EventInstallationUpdatedProperties,
        **kwargs
    ):
        """EventInstallationUpdated

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventInstallationUpdatedType
        :param properties: properties
        :type properties: EventInstallationUpdatedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventInstallationUpdatedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventInstallationUpdatedProperties
        )
        self._kwargs = kwargs
