# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventServerInstanceDisposedType(Enum):
    """An enumeration representing different categories.

    :cvar SERVERINSTANCEDISPOSED: "server.instance.disposed"
    :vartype SERVERINSTANCEDISPOSED: str
    """

    SERVERINSTANCEDISPOSED = "server.instance.disposed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, EventServerInstanceDisposedType._member_map_.values()
            )
        )


@JsonMap({})
class EventServerInstanceDisposedProperties(BaseModel):
    """EventServerInstanceDisposedProperties

    :param directory: directory
    :type directory: str
    """

    def __init__(self, directory: str, **kwargs):
        """EventServerInstanceDisposedProperties

        :param directory: directory
        :type directory: str
        """
        self.directory = self._define_str("directory", directory)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventServerInstanceDisposed(BaseModel):
    """EventServerInstanceDisposed

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventServerInstanceDisposedType
    :param properties: properties
    :type properties: EventServerInstanceDisposedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventServerInstanceDisposedType,
        properties: EventServerInstanceDisposedProperties,
        **kwargs
    ):
        """EventServerInstanceDisposed

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventServerInstanceDisposedType
        :param properties: properties
        :type properties: EventServerInstanceDisposedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventServerInstanceDisposedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventServerInstanceDisposedProperties
        )
        self._kwargs = kwargs
