# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventLspClientDiagnosticsType(Enum):
    """An enumeration representing different categories.

    :cvar LSPCLIENTDIAGNOSTICS: "lsp.client.diagnostics"
    :vartype LSPCLIENTDIAGNOSTICS: str
    """

    LSPCLIENTDIAGNOSTICS = "lsp.client.diagnostics"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventLspClientDiagnosticsType._member_map_.values())
        )


@JsonMap({"server_id": "serverID"})
class EventLspClientDiagnosticsProperties(BaseModel):
    """EventLspClientDiagnosticsProperties

    :param server_id: server_id
    :type server_id: str
    :param path: path
    :type path: str
    """

    def __init__(self, server_id: str, path: str, **kwargs):
        """EventLspClientDiagnosticsProperties

        :param server_id: server_id
        :type server_id: str
        :param path: path
        :type path: str
        """
        self.server_id = self._define_str("server_id", server_id)
        self.path = self._define_str("path", path)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventLspClientDiagnostics(BaseModel):
    """EventLspClientDiagnostics

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventLspClientDiagnosticsType
    :param properties: properties
    :type properties: EventLspClientDiagnosticsProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventLspClientDiagnosticsType,
        properties: EventLspClientDiagnosticsProperties,
        **kwargs
    ):
        """EventLspClientDiagnostics

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventLspClientDiagnosticsType
        :param properties: properties
        :type properties: EventLspClientDiagnosticsProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventLspClientDiagnosticsType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventLspClientDiagnosticsProperties
        )
        self._kwargs = kwargs
