# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventWorkspaceReadyType(Enum):
    """An enumeration representing different categories.

    :cvar WORKSPACEREADY: "workspace.ready"
    :vartype WORKSPACEREADY: str
    """

    WORKSPACEREADY = "workspace.ready"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventWorkspaceReadyType._member_map_.values())
        )


@JsonMap({})
class EventWorkspaceReadyProperties(BaseModel):
    """EventWorkspaceReadyProperties

    :param name: name
    :type name: str
    """

    def __init__(self, name: str, **kwargs):
        """EventWorkspaceReadyProperties

        :param name: name
        :type name: str
        """
        self.name = self._define_str("name", name)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventWorkspaceReady(BaseModel):
    """EventWorkspaceReady

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventWorkspaceReadyType
    :param properties: properties
    :type properties: EventWorkspaceReadyProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventWorkspaceReadyType,
        properties: EventWorkspaceReadyProperties,
        **kwargs
    ):
        """EventWorkspaceReady

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventWorkspaceReadyType
        :param properties: properties
        :type properties: EventWorkspaceReadyProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventWorkspaceReadyType.list(), "type_")
        self.properties = self._define_object(properties, EventWorkspaceReadyProperties)
        self._kwargs = kwargs
