# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextShellEndedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTSHELLENDED: "session.next.shell.ended"
    :vartype SESSIONNEXTSHELLENDED: str
    """

    SESSIONNEXTSHELLENDED = "session.next.shell.ended"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventSessionNextShellEndedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class EventSessionNextShellEndedProperties(BaseModel):
    """EventSessionNextShellEndedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param output: output
    :type output: str
    """

    def __init__(
        self, timestamp: float, session_id: str, call_id: str, output: str, **kwargs
    ):
        """EventSessionNextShellEndedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param output: output
        :type output: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.output = self._define_str("output", output)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextShellEnded(BaseModel):
    """EventSessionNextShellEnded

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextShellEndedType
    :param properties: properties
    :type properties: EventSessionNextShellEndedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextShellEndedType,
        properties: EventSessionNextShellEndedProperties,
        **kwargs
    ):
        """EventSessionNextShellEnded

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextShellEndedType
        :param properties: properties
        :type properties: EventSessionNextShellEndedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextShellEndedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextShellEndedProperties
        )
        self._kwargs = kwargs
