# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventWorktreeFailedType(Enum):
    """An enumeration representing different categories.

    :cvar WORKTREEFAILED: "worktree.failed"
    :vartype WORKTREEFAILED: str
    """

    WORKTREEFAILED = "worktree.failed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventWorktreeFailedType._member_map_.values())
        )


@JsonMap({})
class EventWorktreeFailedProperties(BaseModel):
    """EventWorktreeFailedProperties

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """EventWorktreeFailedProperties

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventWorktreeFailed(BaseModel):
    """EventWorktreeFailed

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventWorktreeFailedType
    :param properties: properties
    :type properties: EventWorktreeFailedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventWorktreeFailedType,
        properties: EventWorktreeFailedProperties,
        **kwargs
    ):
        """EventWorktreeFailed

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventWorktreeFailedType
        :param properties: properties
        :type properties: EventWorktreeFailedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventWorktreeFailedType.list(), "type_")
        self.properties = self._define_object(properties, EventWorktreeFailedProperties)
        self._kwargs = kwargs
