# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextAgentSwitchedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTAGENTSWITCHED: "session.next.agent.switched"
    :vartype SESSIONNEXTAGENTSWITCHED: str
    """

    SESSIONNEXTAGENTSWITCHED = "session.next.agent.switched"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextAgentSwitchedType._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class EventSessionNextAgentSwitchedProperties(BaseModel):
    """EventSessionNextAgentSwitchedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param agent: agent
    :type agent: str
    """

    def __init__(self, timestamp: float, session_id: str, agent: str, **kwargs):
        """EventSessionNextAgentSwitchedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param agent: agent
        :type agent: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.agent = self._define_str("agent", agent)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextAgentSwitched(BaseModel):
    """EventSessionNextAgentSwitched

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextAgentSwitchedType
    :param properties: properties
    :type properties: EventSessionNextAgentSwitchedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextAgentSwitchedType,
        properties: EventSessionNextAgentSwitchedProperties,
        **kwargs
    ):
        """EventSessionNextAgentSwitched

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextAgentSwitchedType
        :param properties: properties
        :type properties: EventSessionNextAgentSwitchedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextAgentSwitchedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextAgentSwitchedProperties
        )
        self._kwargs = kwargs
