# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextModelSwitchedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTMODELSWITCHED: "session.next.model.switched"
    :vartype SESSIONNEXTMODELSWITCHED: str
    """

    SESSIONNEXTMODELSWITCHED = "session.next.model.switched"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextModelSwitchedType._member_map_.values(),
            )
        )


@JsonMap({"id_": "id", "provider_id": "providerID"})
class PropertiesModel1(BaseModel):
    """PropertiesModel1

    :param id_: id_
    :type id_: str
    :param provider_id: provider_id
    :type provider_id: str
    :param variant: variant
    :type variant: str
    """

    def __init__(self, id_: str, provider_id: str, variant: str, **kwargs):
        """PropertiesModel1

        :param id_: id_
        :type id_: str
        :param provider_id: provider_id
        :type provider_id: str
        :param variant: variant
        :type variant: str
        """
        self.id_ = self._define_str("id_", id_)
        self.provider_id = self._define_str("provider_id", provider_id)
        self.variant = self._define_str("variant", variant)
        self._kwargs = kwargs


@JsonMap({"session_id": "sessionID"})
class EventSessionNextModelSwitchedProperties(BaseModel):
    """EventSessionNextModelSwitchedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param model: model
    :type model: PropertiesModel1
    """

    def __init__(
        self, timestamp: float, session_id: str, model: PropertiesModel1, **kwargs
    ):
        """EventSessionNextModelSwitchedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param model: model
        :type model: PropertiesModel1
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.model = self._define_object(model, PropertiesModel1)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextModelSwitched(BaseModel):
    """EventSessionNextModelSwitched

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextModelSwitchedType
    :param properties: properties
    :type properties: EventSessionNextModelSwitchedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextModelSwitchedType,
        properties: EventSessionNextModelSwitchedProperties,
        **kwargs
    ):
        """EventSessionNextModelSwitched

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextModelSwitchedType
        :param properties: properties
        :type properties: EventSessionNextModelSwitchedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextModelSwitchedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextModelSwitchedProperties
        )
        self._kwargs = kwargs
