# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventLspUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar LSPUPDATED: "lsp.updated"
    :vartype LSPUPDATED: str
    """

    LSPUPDATED = "lsp.updated"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, EventLspUpdatedType._member_map_.values()))


@JsonMap({"id_": "id", "type_": "type"})
class EventLspUpdated(BaseModel):
    """EventLspUpdated

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventLspUpdatedType
    :param properties: properties
    :type properties: dict
    """

    def __init__(
        self, id_: str, type_: EventLspUpdatedType, properties: dict, **kwargs
    ):
        """EventLspUpdated

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventLspUpdatedType
        :param properties: properties
        :type properties: dict
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventLspUpdatedType.list(), "type_")
        self.properties = properties
        self._kwargs = kwargs
