# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventMcpBrowserOpenFailedType(Enum):
    """An enumeration representing different categories.

    :cvar MCPBROWSEROPENFAILED: "mcp.browser.open.failed"
    :vartype MCPBROWSEROPENFAILED: str
    """

    MCPBROWSEROPENFAILED = "mcp.browser.open.failed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventMcpBrowserOpenFailedType._member_map_.values())
        )


@JsonMap({"mcp_name": "mcpName"})
class EventMcpBrowserOpenFailedProperties(BaseModel):
    """EventMcpBrowserOpenFailedProperties

    :param mcp_name: mcp_name
    :type mcp_name: str
    :param url: url
    :type url: str
    """

    def __init__(self, mcp_name: str, url: str, **kwargs):
        """EventMcpBrowserOpenFailedProperties

        :param mcp_name: mcp_name
        :type mcp_name: str
        :param url: url
        :type url: str
        """
        self.mcp_name = self._define_str("mcp_name", mcp_name)
        self.url = self._define_str("url", url)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventMcpBrowserOpenFailed(BaseModel):
    """EventMcpBrowserOpenFailed

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventMcpBrowserOpenFailedType
    :param properties: properties
    :type properties: EventMcpBrowserOpenFailedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventMcpBrowserOpenFailedType,
        properties: EventMcpBrowserOpenFailedProperties,
        **kwargs
    ):
        """EventMcpBrowserOpenFailed

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventMcpBrowserOpenFailedType
        :param properties: properties
        :type properties: EventMcpBrowserOpenFailedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventMcpBrowserOpenFailedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventMcpBrowserOpenFailedProperties
        )
        self._kwargs = kwargs
