# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .session_error_unknown import SessionErrorUnknown


class EventSessionNextStepFailedType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTSTEPFAILED: "session.next.step.failed"
    :vartype SESSIONNEXTSTEPFAILED: str
    """

    SESSIONNEXTSTEPFAILED = "session.next.step.failed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventSessionNextStepFailedType._member_map_.values())
        )


@JsonMap({"session_id": "sessionID"})
class EventSessionNextStepFailedProperties(BaseModel):
    """EventSessionNextStepFailedProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param error: error
    :type error: SessionErrorUnknown
    """

    def __init__(
        self, timestamp: float, session_id: str, error: SessionErrorUnknown, **kwargs
    ):
        """EventSessionNextStepFailedProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param error: error
        :type error: SessionErrorUnknown
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.error = self._define_object(error, SessionErrorUnknown)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextStepFailed(BaseModel):
    """EventSessionNextStepFailed

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextStepFailedType
    :param properties: properties
    :type properties: EventSessionNextStepFailedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextStepFailedType,
        properties: EventSessionNextStepFailedProperties,
        **kwargs,
    ):
        """EventSessionNextStepFailed

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextStepFailedType
        :param properties: properties
        :type properties: EventSessionNextStepFailedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextStepFailedType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextStepFailedProperties
        )
        self._kwargs = kwargs
