# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventPtyExitedType(Enum):
    """An enumeration representing different categories.

    :cvar PTYEXITED: "pty.exited"
    :vartype PTYEXITED: str
    """

    PTYEXITED = "pty.exited"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, EventPtyExitedType._member_map_.values()))


@JsonMap({"id_": "id", "exit_code": "exitCode"})
class EventPtyExitedProperties(BaseModel):
    """EventPtyExitedProperties

    :param id_: id_
    :type id_: str
    :param exit_code: exit_code
    :type exit_code: int
    """

    def __init__(self, id_: str, exit_code: int, **kwargs):
        """EventPtyExitedProperties

        :param id_: id_
        :type id_: str
        :param exit_code: exit_code
        :type exit_code: int
        """
        self.id_ = self._define_str("id_", id_, pattern="^pty")
        self.exit_code = self._define_number("exit_code", exit_code, ge=0)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventPtyExited(BaseModel):
    """EventPtyExited

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventPtyExitedType
    :param properties: properties
    :type properties: EventPtyExitedProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventPtyExitedType,
        properties: EventPtyExitedProperties,
        **kwargs
    ):
        """EventPtyExited

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventPtyExitedType
        :param properties: properties
        :type properties: EventPtyExitedProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventPtyExitedType.list(), "type_")
        self.properties = self._define_object(properties, EventPtyExitedProperties)
        self._kwargs = kwargs
