# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .tool_text_content import ToolTextContent
from .tool_file_content import ToolFileContent


class EventSessionNextToolProgressType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTTOOLPROGRESS: "session.next.tool.progress"
    :vartype SESSIONNEXTTOOLPROGRESS: str
    """

    SESSIONNEXTTOOLPROGRESS = "session.next.tool.progress"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextToolProgressType._member_map_.values(),
            )
        )


class PropertiesContent1Guard(OneOfBaseModel):
    class_list = {
        "ToolTextContent": ToolTextContent,
        "ToolFileContent": ToolFileContent,
    }


PropertiesContent1 = Union[ToolTextContent, ToolFileContent]


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class EventSessionNextToolProgressProperties(BaseModel):
    """EventSessionNextToolProgressProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param structured: structured
    :type structured: dict
    :param content: content
    :type content: List[PropertiesContent1]
    """

    def __init__(
        self,
        timestamp: float,
        session_id: str,
        call_id: str,
        structured: dict,
        content: List[PropertiesContent1],
        **kwargs,
    ):
        """EventSessionNextToolProgressProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param structured: structured
        :type structured: dict
        :param content: content
        :type content: List[PropertiesContent1]
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.structured = structured
        self.content = self._define_list(content, PropertiesContent1)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextToolProgress(BaseModel):
    """EventSessionNextToolProgress

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextToolProgressType
    :param properties: properties
    :type properties: EventSessionNextToolProgressProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextToolProgressType,
        properties: EventSessionNextToolProgressProperties,
        **kwargs,
    ):
        """EventSessionNextToolProgress

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextToolProgressType
        :param properties: properties
        :type properties: EventSessionNextToolProgressProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextToolProgressType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextToolProgressProperties
        )
        self._kwargs = kwargs
