# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .event_server_instance_disposed import EventServerInstanceDisposed
from .event_permission_asked import EventPermissionAsked
from .event_permission_replied import EventPermissionReplied
from .event_lsp_client_diagnostics import EventLspClientDiagnostics
from .event_lsp_updated import EventLspUpdated
from .event_message_part_delta import EventMessagePartDelta
from .event_session_diff import EventSessionDiff
from .event_session_error import EventSessionError
from .payload_9 import Payload9
from .payload_10 import Payload10
from .event_tui_toast_show1 import EventTuiToastShow1
from .payload_12 import Payload12
from .event_installation_updated import EventInstallationUpdated
from .event_installation_update_available import EventInstallationUpdateAvailable
from .event_mcp_tools_changed import EventMcpToolsChanged
from .event_mcp_browser_open_failed import EventMcpBrowserOpenFailed
from .event_command_executed import EventCommandExecuted
from .event_project_updated import EventProjectUpdated
from .event_worktree_ready import EventWorktreeReady
from .event_worktree_failed import EventWorktreeFailed
from .event_file_edited import EventFileEdited
from .event_file_watcher_updated import EventFileWatcherUpdated
from .event_vcs_branch_updated import EventVcsBranchUpdated
from .event_question_asked import EventQuestionAsked
from .event_question_replied import EventQuestionReplied
from .event_question_rejected import EventQuestionRejected
from .event_todo_updated import EventTodoUpdated
from .event_session_status import EventSessionStatus
from .event_session_idle import EventSessionIdle
from .event_session_compacted import EventSessionCompacted
from .event_workspace_ready import EventWorkspaceReady
from .event_workspace_failed import EventWorkspaceFailed
from .event_workspace_status import EventWorkspaceStatus
from .event_pty_created import EventPtyCreated
from .event_pty_updated import EventPtyUpdated
from .event_pty_exited import EventPtyExited
from .event_pty_deleted import EventPtyDeleted
from .event_message_updated import EventMessageUpdated
from .event_message_removed import EventMessageRemoved
from .event_message_part_updated import EventMessagePartUpdated
from .event_message_part_removed import EventMessagePartRemoved
from .event_session_created import EventSessionCreated
from .event_session_updated import EventSessionUpdated
from .event_session_deleted import EventSessionDeleted
from .event_session_next_agent_switched import EventSessionNextAgentSwitched
from .event_session_next_model_switched import EventSessionNextModelSwitched
from .event_session_next_prompted import EventSessionNextPrompted
from .event_session_next_synthetic import EventSessionNextSynthetic
from .event_session_next_shell_started import EventSessionNextShellStarted
from .event_session_next_shell_ended import EventSessionNextShellEnded
from .event_session_next_step_started import EventSessionNextStepStarted
from .event_session_next_step_ended import EventSessionNextStepEnded
from .event_session_next_step_failed import EventSessionNextStepFailed
from .event_session_next_text_started import EventSessionNextTextStarted
from .event_session_next_text_delta import EventSessionNextTextDelta
from .event_session_next_text_ended import EventSessionNextTextEnded
from .event_session_next_reasoning_started import EventSessionNextReasoningStarted
from .event_session_next_reasoning_delta import EventSessionNextReasoningDelta
from .event_session_next_reasoning_ended import EventSessionNextReasoningEnded
from .event_session_next_tool_input_started import EventSessionNextToolInputStarted
from .event_session_next_tool_input_delta import EventSessionNextToolInputDelta
from .event_session_next_tool_input_ended import EventSessionNextToolInputEnded
from .event_session_next_tool_called import EventSessionNextToolCalled
from .event_session_next_tool_progress import EventSessionNextToolProgress
from .event_session_next_tool_success import EventSessionNextToolSuccess
from .event_session_next_tool_failed import EventSessionNextToolFailed
from .event_session_next_retried import EventSessionNextRetried
from .event_session_next_compaction_started import EventSessionNextCompactionStarted
from .event_session_next_compaction_delta import EventSessionNextCompactionDelta
from .event_session_next_compaction_ended import EventSessionNextCompactionEnded
from .event_server_connected import EventServerConnected
from .event_global_disposed import EventGlobalDisposed
from .event_catalog_model_updated import EventCatalogModelUpdated


class EventGuard(OneOfBaseModel):
    class_list = {
        "EventServerInstanceDisposed": EventServerInstanceDisposed,
        "EventPermissionAsked": EventPermissionAsked,
        "EventPermissionReplied": EventPermissionReplied,
        "EventLspClientDiagnostics": EventLspClientDiagnostics,
        "EventLspUpdated": EventLspUpdated,
        "EventMessagePartDelta": EventMessagePartDelta,
        "EventSessionDiff": EventSessionDiff,
        "EventSessionError": EventSessionError,
        "Payload9": Payload9,
        "Payload10": Payload10,
        "EventTuiToastShow1": EventTuiToastShow1,
        "Payload12": Payload12,
        "EventInstallationUpdated": EventInstallationUpdated,
        "EventInstallationUpdateAvailable": EventInstallationUpdateAvailable,
        "EventMcpToolsChanged": EventMcpToolsChanged,
        "EventMcpBrowserOpenFailed": EventMcpBrowserOpenFailed,
        "EventCommandExecuted": EventCommandExecuted,
        "EventProjectUpdated": EventProjectUpdated,
        "EventWorktreeReady": EventWorktreeReady,
        "EventWorktreeFailed": EventWorktreeFailed,
        "EventFileEdited": EventFileEdited,
        "EventFileWatcherUpdated": EventFileWatcherUpdated,
        "EventVcsBranchUpdated": EventVcsBranchUpdated,
        "EventQuestionAsked": EventQuestionAsked,
        "EventQuestionReplied": EventQuestionReplied,
        "EventQuestionRejected": EventQuestionRejected,
        "EventTodoUpdated": EventTodoUpdated,
        "EventSessionStatus": EventSessionStatus,
        "EventSessionIdle": EventSessionIdle,
        "EventSessionCompacted": EventSessionCompacted,
        "EventWorkspaceReady": EventWorkspaceReady,
        "EventWorkspaceFailed": EventWorkspaceFailed,
        "EventWorkspaceStatus": EventWorkspaceStatus,
        "EventPtyCreated": EventPtyCreated,
        "EventPtyUpdated": EventPtyUpdated,
        "EventPtyExited": EventPtyExited,
        "EventPtyDeleted": EventPtyDeleted,
        "EventMessageUpdated": EventMessageUpdated,
        "EventMessageRemoved": EventMessageRemoved,
        "EventMessagePartUpdated": EventMessagePartUpdated,
        "EventMessagePartRemoved": EventMessagePartRemoved,
        "EventSessionCreated": EventSessionCreated,
        "EventSessionUpdated": EventSessionUpdated,
        "EventSessionDeleted": EventSessionDeleted,
        "EventSessionNextAgentSwitched": EventSessionNextAgentSwitched,
        "EventSessionNextModelSwitched": EventSessionNextModelSwitched,
        "EventSessionNextPrompted": EventSessionNextPrompted,
        "EventSessionNextSynthetic": EventSessionNextSynthetic,
        "EventSessionNextShellStarted": EventSessionNextShellStarted,
        "EventSessionNextShellEnded": EventSessionNextShellEnded,
        "EventSessionNextStepStarted": EventSessionNextStepStarted,
        "EventSessionNextStepEnded": EventSessionNextStepEnded,
        "EventSessionNextStepFailed": EventSessionNextStepFailed,
        "EventSessionNextTextStarted": EventSessionNextTextStarted,
        "EventSessionNextTextDelta": EventSessionNextTextDelta,
        "EventSessionNextTextEnded": EventSessionNextTextEnded,
        "EventSessionNextReasoningStarted": EventSessionNextReasoningStarted,
        "EventSessionNextReasoningDelta": EventSessionNextReasoningDelta,
        "EventSessionNextReasoningEnded": EventSessionNextReasoningEnded,
        "EventSessionNextToolInputStarted": EventSessionNextToolInputStarted,
        "EventSessionNextToolInputDelta": EventSessionNextToolInputDelta,
        "EventSessionNextToolInputEnded": EventSessionNextToolInputEnded,
        "EventSessionNextToolCalled": EventSessionNextToolCalled,
        "EventSessionNextToolProgress": EventSessionNextToolProgress,
        "EventSessionNextToolSuccess": EventSessionNextToolSuccess,
        "EventSessionNextToolFailed": EventSessionNextToolFailed,
        "EventSessionNextRetried": EventSessionNextRetried,
        "EventSessionNextCompactionStarted": EventSessionNextCompactionStarted,
        "EventSessionNextCompactionDelta": EventSessionNextCompactionDelta,
        "EventSessionNextCompactionEnded": EventSessionNextCompactionEnded,
        "EventServerConnected": EventServerConnected,
        "EventGlobalDisposed": EventGlobalDisposed,
        "EventCatalogModelUpdated": EventCatalogModelUpdated,
        "EventSessionNextAgentSwitched": EventSessionNextAgentSwitched,
        "EventSessionNextModelSwitched": EventSessionNextModelSwitched,
        "EventSessionNextPrompted": EventSessionNextPrompted,
        "EventSessionNextSynthetic": EventSessionNextSynthetic,
        "EventSessionNextShellStarted": EventSessionNextShellStarted,
        "EventSessionNextShellEnded": EventSessionNextShellEnded,
        "EventSessionNextStepStarted": EventSessionNextStepStarted,
        "EventSessionNextStepEnded": EventSessionNextStepEnded,
        "EventSessionNextStepFailed": EventSessionNextStepFailed,
        "EventSessionNextTextStarted": EventSessionNextTextStarted,
        "EventSessionNextTextDelta": EventSessionNextTextDelta,
        "EventSessionNextTextEnded": EventSessionNextTextEnded,
        "EventSessionNextReasoningStarted": EventSessionNextReasoningStarted,
        "EventSessionNextReasoningDelta": EventSessionNextReasoningDelta,
        "EventSessionNextReasoningEnded": EventSessionNextReasoningEnded,
        "EventSessionNextToolInputStarted": EventSessionNextToolInputStarted,
        "EventSessionNextToolInputDelta": EventSessionNextToolInputDelta,
        "EventSessionNextToolInputEnded": EventSessionNextToolInputEnded,
        "EventSessionNextToolCalled": EventSessionNextToolCalled,
        "EventSessionNextToolProgress": EventSessionNextToolProgress,
        "EventSessionNextToolSuccess": EventSessionNextToolSuccess,
        "EventSessionNextToolFailed": EventSessionNextToolFailed,
        "EventSessionNextRetried": EventSessionNextRetried,
        "EventSessionNextCompactionStarted": EventSessionNextCompactionStarted,
        "EventSessionNextCompactionDelta": EventSessionNextCompactionDelta,
        "EventSessionNextCompactionEnded": EventSessionNextCompactionEnded,
    }


Event = Union[
    EventServerInstanceDisposed,
    EventPermissionAsked,
    EventPermissionReplied,
    EventLspClientDiagnostics,
    EventLspUpdated,
    EventMessagePartDelta,
    EventSessionDiff,
    EventSessionError,
    Payload9,
    Payload10,
    EventTuiToastShow1,
    Payload12,
    EventInstallationUpdated,
    EventInstallationUpdateAvailable,
    EventMcpToolsChanged,
    EventMcpBrowserOpenFailed,
    EventCommandExecuted,
    EventProjectUpdated,
    EventWorktreeReady,
    EventWorktreeFailed,
    EventFileEdited,
    EventFileWatcherUpdated,
    EventVcsBranchUpdated,
    EventQuestionAsked,
    EventQuestionReplied,
    EventQuestionRejected,
    EventTodoUpdated,
    EventSessionStatus,
    EventSessionIdle,
    EventSessionCompacted,
    EventWorkspaceReady,
    EventWorkspaceFailed,
    EventWorkspaceStatus,
    EventPtyCreated,
    EventPtyUpdated,
    EventPtyExited,
    EventPtyDeleted,
    EventMessageUpdated,
    EventMessageRemoved,
    EventMessagePartUpdated,
    EventMessagePartRemoved,
    EventSessionCreated,
    EventSessionUpdated,
    EventSessionDeleted,
    EventSessionNextAgentSwitched,
    EventSessionNextModelSwitched,
    EventSessionNextPrompted,
    EventSessionNextSynthetic,
    EventSessionNextShellStarted,
    EventSessionNextShellEnded,
    EventSessionNextStepStarted,
    EventSessionNextStepEnded,
    EventSessionNextStepFailed,
    EventSessionNextTextStarted,
    EventSessionNextTextDelta,
    EventSessionNextTextEnded,
    EventSessionNextReasoningStarted,
    EventSessionNextReasoningDelta,
    EventSessionNextReasoningEnded,
    EventSessionNextToolInputStarted,
    EventSessionNextToolInputDelta,
    EventSessionNextToolInputEnded,
    EventSessionNextToolCalled,
    EventSessionNextToolProgress,
    EventSessionNextToolSuccess,
    EventSessionNextToolFailed,
    EventSessionNextRetried,
    EventSessionNextCompactionStarted,
    EventSessionNextCompactionDelta,
    EventSessionNextCompactionEnded,
    EventServerConnected,
    EventGlobalDisposed,
    EventCatalogModelUpdated,
    EventSessionNextAgentSwitched,
    EventSessionNextModelSwitched,
    EventSessionNextPrompted,
    EventSessionNextSynthetic,
    EventSessionNextShellStarted,
    EventSessionNextShellEnded,
    EventSessionNextStepStarted,
    EventSessionNextStepEnded,
    EventSessionNextStepFailed,
    EventSessionNextTextStarted,
    EventSessionNextTextDelta,
    EventSessionNextTextEnded,
    EventSessionNextReasoningStarted,
    EventSessionNextReasoningDelta,
    EventSessionNextReasoningEnded,
    EventSessionNextToolInputStarted,
    EventSessionNextToolInputDelta,
    EventSessionNextToolInputEnded,
    EventSessionNextToolCalled,
    EventSessionNextToolProgress,
    EventSessionNextToolSuccess,
    EventSessionNextToolFailed,
    EventSessionNextRetried,
    EventSessionNextCompactionStarted,
    EventSessionNextCompactionDelta,
    EventSessionNextCompactionEnded,
]
