# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class EventSessionNextReasoningDeltaType(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTREASONINGDELTA: "session.next.reasoning.delta"
    :vartype SESSIONNEXTREASONINGDELTA: str
    """

    SESSIONNEXTREASONINGDELTA = "session.next.reasoning.delta"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                EventSessionNextReasoningDeltaType._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID", "reasoning_id": "reasoningID"})
class EventSessionNextReasoningDeltaProperties(BaseModel):
    """EventSessionNextReasoningDeltaProperties

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param reasoning_id: reasoning_id
    :type reasoning_id: str
    :param delta: delta
    :type delta: str
    """

    def __init__(
        self, timestamp: float, session_id: str, reasoning_id: str, delta: str, **kwargs
    ):
        """EventSessionNextReasoningDeltaProperties

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param reasoning_id: reasoning_id
        :type reasoning_id: str
        :param delta: delta
        :type delta: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.reasoning_id = self._define_str("reasoning_id", reasoning_id)
        self.delta = self._define_str("delta", delta)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class EventSessionNextReasoningDelta(BaseModel):
    """EventSessionNextReasoningDelta

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventSessionNextReasoningDeltaType
    :param properties: properties
    :type properties: EventSessionNextReasoningDeltaProperties
    """

    def __init__(
        self,
        id_: str,
        type_: EventSessionNextReasoningDeltaType,
        properties: EventSessionNextReasoningDeltaProperties,
        **kwargs
    ):
        """EventSessionNextReasoningDelta

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventSessionNextReasoningDeltaType
        :param properties: properties
        :type properties: EventSessionNextReasoningDeltaProperties
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(
            type_, EventSessionNextReasoningDeltaType.list(), "type_"
        )
        self.properties = self._define_object(
            properties, EventSessionNextReasoningDeltaProperties
        )
        self._kwargs = kwargs
