# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .workspace_warp_error import WorkspaceWarpError
from .vcs_apply_error import VcsApplyError


class ExperimentalWorkspaceWarpBadRequestResponseGuard(OneOfBaseModel):
    class_list = {
        "WorkspaceWarpError": WorkspaceWarpError,
        "VcsApplyError": VcsApplyError,
    }


ExperimentalWorkspaceWarpBadRequestResponse = Union[WorkspaceWarpError, VcsApplyError]
