# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"id_": "id", "session_id": "sessionID", "copy_changes": "copyChanges"})
class ExperimentalWorkspaceWarpRequest(BaseModel):
    """ExperimentalWorkspaceWarpRequest

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param copy_changes: copy_changes, defaults to None
    :type copy_changes: bool, optional
    """

    def __init__(
        self,
        id_: Union[str, None],
        session_id: str,
        copy_changes: bool = SENTINEL,
        **kwargs
    ):
        """ExperimentalWorkspaceWarpRequest

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param copy_changes: copy_changes, defaults to None
        :type copy_changes: bool, optional
        """
        self.id_ = self._define_str("id_", id_, nullable=True, pattern="^wrk")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        if copy_changes is not SENTINEL:
            self.copy_changes = copy_changes
        self._kwargs = kwargs
