# This file was generated by liblab | https://liblab.com/

from enum import Enum
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class FileContentType(Enum):
    """An enumeration representing different categories.

    :cvar TEXT: "text"
    :vartype TEXT: str
    :cvar BINARY: "binary"
    :vartype BINARY: str
    """

    TEXT = "text"
    BINARY = "binary"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, FileContentType._member_map_.values()))


@JsonMap(
    {
        "old_start": "oldStart",
        "old_lines": "oldLines",
        "new_start": "newStart",
        "new_lines": "newLines",
    }
)
class Hunks(BaseModel):
    """Hunks

    :param old_start: old_start
    :type old_start: int
    :param old_lines: old_lines
    :type old_lines: int
    :param new_start: new_start
    :type new_start: int
    :param new_lines: new_lines
    :type new_lines: int
    :param lines: lines
    :type lines: List[str]
    """

    def __init__(
        self,
        old_start: int,
        old_lines: int,
        new_start: int,
        new_lines: int,
        lines: List[str],
        **kwargs
    ):
        """Hunks

        :param old_start: old_start
        :type old_start: int
        :param old_lines: old_lines
        :type old_lines: int
        :param new_start: new_start
        :type new_start: int
        :param new_lines: new_lines
        :type new_lines: int
        :param lines: lines
        :type lines: List[str]
        """
        self.old_start = self._define_number("old_start", old_start, ge=0)
        self.old_lines = self._define_number("old_lines", old_lines, ge=0)
        self.new_start = self._define_number("new_start", new_start, ge=0)
        self.new_lines = self._define_number("new_lines", new_lines, ge=0)
        self.lines = lines
        self._kwargs = kwargs


@JsonMap(
    {
        "old_file_name": "oldFileName",
        "new_file_name": "newFileName",
        "old_header": "oldHeader",
        "new_header": "newHeader",
    }
)
class Patch(BaseModel):
    """Patch

    :param old_file_name: old_file_name
    :type old_file_name: str
    :param new_file_name: new_file_name
    :type new_file_name: str
    :param old_header: old_header, defaults to None
    :type old_header: str, optional
    :param new_header: new_header, defaults to None
    :type new_header: str, optional
    :param hunks: hunks
    :type hunks: List[Hunks]
    :param index: index, defaults to None
    :type index: str, optional
    """

    def __init__(
        self,
        old_file_name: str,
        new_file_name: str,
        hunks: List[Hunks],
        old_header: str = SENTINEL,
        new_header: str = SENTINEL,
        index: str = SENTINEL,
        **kwargs
    ):
        """Patch

        :param old_file_name: old_file_name
        :type old_file_name: str
        :param new_file_name: new_file_name
        :type new_file_name: str
        :param old_header: old_header, defaults to None
        :type old_header: str, optional
        :param new_header: new_header, defaults to None
        :type new_header: str, optional
        :param hunks: hunks
        :type hunks: List[Hunks]
        :param index: index, defaults to None
        :type index: str, optional
        """
        self.old_file_name = self._define_str("old_file_name", old_file_name)
        self.new_file_name = self._define_str("new_file_name", new_file_name)
        if old_header is not SENTINEL:
            self.old_header = self._define_str("old_header", old_header)
        if new_header is not SENTINEL:
            self.new_header = self._define_str("new_header", new_header)
        self.hunks = self._define_list(hunks, Hunks)
        if index is not SENTINEL:
            self.index = self._define_str("index", index)
        self._kwargs = kwargs


class Encoding(Enum):
    """An enumeration representing different categories.

    :cvar BASE64: "base64"
    :vartype BASE64: str
    """

    BASE64 = "base64"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Encoding._member_map_.values()))


@JsonMap({"type_": "type", "mime_type": "mimeType"})
class FileContent(BaseModel):
    """FileContent

    :param type_: type_
    :type type_: FileContentType
    :param content: content
    :type content: str
    :param diff: diff, defaults to None
    :type diff: str, optional
    :param patch: patch, defaults to None
    :type patch: Patch, optional
    :param encoding: encoding, defaults to None
    :type encoding: Encoding, optional
    :param mime_type: mime_type, defaults to None
    :type mime_type: str, optional
    """

    def __init__(
        self,
        type_: FileContentType,
        content: str,
        diff: str = SENTINEL,
        patch: Patch = SENTINEL,
        encoding: Encoding = SENTINEL,
        mime_type: str = SENTINEL,
        **kwargs
    ):
        """FileContent

        :param type_: type_
        :type type_: FileContentType
        :param content: content
        :type content: str
        :param diff: diff, defaults to None
        :type diff: str, optional
        :param patch: patch, defaults to None
        :type patch: Patch, optional
        :param encoding: encoding, defaults to None
        :type encoding: Encoding, optional
        :param mime_type: mime_type, defaults to None
        :type mime_type: str, optional
        """
        self.type_ = self._enum_matching(type_, FileContentType.list(), "type_")
        self.content = self._define_str("content", content)
        if diff is not SENTINEL:
            self.diff = self._define_str("diff", diff)
        if patch is not SENTINEL:
            self.patch = self._define_object(patch, Patch)
        if encoding is not SENTINEL:
            self.encoding = self._enum_matching(encoding, Encoding.list(), "encoding")
        if mime_type is not SENTINEL:
            self.mime_type = self._define_str("mime_type", mime_type)
        self._kwargs = kwargs
