# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class FileStatus(Enum):
    """An enumeration representing different categories.

    :cvar ADDED: "added"
    :vartype ADDED: str
    :cvar DELETED: "deleted"
    :vartype DELETED: str
    :cvar MODIFIED: "modified"
    :vartype MODIFIED: str
    """

    ADDED = "added"
    DELETED = "deleted"
    MODIFIED = "modified"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, FileStatus._member_map_.values()))


@JsonMap({})
class File(BaseModel):
    """File

    :param path: path
    :type path: str
    :param added: added
    :type added: int
    :param removed: removed
    :type removed: int
    :param status: status
    :type status: FileStatus
    """

    def __init__(
        self, path: str, added: int, removed: int, status: FileStatus, **kwargs
    ):
        """File

        :param path: path
        :type path: str
        :param added: added
        :type added: int
        :param removed: removed
        :type removed: int
        :param status: status
        :type status: FileStatus
        """
        self.path = self._define_str("path", path)
        self.added = self._define_number("added", added, ge=0)
        self.removed = self._define_number("removed", removed, ge=0)
        self.status = self._enum_matching(status, FileStatus.list(), "status")
        self._kwargs = kwargs
