# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class FileNodeType(Enum):
    """An enumeration representing different categories.

    :cvar FILE: "file"
    :vartype FILE: str
    :cvar DIRECTORY: "directory"
    :vartype DIRECTORY: str
    """

    FILE = "file"
    DIRECTORY = "directory"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, FileNodeType._member_map_.values()))


@JsonMap({"type_": "type"})
class FileNode(BaseModel):
    """FileNode

    :param name: name
    :type name: str
    :param path: path
    :type path: str
    :param absolute: absolute
    :type absolute: str
    :param type_: type_
    :type type_: FileNodeType
    :param ignored: ignored
    :type ignored: bool
    """

    def __init__(
        self,
        name: str,
        path: str,
        absolute: str,
        type_: FileNodeType,
        ignored: bool,
        **kwargs
    ):
        """FileNode

        :param name: name
        :type name: str
        :param path: path
        :type path: str
        :param absolute: absolute
        :type absolute: str
        :param type_: type_
        :type type_: FileNodeType
        :param ignored: ignored
        :type ignored: bool
        """
        self.name = self._define_str("name", name)
        self.path = self._define_str("path", path)
        self.absolute = self._define_str("absolute", absolute)
        self.type_ = self._enum_matching(type_, FileNodeType.list(), "type_")
        self.ignored = ignored
        self._kwargs = kwargs
