# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class GlobalUpgradeRequest(BaseModel):
    """GlobalUpgradeRequest

    :param target: target, defaults to None
    :type target: str, optional
    """

    def __init__(self, target: str = SENTINEL, **kwargs):
        """GlobalUpgradeRequest

        :param target: target, defaults to None
        :type target: str, optional
        """
        if target is not SENTINEL:
            self.target = self._define_str("target", target)
        self._kwargs = kwargs
