# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LayoutConfig(Enum):
    """An enumeration representing different categories.

    :cvar AUTO: "auto"
    :vartype AUTO: str
    :cvar STRETCH: "stretch"
    :vartype STRETCH: str
    """

    AUTO = "auto"
    STRETCH = "stretch"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LayoutConfig._member_map_.values()))
