# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class LspStatusStatus(Enum):
    """An enumeration representing different categories.

    :cvar CONNECTED: "connected"
    :vartype CONNECTED: str
    :cvar ERROR: "error"
    :vartype ERROR: str
    """

    CONNECTED = "connected"
    ERROR = "error"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LspStatusStatus._member_map_.values()))


@JsonMap({"id_": "id"})
class LspStatus(BaseModel):
    """LspStatus

    :param id_: id_
    :type id_: str
    :param name: name
    :type name: str
    :param root: root
    :type root: str
    :param status: status
    :type status: LspStatusStatus
    """

    def __init__(
        self, id_: str, name: str, root: str, status: LspStatusStatus, **kwargs
    ):
        """LspStatus

        :param id_: id_
        :type id_: str
        :param name: name
        :type name: str
        :param root: root
        :type root: str
        :param status: status
        :type status: LspStatusStatus
        """
        self.id_ = self._define_str("id_", id_)
        self.name = self._define_str("name", name)
        self.root = self._define_str("root", root)
        self.status = self._enum_matching(status, LspStatusStatus.list(), "status")
        self._kwargs = kwargs
