# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class McpStatusFailedStatus(Enum):
    """An enumeration representing different categories.

    :cvar FAILED: "failed"
    :vartype FAILED: str
    """

    FAILED = "failed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, McpStatusFailedStatus._member_map_.values()))


@JsonMap({})
class McpStatusFailed(BaseModel):
    """McpStatusFailed

    :param status: status
    :type status: McpStatusFailedStatus
    :param error: error
    :type error: str
    """

    def __init__(self, status: McpStatusFailedStatus, error: str, **kwargs):
        """McpStatusFailed

        :param status: status
        :type status: McpStatusFailedStatus
        :param error: error
        :type error: str
        """
        self.status = self._enum_matching(
            status, McpStatusFailedStatus.list(), "status"
        )
        self.error = self._define_str("error", error)
        self._kwargs = kwargs
