# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError


@JsonMap({})
class McpUnsupportedOAuthError(ApiError):
    """McpUnsupportedOAuthError

    :param error: error
    :type error: str
    """

    def __init__(self, error: str, **kwargs):
        """McpUnsupportedOAuthError

        :param error: error
        :type error: str
        """
        self.error = self._define_str("error", error)
        self._kwargs = kwargs
