# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class McpStatusNeedsAuthStatus(Enum):
    """An enumeration representing different categories.

    :cvar NEEDSAUTH: "needs_auth"
    :vartype NEEDSAUTH: str
    """

    NEEDSAUTH = "needs_auth"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, McpStatusNeedsAuthStatus._member_map_.values())
        )


@JsonMap({})
class McpStatusNeedsAuth(BaseModel):
    """McpStatusNeedsAuth

    :param status: status
    :type status: McpStatusNeedsAuthStatus
    """

    def __init__(self, status: McpStatusNeedsAuthStatus, **kwargs):
        """McpStatusNeedsAuth

        :param status: status
        :type status: McpStatusNeedsAuthStatus
        """
        self.status = self._enum_matching(
            status, McpStatusNeedsAuthStatus.list(), "status"
        )
        self._kwargs = kwargs
