# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .mcp_status_connected import McpStatusConnected
from .mcp_status_disabled import McpStatusDisabled
from .mcp_status_failed import McpStatusFailed
from .mcp_status_needs_auth import McpStatusNeedsAuth
from .mcp_status_needs_client_registration import McpStatusNeedsClientRegistration


class McpStatusGuard(OneOfBaseModel):
    class_list = {
        "McpStatusConnected": McpStatusConnected,
        "McpStatusDisabled": McpStatusDisabled,
        "McpStatusFailed": McpStatusFailed,
        "McpStatusNeedsAuth": McpStatusNeedsAuth,
        "McpStatusNeedsClientRegistration": McpStatusNeedsClientRegistration,
    }


McpStatus = Union[
    McpStatusConnected,
    McpStatusDisabled,
    McpStatusFailed,
    McpStatusNeedsAuth,
    McpStatusNeedsClientRegistration,
]
