# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .mcp_local_config import McpLocalConfig
from .mcp_remote_config import McpRemoteConfig


class McpAddRequestConfigGuard(OneOfBaseModel):
    class_list = {"McpLocalConfig": McpLocalConfig, "McpRemoteConfig": McpRemoteConfig}


McpAddRequestConfig = Union[McpLocalConfig, McpRemoteConfig]


@JsonMap({})
class McpAddRequest(BaseModel):
    """McpAddRequest

    :param name: name
    :type name: str
    :param config: config
    :type config: McpAddRequestConfig
    """

    def __init__(self, name: str, config: McpAddRequestConfig, **kwargs):
        """McpAddRequest

        :param name: name
        :type name: str
        :param config: config
        :type config: McpAddRequestConfig
        """
        self.name = self._define_str("name", name)
        self.config = McpAddRequestConfigGuard.return_one_of(config)
        self._kwargs = kwargs
