# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class McpStatusNeedsClientRegistrationStatus(Enum):
    """An enumeration representing different categories.

    :cvar NEEDSCLIENTREGISTRATION: "needs_client_registration"
    :vartype NEEDSCLIENTREGISTRATION: str
    """

    NEEDSCLIENTREGISTRATION = "needs_client_registration"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                McpStatusNeedsClientRegistrationStatus._member_map_.values(),
            )
        )


@JsonMap({})
class McpStatusNeedsClientRegistration(BaseModel):
    """McpStatusNeedsClientRegistration

    :param status: status
    :type status: McpStatusNeedsClientRegistrationStatus
    :param error: error
    :type error: str
    """

    def __init__(
        self, status: McpStatusNeedsClientRegistrationStatus, error: str, **kwargs
    ):
        """McpStatusNeedsClientRegistration

        :param status: status
        :type status: McpStatusNeedsClientRegistrationStatus
        :param error: error
        :type error: str
        """
        self.status = self._enum_matching(
            status, McpStatusNeedsClientRegistrationStatus.list(), "status"
        )
        self.error = self._define_str("error", error)
        self._kwargs = kwargs
