# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class MessageAbortedErrorName(Enum):
    """An enumeration representing different categories.

    :cvar MESSAGEABORTEDERROR: "MessageAbortedError"
    :vartype MESSAGEABORTEDERROR: str
    """

    MESSAGEABORTEDERROR = "MessageAbortedError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, MessageAbortedErrorName._member_map_.values())
        )


@JsonMap({})
class MessageAbortedErrorData(BaseModel):
    """MessageAbortedErrorData

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """MessageAbortedErrorData

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({})
class MessageAbortedError(BaseModel):
    """MessageAbortedError

    :param name: name
    :type name: MessageAbortedErrorName
    :param data: data
    :type data: MessageAbortedErrorData
    """

    def __init__(
        self, name: MessageAbortedErrorName, data: MessageAbortedErrorData, **kwargs
    ):
        """MessageAbortedError

        :param name: name
        :type name: MessageAbortedErrorName
        :param data: data
        :type data: MessageAbortedErrorData
        """
        self.name = self._enum_matching(name, MessageAbortedErrorName.list(), "name")
        self.data = self._define_object(data, MessageAbortedErrorData)
        self._kwargs = kwargs
