# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .user_message import UserMessage
from .assistant_message import AssistantMessage


class MessageGuard(OneOfBaseModel):
    class_list = {"UserMessage": UserMessage, "AssistantMessage": AssistantMessage}


Message = Union[UserMessage, AssistantMessage]
