# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class MessageOutputLengthErrorName(Enum):
    """An enumeration representing different categories.

    :cvar MESSAGEOUTPUTLENGTHERROR: "MessageOutputLengthError"
    :vartype MESSAGEOUTPUTLENGTHERROR: str
    """

    MESSAGEOUTPUTLENGTHERROR = "MessageOutputLengthError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, MessageOutputLengthErrorName._member_map_.values())
        )


@JsonMap({})
class MessageOutputLengthError(BaseModel):
    """MessageOutputLengthError

    :param name: name
    :type name: MessageOutputLengthErrorName
    :param data: data
    :type data: dict
    """

    def __init__(self, name: MessageOutputLengthErrorName, data: dict, **kwargs):
        """MessageOutputLengthError

        :param name: name
        :type name: MessageOutputLengthErrorName
        :param data: data
        :type data: dict
        """
        self.name = self._enum_matching(
            name, MessageOutputLengthErrorName.list(), "name"
        )
        self.data = data
        self._kwargs = kwargs
