# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.base_model import BaseModel


class NotFoundErrorName(Enum):
    """An enumeration representing different categories.

    :cvar NOTFOUNDERROR: "NotFoundError"
    :vartype NOTFOUNDERROR: str
    """

    NOTFOUNDERROR = "NotFoundError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, NotFoundErrorName._member_map_.values()))


@JsonMap({})
class NotFoundErrorData(BaseModel):
    """NotFoundErrorData

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """NotFoundErrorData

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({})
class NotFoundError(ApiError):
    """NotFoundError

    :param name: name
    :type name: NotFoundErrorName
    :param data: data
    :type data: NotFoundErrorData
    """

    def __init__(self, name: NotFoundErrorName, data: NotFoundErrorData, **kwargs):
        """NotFoundError

        :param name: name
        :type name: NotFoundErrorName
        :param data: data
        :type data: NotFoundErrorData
        """
        self.name = self._enum_matching(name, NotFoundErrorName.list(), "name")
        self.data = self._define_object(data, NotFoundErrorData)
        self._kwargs = kwargs
