# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class OutputFormatJsonSchemaType(Enum):
    """An enumeration representing different categories.

    :cvar JSONSCHEMA: "json_schema"
    :vartype JSONSCHEMA: str
    """

    JSONSCHEMA = "json_schema"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, OutputFormatJsonSchemaType._member_map_.values())
        )


@JsonMap({"type_": "type", "retry_count": "retryCount"})
class OutputFormatJsonSchema(BaseModel):
    """OutputFormatJsonSchema

    :param type_: type_
    :type type_: OutputFormatJsonSchemaType
    :param schema: schema
    :type schema: dict
    :param retry_count: retry_count, defaults to None
    :type retry_count: int, optional
    """

    def __init__(
        self,
        type_: OutputFormatJsonSchemaType,
        schema: dict,
        retry_count: int = SENTINEL,
        **kwargs
    ):
        """OutputFormatJsonSchema

        :param type_: type_
        :type type_: OutputFormatJsonSchemaType
        :param schema: schema
        :type schema: dict
        :param retry_count: retry_count, defaults to None
        :type retry_count: int, optional
        """
        self.type_ = self._enum_matching(
            type_, OutputFormatJsonSchemaType.list(), "type_"
        )
        self.schema = schema
        if retry_count is not SENTINEL:
            self.retry_count = self._define_number("retry_count", retry_count, ge=0)
        self._kwargs = kwargs
