# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .text_part import TextPart
from .subtask_part import SubtaskPart
from .reasoning_part import ReasoningPart
from .file_part import FilePart
from .tool_part import ToolPart
from .step_start_part import StepStartPart
from .step_finish_part import StepFinishPart
from .snapshot_part import SnapshotPart
from .patch_part import PatchPart
from .agent_part import AgentPart
from .retry_part import RetryPart
from .compaction_part import CompactionPart


class PartGuard(OneOfBaseModel):
    class_list = {
        "TextPart": TextPart,
        "SubtaskPart": SubtaskPart,
        "ReasoningPart": ReasoningPart,
        "FilePart": FilePart,
        "ToolPart": ToolPart,
        "StepStartPart": StepStartPart,
        "StepFinishPart": StepFinishPart,
        "SnapshotPart": SnapshotPart,
        "PatchPart": PatchPart,
        "AgentPart": AgentPart,
        "RetryPart": RetryPart,
        "CompactionPart": CompactionPart,
    }


Part = Union[
    TextPart,
    SubtaskPart,
    ReasoningPart,
    FilePart,
    ToolPart,
    StepStartPart,
    StepFinishPart,
    SnapshotPart,
    PatchPart,
    AgentPart,
    RetryPart,
    CompactionPart,
]
