# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Path(BaseModel):
    """Path

    :param home: home
    :type home: str
    :param state: state
    :type state: str
    :param config: config
    :type config: str
    :param worktree: worktree
    :type worktree: str
    :param directory: directory
    :type directory: str
    """

    def __init__(
        self,
        home: str,
        state: str,
        config: str,
        worktree: str,
        directory: str,
        **kwargs
    ):
        """Path

        :param home: home
        :type home: str
        :param state: state
        :type state: str
        :param config: config
        :type config: str
        :param worktree: worktree
        :type worktree: str
        :param directory: directory
        :type directory: str
        """
        self.home = self._define_str("home", home)
        self.state = self._define_str("state", state)
        self.config = self._define_str("config", config)
        self.worktree = self._define_str("worktree", worktree)
        self.directory = self._define_str("directory", directory)
        self._kwargs = kwargs
