# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class EventTuiToastShowType1(Enum):
    """An enumeration representing different categories.

    :cvar TUITOASTSHOW: "tui.toast.show"
    :vartype TUITOASTSHOW: str
    """

    TUITOASTSHOW = "tui.toast.show"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventTuiToastShowType1._member_map_.values())
        )


class PropertiesVariant1(Enum):
    """An enumeration representing different categories.

    :cvar INFO: "info"
    :vartype INFO: str
    :cvar SUCCESS: "success"
    :vartype SUCCESS: str
    :cvar WARNING: "warning"
    :vartype WARNING: str
    :cvar ERROR: "error"
    :vartype ERROR: str
    """

    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, PropertiesVariant1._member_map_.values()))


@JsonMap({})
class EventTuiToastShowProperties1(BaseModel):
    """EventTuiToastShowProperties1

    :param title: title, defaults to None
    :type title: str, optional
    :param message: message
    :type message: str
    :param variant: variant
    :type variant: PropertiesVariant1
    :param duration: duration, defaults to None
    :type duration: int, optional
    """

    def __init__(
        self,
        message: str,
        variant: PropertiesVariant1,
        title: str = SENTINEL,
        duration: int = SENTINEL,
        **kwargs
    ):
        """EventTuiToastShowProperties1

        :param title: title, defaults to None
        :type title: str, optional
        :param message: message
        :type message: str
        :param variant: variant
        :type variant: PropertiesVariant1
        :param duration: duration, defaults to None
        :type duration: int, optional
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        self.message = self._define_str("message", message)
        self.variant = self._enum_matching(
            variant, PropertiesVariant1.list(), "variant"
        )
        if duration is not SENTINEL:
            self.duration = self._define_number("duration", duration)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class Payload11(BaseModel):
    """Payload11

    :param id_: id_
    :type id_: str
    :param type_: type_
    :type type_: EventTuiToastShowType1
    :param properties: properties
    :type properties: EventTuiToastShowProperties1
    """

    def __init__(
        self,
        id_: str,
        type_: EventTuiToastShowType1,
        properties: EventTuiToastShowProperties1,
        **kwargs
    ):
        """Payload11

        :param id_: id_
        :type id_: str
        :param type_: type_
        :type type_: EventTuiToastShowType1
        :param properties: properties
        :type properties: EventTuiToastShowProperties1
        """
        self.id_ = self._define_str("id_", id_)
        self.type_ = self._enum_matching(type_, EventTuiToastShowType1.list(), "type_")
        self.properties = self._define_object(properties, EventTuiToastShowProperties1)
        self._kwargs = kwargs
