# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .utils.sentinel import SENTINEL
from .permission_action_config import PermissionActionConfig
from .permission_rule_config import PermissionRuleConfig, PermissionRuleConfigGuard


@JsonMap({})
class PermissionConfig2(BaseModel):
    """PermissionConfig2

    :param read: read, defaults to None
    :type read: PermissionRuleConfig, optional
    :param edit: edit, defaults to None
    :type edit: PermissionRuleConfig, optional
    :param glob: glob, defaults to None
    :type glob: PermissionRuleConfig, optional
    :param grep: grep, defaults to None
    :type grep: PermissionRuleConfig, optional
    :param list: list, defaults to None
    :type list: PermissionRuleConfig, optional
    :param bash: bash, defaults to None
    :type bash: PermissionRuleConfig, optional
    :param task: task, defaults to None
    :type task: PermissionRuleConfig, optional
    :param external_directory: external_directory, defaults to None
    :type external_directory: PermissionRuleConfig, optional
    :param todowrite: todowrite, defaults to None
    :type todowrite: PermissionActionConfig, optional
    :param question: question, defaults to None
    :type question: PermissionActionConfig, optional
    :param webfetch: webfetch, defaults to None
    :type webfetch: PermissionActionConfig, optional
    :param websearch: websearch, defaults to None
    :type websearch: PermissionActionConfig, optional
    :param repo_clone: repo_clone, defaults to None
    :type repo_clone: PermissionRuleConfig, optional
    :param repo_overview: repo_overview, defaults to None
    :type repo_overview: PermissionRuleConfig, optional
    :param lsp: lsp, defaults to None
    :type lsp: PermissionRuleConfig, optional
    :param doom_loop: doom_loop, defaults to None
    :type doom_loop: PermissionActionConfig, optional
    :param skill: skill, defaults to None
    :type skill: PermissionRuleConfig, optional
    """

    def __init__(
        self,
        read: PermissionRuleConfig = SENTINEL,
        edit: PermissionRuleConfig = SENTINEL,
        glob: PermissionRuleConfig = SENTINEL,
        grep: PermissionRuleConfig = SENTINEL,
        list: PermissionRuleConfig = SENTINEL,
        bash: PermissionRuleConfig = SENTINEL,
        task: PermissionRuleConfig = SENTINEL,
        external_directory: PermissionRuleConfig = SENTINEL,
        todowrite: PermissionActionConfig = SENTINEL,
        question: PermissionActionConfig = SENTINEL,
        webfetch: PermissionActionConfig = SENTINEL,
        websearch: PermissionActionConfig = SENTINEL,
        repo_clone: PermissionRuleConfig = SENTINEL,
        repo_overview: PermissionRuleConfig = SENTINEL,
        lsp: PermissionRuleConfig = SENTINEL,
        doom_loop: PermissionActionConfig = SENTINEL,
        skill: PermissionRuleConfig = SENTINEL,
        **kwargs,
    ):
        """PermissionConfig2

        :param read: read, defaults to None
        :type read: PermissionRuleConfig, optional
        :param edit: edit, defaults to None
        :type edit: PermissionRuleConfig, optional
        :param glob: glob, defaults to None
        :type glob: PermissionRuleConfig, optional
        :param grep: grep, defaults to None
        :type grep: PermissionRuleConfig, optional
        :param list: list, defaults to None
        :type list: PermissionRuleConfig, optional
        :param bash: bash, defaults to None
        :type bash: PermissionRuleConfig, optional
        :param task: task, defaults to None
        :type task: PermissionRuleConfig, optional
        :param external_directory: external_directory, defaults to None
        :type external_directory: PermissionRuleConfig, optional
        :param todowrite: todowrite, defaults to None
        :type todowrite: PermissionActionConfig, optional
        :param question: question, defaults to None
        :type question: PermissionActionConfig, optional
        :param webfetch: webfetch, defaults to None
        :type webfetch: PermissionActionConfig, optional
        :param websearch: websearch, defaults to None
        :type websearch: PermissionActionConfig, optional
        :param repo_clone: repo_clone, defaults to None
        :type repo_clone: PermissionRuleConfig, optional
        :param repo_overview: repo_overview, defaults to None
        :type repo_overview: PermissionRuleConfig, optional
        :param lsp: lsp, defaults to None
        :type lsp: PermissionRuleConfig, optional
        :param doom_loop: doom_loop, defaults to None
        :type doom_loop: PermissionActionConfig, optional
        :param skill: skill, defaults to None
        :type skill: PermissionRuleConfig, optional
        """
        if read is not SENTINEL:
            self.read = PermissionRuleConfigGuard.return_one_of(read)
        if edit is not SENTINEL:
            self.edit = PermissionRuleConfigGuard.return_one_of(edit)
        if glob is not SENTINEL:
            self.glob = PermissionRuleConfigGuard.return_one_of(glob)
        if grep is not SENTINEL:
            self.grep = PermissionRuleConfigGuard.return_one_of(grep)
        if list is not SENTINEL:
            self.list = PermissionRuleConfigGuard.return_one_of(list)
        if bash is not SENTINEL:
            self.bash = PermissionRuleConfigGuard.return_one_of(bash)
        if task is not SENTINEL:
            self.task = PermissionRuleConfigGuard.return_one_of(task)
        if external_directory is not SENTINEL:
            self.external_directory = PermissionRuleConfigGuard.return_one_of(
                external_directory
            )
        if todowrite is not SENTINEL:
            self.todowrite = self._enum_matching(
                todowrite, PermissionActionConfig.list(), "todowrite"
            )
        if question is not SENTINEL:
            self.question = self._enum_matching(
                question, PermissionActionConfig.list(), "question"
            )
        if webfetch is not SENTINEL:
            self.webfetch = self._enum_matching(
                webfetch, PermissionActionConfig.list(), "webfetch"
            )
        if websearch is not SENTINEL:
            self.websearch = self._enum_matching(
                websearch, PermissionActionConfig.list(), "websearch"
            )
        if repo_clone is not SENTINEL:
            self.repo_clone = PermissionRuleConfigGuard.return_one_of(repo_clone)
        if repo_overview is not SENTINEL:
            self.repo_overview = PermissionRuleConfigGuard.return_one_of(repo_overview)
        if lsp is not SENTINEL:
            self.lsp = PermissionRuleConfigGuard.return_one_of(lsp)
        if doom_loop is not SENTINEL:
            self.doom_loop = self._enum_matching(
                doom_loop, PermissionActionConfig.list(), "doom_loop"
            )
        if skill is not SENTINEL:
            self.skill = PermissionRuleConfigGuard.return_one_of(skill)
        self._kwargs = kwargs


class PermissionConfigGuard(OneOfBaseModel):
    class_list = {
        "PermissionActionConfigEnum": str,
        "PermissionConfig2": PermissionConfig2,
    }


PermissionConfig = Union[str, PermissionConfig2]
