# This file was generated by liblab | https://liblab.com/

from enum import Enum


class PermissionActionConfig(Enum):
    """An enumeration representing different categories.

    :cvar ASK: "ask"
    :vartype ASK: str
    :cvar ALLOW: "allow"
    :vartype ALLOW: str
    :cvar DENY: "deny"
    :vartype DENY: str
    """

    ASK = "ask"
    ALLOW = "allow"
    DENY = "deny"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, PermissionActionConfig._member_map_.values())
        )
