# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"message_id": "messageID", "call_id": "callID"})
class Tool(BaseModel):
    """Tool

    :param message_id: message_id
    :type message_id: str
    :param call_id: call_id
    :type call_id: str
    """

    def __init__(self, message_id: str, call_id: str, **kwargs):
        """Tool

        :param message_id: message_id
        :type message_id: str
        :param call_id: call_id
        :type call_id: str
        """
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.call_id = self._define_str("call_id", call_id)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "session_id": "sessionID"})
class PermissionRequest(BaseModel):
    """PermissionRequest

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param permission: permission
    :type permission: str
    :param patterns: patterns
    :type patterns: List[str]
    :param metadata: metadata
    :type metadata: dict
    :param always: always
    :type always: List[str]
    :param tool: tool, defaults to None
    :type tool: Tool, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        permission: str,
        patterns: List[str],
        metadata: dict,
        always: List[str],
        tool: Tool = SENTINEL,
        **kwargs
    ):
        """PermissionRequest

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param permission: permission
        :type permission: str
        :param patterns: patterns
        :type patterns: List[str]
        :param metadata: metadata
        :type metadata: dict
        :param always: always
        :type always: List[str]
        :param tool: tool, defaults to None
        :type tool: Tool, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^per")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.permission = self._define_str("permission", permission)
        self.patterns = patterns
        self.metadata = metadata
        self.always = always
        if tool is not SENTINEL:
            self.tool = self._define_object(tool, Tool)
        self._kwargs = kwargs
