# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"id_": "id"})
class ProjectSummary(BaseModel):
    """ProjectSummary

    :param id_: id_
    :type id_: str
    :param name: name, defaults to None
    :type name: str, optional
    :param worktree: worktree
    :type worktree: str
    """

    def __init__(self, id_: str, worktree: str, name: str = SENTINEL, **kwargs):
        """ProjectSummary

        :param id_: id_
        :type id_: str
        :param name: name, defaults to None
        :type name: str, optional
        :param worktree: worktree
        :type worktree: str
        """
        self.id_ = self._define_str("id_", id_)
        if name is not SENTINEL:
            self.name = self._define_str("name", name)
        self.worktree = self._define_str("worktree", worktree)
        self._kwargs = kwargs
