# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .prompt_source import PromptSource


@JsonMap({})
class PromptAgentAttachment(BaseModel):
    """PromptAgentAttachment

    :param name: name
    :type name: str
    :param source: source, defaults to None
    :type source: PromptSource, optional
    """

    def __init__(self, name: str, source: PromptSource = SENTINEL, **kwargs):
        """PromptAgentAttachment

        :param name: name
        :type name: str
        :param source: source, defaults to None
        :type source: PromptSource, optional
        """
        self.name = self._define_str("name", name)
        if source is not SENTINEL:
            self.source = self._define_object(source, PromptSource)
        self._kwargs = kwargs
