# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .prompt_source import PromptSource


class PromptReferenceAttachmentKind(Enum):
    """An enumeration representing different categories.

    :cvar LOCAL: "local"
    :vartype LOCAL: str
    :cvar GIT: "git"
    :vartype GIT: str
    :cvar INVALID: "invalid"
    :vartype INVALID: str
    """

    LOCAL = "local"
    GIT = "git"
    INVALID = "invalid"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, PromptReferenceAttachmentKind._member_map_.values())
        )


@JsonMap({"target_uri": "targetUri"})
class PromptReferenceAttachment(BaseModel):
    """PromptReferenceAttachment

    :param name: name
    :type name: str
    :param kind: kind
    :type kind: PromptReferenceAttachmentKind
    :param uri: uri, defaults to None
    :type uri: str, optional
    :param repository: repository, defaults to None
    :type repository: str, optional
    :param branch: branch, defaults to None
    :type branch: str, optional
    :param target: target, defaults to None
    :type target: str, optional
    :param target_uri: target_uri, defaults to None
    :type target_uri: str, optional
    :param problem: problem, defaults to None
    :type problem: str, optional
    :param source: source, defaults to None
    :type source: PromptSource, optional
    """

    def __init__(
        self,
        name: str,
        kind: PromptReferenceAttachmentKind,
        uri: str = SENTINEL,
        repository: str = SENTINEL,
        branch: str = SENTINEL,
        target: str = SENTINEL,
        target_uri: str = SENTINEL,
        problem: str = SENTINEL,
        source: PromptSource = SENTINEL,
        **kwargs,
    ):
        """PromptReferenceAttachment

        :param name: name
        :type name: str
        :param kind: kind
        :type kind: PromptReferenceAttachmentKind
        :param uri: uri, defaults to None
        :type uri: str, optional
        :param repository: repository, defaults to None
        :type repository: str, optional
        :param branch: branch, defaults to None
        :type branch: str, optional
        :param target: target, defaults to None
        :type target: str, optional
        :param target_uri: target_uri, defaults to None
        :type target_uri: str, optional
        :param problem: problem, defaults to None
        :type problem: str, optional
        :param source: source, defaults to None
        :type source: PromptSource, optional
        """
        self.name = self._define_str("name", name)
        self.kind = self._enum_matching(
            kind, PromptReferenceAttachmentKind.list(), "kind"
        )
        if uri is not SENTINEL:
            self.uri = self._define_str("uri", uri)
        if repository is not SENTINEL:
            self.repository = self._define_str("repository", repository)
        if branch is not SENTINEL:
            self.branch = self._define_str("branch", branch)
        if target is not SENTINEL:
            self.target = self._define_str("target", target)
        if target_uri is not SENTINEL:
            self.target_uri = self._define_str("target_uri", target_uri)
        if problem is not SENTINEL:
            self.problem = self._define_str("problem", problem)
        if source is not SENTINEL:
            self.source = self._define_object(source, PromptSource)
        self._kwargs = kwargs
