# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .provider import Provider


@JsonMap({})
class ProviderListOkResponse(BaseModel):
    """List of providers

    :param all: all
    :type all: List[Provider]
    :param default: default
    :type default: dict
    :param connected: connected
    :type connected: List[str]
    """

    def __init__(
        self, all: List[Provider], default: dict, connected: List[str], **kwargs
    ):
        """List of providers

        :param all: all
        :type all: List[Provider]
        :param default: default
        :type default: dict
        :param connected: connected
        :type connected: List[str]
        """
        self.all = self._define_list(all, Provider)
        self.default = default
        self.connected = connected
        self._kwargs = kwargs
