# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class Method(Enum):
    """An enumeration representing different categories.

    :cvar AUTO: "auto"
    :vartype AUTO: str
    :cvar CODE: "code"
    :vartype CODE: str
    """

    AUTO = "auto"
    CODE = "code"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Method._member_map_.values()))


@JsonMap({})
class ProviderAuthAuthorization(BaseModel):
    """ProviderAuthAuthorization

    :param url: url
    :type url: str
    :param method: method
    :type method: Method
    :param instructions: instructions
    :type instructions: str
    """

    def __init__(self, url: str, method: Method, instructions: str, **kwargs):
        """ProviderAuthAuthorization

        :param url: url
        :type url: str
        :param method: method
        :type method: Method
        :param instructions: instructions
        :type instructions: str
        """
        self.url = self._define_str("url", url)
        self.method = self._enum_matching(method, Method.list(), "method")
        self.instructions = self._define_str("instructions", instructions)
        self._kwargs = kwargs
