# This file was generated by liblab | https://liblab.com/

from enum import Enum
from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .utils.sentinel import SENTINEL


class Timeout2(Enum):
    """An enumeration representing different categories.

    :cvar FALSE: "false"
    :vartype FALSE: str
    """

    FALSE = "false"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Timeout2._member_map_.values()))


class TimeoutGuard(OneOfBaseModel):
    class_list = {"int": int, "Timeout2Enum": str}


Timeout = Union[int, str]


@JsonMap(
    {
        "api_key": "apiKey",
        "base_url": "baseURL",
        "enterprise_url": "enterpriseUrl",
        "set_cache_key": "setCacheKey",
        "chunk_timeout": "chunkTimeout",
    }
)
class ProviderConfigOptions(BaseModel):
    """ProviderConfigOptions

    :param api_key: api_key, defaults to None
    :type api_key: str, optional
    :param base_url: base_url, defaults to None
    :type base_url: str, optional
    :param enterprise_url: enterprise_url, defaults to None
    :type enterprise_url: str, optional
    :param set_cache_key: set_cache_key, defaults to None
    :type set_cache_key: bool, optional
    :param timeout: Timeout in milliseconds for requests to this provider. Default is 300000 (5 minutes). Set to false to disable timeout., defaults to None
    :type timeout: Timeout, optional
    :param chunk_timeout: chunk_timeout, defaults to None
    :type chunk_timeout: int, optional
    """

    def __init__(
        self,
        api_key: str = SENTINEL,
        base_url: str = SENTINEL,
        enterprise_url: str = SENTINEL,
        set_cache_key: bool = SENTINEL,
        timeout: Timeout = SENTINEL,
        chunk_timeout: int = SENTINEL,
        **kwargs
    ):
        """ProviderConfigOptions

        :param api_key: api_key, defaults to None
        :type api_key: str, optional
        :param base_url: base_url, defaults to None
        :type base_url: str, optional
        :param enterprise_url: enterprise_url, defaults to None
        :type enterprise_url: str, optional
        :param set_cache_key: set_cache_key, defaults to None
        :type set_cache_key: bool, optional
        :param timeout: Timeout in milliseconds for requests to this provider. Default is 300000 (5 minutes). Set to false to disable timeout., defaults to None
        :type timeout: Timeout, optional
        :param chunk_timeout: chunk_timeout, defaults to None
        :type chunk_timeout: int, optional
        """
        if api_key is not SENTINEL:
            self.api_key = self._define_str("api_key", api_key)
        if base_url is not SENTINEL:
            self.base_url = self._define_str("base_url", base_url)
        if enterprise_url is not SENTINEL:
            self.enterprise_url = self._define_str("enterprise_url", enterprise_url)
        if set_cache_key is not SENTINEL:
            self.set_cache_key = set_cache_key
        if timeout is not SENTINEL:
            self.timeout = TimeoutGuard.return_one_of(timeout)
        if chunk_timeout is not SENTINEL:
            self.chunk_timeout = self._define_number("chunk_timeout", chunk_timeout)
        self._kwargs = kwargs


class Interleaved1(Enum):
    """An enumeration representing different categories.

    :cvar TRUE: "true"
    :vartype TRUE: str
    """

    TRUE = "true"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Interleaved1._member_map_.values()))


class Interleaved2Field1(Enum):
    """An enumeration representing different categories.

    :cvar REASONINGCONTENT: "reasoning_content"
    :vartype REASONINGCONTENT: str
    :cvar REASONINGDETAILS: "reasoning_details"
    :vartype REASONINGDETAILS: str
    """

    REASONINGCONTENT = "reasoning_content"
    REASONINGDETAILS = "reasoning_details"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Interleaved2Field1._member_map_.values()))


@JsonMap({})
class Interleaved2_1(BaseModel):
    """Interleaved2_1

    :param field: field
    :type field: Interleaved2Field1
    """

    def __init__(self, field: Interleaved2Field1, **kwargs):
        """Interleaved2_1

        :param field: field
        :type field: Interleaved2Field1
        """
        self.field = self._enum_matching(field, Interleaved2Field1.list(), "field")
        self._kwargs = kwargs


class ModelsInterleavedGuard(OneOfBaseModel):
    class_list = {"Interleaved1Enum": str, "Interleaved2_1": Interleaved2_1}


ModelsInterleaved = Union[str, Interleaved2_1]


@JsonMap({})
class ContextOver200k(BaseModel):
    """ContextOver200k

    :param input: input
    :type input: float
    :param output: output
    :type output: float
    :param cache_read: cache_read, defaults to None
    :type cache_read: float, optional
    :param cache_write: cache_write, defaults to None
    :type cache_write: float, optional
    """

    def __init__(
        self,
        input: float,
        output: float,
        cache_read: float = SENTINEL,
        cache_write: float = SENTINEL,
        **kwargs
    ):
        """ContextOver200k

        :param input: input
        :type input: float
        :param output: output
        :type output: float
        :param cache_read: cache_read, defaults to None
        :type cache_read: float, optional
        :param cache_write: cache_write, defaults to None
        :type cache_write: float, optional
        """
        self.input = self._define_number("input", input)
        self.output = self._define_number("output", output)
        if cache_read is not SENTINEL:
            self.cache_read = self._define_number("cache_read", cache_read)
        if cache_write is not SENTINEL:
            self.cache_write = self._define_number("cache_write", cache_write)
        self._kwargs = kwargs


@JsonMap({})
class ModelsCost(BaseModel):
    """ModelsCost

    :param input: input
    :type input: float
    :param output: output
    :type output: float
    :param cache_read: cache_read, defaults to None
    :type cache_read: float, optional
    :param cache_write: cache_write, defaults to None
    :type cache_write: float, optional
    :param context_over_200k: context_over_200k, defaults to None
    :type context_over_200k: ContextOver200k, optional
    """

    def __init__(
        self,
        input: float,
        output: float,
        cache_read: float = SENTINEL,
        cache_write: float = SENTINEL,
        context_over_200k: ContextOver200k = SENTINEL,
        **kwargs
    ):
        """ModelsCost

        :param input: input
        :type input: float
        :param output: output
        :type output: float
        :param cache_read: cache_read, defaults to None
        :type cache_read: float, optional
        :param cache_write: cache_write, defaults to None
        :type cache_write: float, optional
        :param context_over_200k: context_over_200k, defaults to None
        :type context_over_200k: ContextOver200k, optional
        """
        self.input = self._define_number("input", input)
        self.output = self._define_number("output", output)
        if cache_read is not SENTINEL:
            self.cache_read = self._define_number("cache_read", cache_read)
        if cache_write is not SENTINEL:
            self.cache_write = self._define_number("cache_write", cache_write)
        if context_over_200k is not SENTINEL:
            self.context_over_200k = self._define_object(
                context_over_200k, ContextOver200k
            )
        self._kwargs = kwargs


@JsonMap({})
class ModelsLimit(BaseModel):
    """ModelsLimit

    :param context: context
    :type context: float
    :param input: input, defaults to None
    :type input: float, optional
    :param output: output
    :type output: float
    """

    def __init__(
        self, context: float, output: float, input: float = SENTINEL, **kwargs
    ):
        """ModelsLimit

        :param context: context
        :type context: float
        :param input: input, defaults to None
        :type input: float, optional
        :param output: output
        :type output: float
        """
        self.context = self._define_number("context", context)
        if input is not SENTINEL:
            self.input = self._define_number("input", input)
        self.output = self._define_number("output", output)
        self._kwargs = kwargs


class ModalitiesInput(Enum):
    """An enumeration representing different categories.

    :cvar TEXT: "text"
    :vartype TEXT: str
    :cvar AUDIO: "audio"
    :vartype AUDIO: str
    :cvar IMAGE: "image"
    :vartype IMAGE: str
    :cvar VIDEO: "video"
    :vartype VIDEO: str
    :cvar PDF: "pdf"
    :vartype PDF: str
    """

    TEXT = "text"
    AUDIO = "audio"
    IMAGE = "image"
    VIDEO = "video"
    PDF = "pdf"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ModalitiesInput._member_map_.values()))


class ModalitiesOutput(Enum):
    """An enumeration representing different categories.

    :cvar TEXT: "text"
    :vartype TEXT: str
    :cvar AUDIO: "audio"
    :vartype AUDIO: str
    :cvar IMAGE: "image"
    :vartype IMAGE: str
    :cvar VIDEO: "video"
    :vartype VIDEO: str
    :cvar PDF: "pdf"
    :vartype PDF: str
    """

    TEXT = "text"
    AUDIO = "audio"
    IMAGE = "image"
    VIDEO = "video"
    PDF = "pdf"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ModalitiesOutput._member_map_.values()))


@JsonMap({})
class Modalities(BaseModel):
    """Modalities

    :param input: input
    :type input: List[ModalitiesInput]
    :param output: output
    :type output: List[ModalitiesOutput]
    """

    def __init__(
        self, input: List[ModalitiesInput], output: List[ModalitiesOutput], **kwargs
    ):
        """Modalities

        :param input: input
        :type input: List[ModalitiesInput]
        :param output: output
        :type output: List[ModalitiesOutput]
        """
        self.input = self._define_list(input, ModalitiesInput)
        self.output = self._define_list(output, ModalitiesOutput)
        self._kwargs = kwargs


class ModelsStatus(Enum):
    """An enumeration representing different categories.

    :cvar ALPHA: "alpha"
    :vartype ALPHA: str
    :cvar BETA: "beta"
    :vartype BETA: str
    :cvar DEPRECATED: "deprecated"
    :vartype DEPRECATED: str
    :cvar ACTIVE: "active"
    :vartype ACTIVE: str
    """

    ALPHA = "alpha"
    BETA = "beta"
    DEPRECATED = "deprecated"
    ACTIVE = "active"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ModelsStatus._member_map_.values()))


@JsonMap({})
class ModelsProvider(BaseModel):
    """ModelsProvider

    :param npm: npm, defaults to None
    :type npm: str, optional
    :param api: api, defaults to None
    :type api: str, optional
    """

    def __init__(self, npm: str = SENTINEL, api: str = SENTINEL, **kwargs):
        """ModelsProvider

        :param npm: npm, defaults to None
        :type npm: str, optional
        :param api: api, defaults to None
        :type api: str, optional
        """
        if npm is not SENTINEL:
            self.npm = self._define_str("npm", npm)
        if api is not SENTINEL:
            self.api = self._define_str("api", api)
        self._kwargs = kwargs


@JsonMap({})
class ModelsVariants(BaseModel):
    """ModelsVariants

    :param disabled: disabled, defaults to None
    :type disabled: bool, optional
    """

    def __init__(self, disabled: bool = SENTINEL, **kwargs):
        """ModelsVariants

        :param disabled: disabled, defaults to None
        :type disabled: bool, optional
        """
        if disabled is not SENTINEL:
            self.disabled = disabled
        self._kwargs = kwargs


@JsonMap({"id_": "id"})
class Models(BaseModel):
    """Models

    :param id_: id_, defaults to None
    :type id_: str, optional
    :param name: name, defaults to None
    :type name: str, optional
    :param family: family, defaults to None
    :type family: str, optional
    :param release_date: release_date, defaults to None
    :type release_date: str, optional
    :param attachment: attachment, defaults to None
    :type attachment: bool, optional
    :param reasoning: reasoning, defaults to None
    :type reasoning: bool, optional
    :param temperature: temperature, defaults to None
    :type temperature: bool, optional
    :param tool_call: tool_call, defaults to None
    :type tool_call: bool, optional
    :param interleaved: interleaved, defaults to None
    :type interleaved: ModelsInterleaved, optional
    :param cost: cost, defaults to None
    :type cost: ModelsCost, optional
    :param limit: limit, defaults to None
    :type limit: ModelsLimit, optional
    :param modalities: modalities, defaults to None
    :type modalities: Modalities, optional
    :param experimental: experimental, defaults to None
    :type experimental: bool, optional
    :param status: status, defaults to None
    :type status: ModelsStatus, optional
    :param provider: provider, defaults to None
    :type provider: ModelsProvider, optional
    :param options: options, defaults to None
    :type options: dict, optional
    :param headers: headers, defaults to None
    :type headers: dict, optional
    :param variants: Variant-specific configuration, defaults to None
    :type variants: dict, optional
    """

    def __init__(
        self,
        id_: str = SENTINEL,
        name: str = SENTINEL,
        family: str = SENTINEL,
        release_date: str = SENTINEL,
        attachment: bool = SENTINEL,
        reasoning: bool = SENTINEL,
        temperature: bool = SENTINEL,
        tool_call: bool = SENTINEL,
        interleaved: ModelsInterleaved = SENTINEL,
        cost: ModelsCost = SENTINEL,
        limit: ModelsLimit = SENTINEL,
        modalities: Modalities = SENTINEL,
        experimental: bool = SENTINEL,
        status: ModelsStatus = SENTINEL,
        provider: ModelsProvider = SENTINEL,
        options: dict = SENTINEL,
        headers: dict = SENTINEL,
        variants: dict = SENTINEL,
        **kwargs
    ):
        """Models

        :param id_: id_, defaults to None
        :type id_: str, optional
        :param name: name, defaults to None
        :type name: str, optional
        :param family: family, defaults to None
        :type family: str, optional
        :param release_date: release_date, defaults to None
        :type release_date: str, optional
        :param attachment: attachment, defaults to None
        :type attachment: bool, optional
        :param reasoning: reasoning, defaults to None
        :type reasoning: bool, optional
        :param temperature: temperature, defaults to None
        :type temperature: bool, optional
        :param tool_call: tool_call, defaults to None
        :type tool_call: bool, optional
        :param interleaved: interleaved, defaults to None
        :type interleaved: ModelsInterleaved, optional
        :param cost: cost, defaults to None
        :type cost: ModelsCost, optional
        :param limit: limit, defaults to None
        :type limit: ModelsLimit, optional
        :param modalities: modalities, defaults to None
        :type modalities: Modalities, optional
        :param experimental: experimental, defaults to None
        :type experimental: bool, optional
        :param status: status, defaults to None
        :type status: ModelsStatus, optional
        :param provider: provider, defaults to None
        :type provider: ModelsProvider, optional
        :param options: options, defaults to None
        :type options: dict, optional
        :param headers: headers, defaults to None
        :type headers: dict, optional
        :param variants: Variant-specific configuration, defaults to None
        :type variants: dict, optional
        """
        if id_ is not SENTINEL:
            self.id_ = self._define_str("id_", id_)
        if name is not SENTINEL:
            self.name = self._define_str("name", name)
        if family is not SENTINEL:
            self.family = self._define_str("family", family)
        if release_date is not SENTINEL:
            self.release_date = self._define_str("release_date", release_date)
        if attachment is not SENTINEL:
            self.attachment = attachment
        if reasoning is not SENTINEL:
            self.reasoning = reasoning
        if temperature is not SENTINEL:
            self.temperature = temperature
        if tool_call is not SENTINEL:
            self.tool_call = tool_call
        if interleaved is not SENTINEL:
            self.interleaved = ModelsInterleavedGuard.return_one_of(interleaved)
        if cost is not SENTINEL:
            self.cost = self._define_object(cost, ModelsCost)
        if limit is not SENTINEL:
            self.limit = self._define_object(limit, ModelsLimit)
        if modalities is not SENTINEL:
            self.modalities = self._define_object(modalities, Modalities)
        if experimental is not SENTINEL:
            self.experimental = experimental
        if status is not SENTINEL:
            self.status = self._enum_matching(status, ModelsStatus.list(), "status")
        if provider is not SENTINEL:
            self.provider = self._define_object(provider, ModelsProvider)
        if options is not SENTINEL:
            self.options = options
        if headers is not SENTINEL:
            self.headers = headers
        if variants is not SENTINEL:
            self.variants = variants
        self._kwargs = kwargs


@JsonMap({"id_": "id"})
class ProviderConfig(BaseModel):
    """ProviderConfig

    :param api: api, defaults to None
    :type api: str, optional
    :param name: name, defaults to None
    :type name: str, optional
    :param env: env, defaults to None
    :type env: List[str], optional
    :param id_: id_, defaults to None
    :type id_: str, optional
    :param npm: npm, defaults to None
    :type npm: str, optional
    :param whitelist: whitelist, defaults to None
    :type whitelist: List[str], optional
    :param blacklist: blacklist, defaults to None
    :type blacklist: List[str], optional
    :param options: options, defaults to None
    :type options: ProviderConfigOptions, optional
    :param models: models, defaults to None
    :type models: dict, optional
    """

    def __init__(
        self,
        api: str = SENTINEL,
        name: str = SENTINEL,
        env: List[str] = SENTINEL,
        id_: str = SENTINEL,
        npm: str = SENTINEL,
        whitelist: List[str] = SENTINEL,
        blacklist: List[str] = SENTINEL,
        options: ProviderConfigOptions = SENTINEL,
        models: dict = SENTINEL,
        **kwargs
    ):
        """ProviderConfig

        :param api: api, defaults to None
        :type api: str, optional
        :param name: name, defaults to None
        :type name: str, optional
        :param env: env, defaults to None
        :type env: List[str], optional
        :param id_: id_, defaults to None
        :type id_: str, optional
        :param npm: npm, defaults to None
        :type npm: str, optional
        :param whitelist: whitelist, defaults to None
        :type whitelist: List[str], optional
        :param blacklist: blacklist, defaults to None
        :type blacklist: List[str], optional
        :param options: options, defaults to None
        :type options: ProviderConfigOptions, optional
        :param models: models, defaults to None
        :type models: dict, optional
        """
        if api is not SENTINEL:
            self.api = self._define_str("api", api)
        if name is not SENTINEL:
            self.name = self._define_str("name", name)
        if env is not SENTINEL:
            self.env = env
        if id_ is not SENTINEL:
            self.id_ = self._define_str("id_", id_)
        if npm is not SENTINEL:
            self.npm = self._define_str("npm", npm)
        if whitelist is not SENTINEL:
            self.whitelist = whitelist
        if blacklist is not SENTINEL:
            self.blacklist = blacklist
        if options is not SENTINEL:
            self.options = self._define_object(options, ProviderConfigOptions)
        if models is not SENTINEL:
            self.models = models
        self._kwargs = kwargs
