# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class ProviderAuthErrorName(Enum):
    """An enumeration representing different categories.

    :cvar PROVIDERAUTHERROR: "ProviderAuthError"
    :vartype PROVIDERAUTHERROR: str
    """

    PROVIDERAUTHERROR = "ProviderAuthError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ProviderAuthErrorName._member_map_.values()))


@JsonMap({"provider_id": "providerID"})
class ProviderAuthErrorData(BaseModel):
    """ProviderAuthErrorData

    :param provider_id: provider_id
    :type provider_id: str
    :param message: message
    :type message: str
    """

    def __init__(self, provider_id: str, message: str, **kwargs):
        """ProviderAuthErrorData

        :param provider_id: provider_id
        :type provider_id: str
        :param message: message
        :type message: str
        """
        self.provider_id = self._define_str("provider_id", provider_id)
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({})
class ProviderAuthError(BaseModel):
    """ProviderAuthError

    :param name: name
    :type name: ProviderAuthErrorName
    :param data: data
    :type data: ProviderAuthErrorData
    """

    def __init__(
        self, name: ProviderAuthErrorName, data: ProviderAuthErrorData, **kwargs
    ):
        """ProviderAuthError

        :param name: name
        :type name: ProviderAuthErrorName
        :param data: data
        :type data: ProviderAuthErrorData
        """
        self.name = self._enum_matching(name, ProviderAuthErrorName.list(), "name")
        self.data = self._define_object(data, ProviderAuthErrorData)
        self._kwargs = kwargs
