# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class ProviderAuthError1Name(Enum):
    """An enumeration representing different categories.

    :cvar BADREQUEST: "BadRequest"
    :vartype BADREQUEST: str
    :cvar PROVIDERAUTHOAUTHMISSING: "ProviderAuthOauthMissing"
    :vartype PROVIDERAUTHOAUTHMISSING: str
    :cvar PROVIDERAUTHOAUTHCODEMISSING: "ProviderAuthOauthCodeMissing"
    :vartype PROVIDERAUTHOAUTHCODEMISSING: str
    :cvar PROVIDERAUTHOAUTHCALLBACKFAILED: "ProviderAuthOauthCallbackFailed"
    :vartype PROVIDERAUTHOAUTHCALLBACKFAILED: str
    :cvar PROVIDERAUTHVALIDATIONFAILED: "ProviderAuthValidationFailed"
    :vartype PROVIDERAUTHVALIDATIONFAILED: str
    """

    BADREQUEST = "BadRequest"
    PROVIDERAUTHOAUTHMISSING = "ProviderAuthOauthMissing"
    PROVIDERAUTHOAUTHCODEMISSING = "ProviderAuthOauthCodeMissing"
    PROVIDERAUTHOAUTHCALLBACKFAILED = "ProviderAuthOauthCallbackFailed"
    PROVIDERAUTHVALIDATIONFAILED = "ProviderAuthValidationFailed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, ProviderAuthError1Name._member_map_.values())
        )


@JsonMap({"provider_id": "providerID"})
class ProviderAuthError1Data(BaseModel):
    """ProviderAuthError1Data

    :param provider_id: provider_id, defaults to None
    :type provider_id: str, optional
    :param field: field, defaults to None
    :type field: str, optional
    :param message: message, defaults to None
    :type message: str, optional
    :param kind: kind, defaults to None
    :type kind: str, optional
    """

    def __init__(
        self,
        provider_id: str = SENTINEL,
        field: str = SENTINEL,
        message: str = SENTINEL,
        kind: str = SENTINEL,
        **kwargs
    ):
        """ProviderAuthError1Data

        :param provider_id: provider_id, defaults to None
        :type provider_id: str, optional
        :param field: field, defaults to None
        :type field: str, optional
        :param message: message, defaults to None
        :type message: str, optional
        :param kind: kind, defaults to None
        :type kind: str, optional
        """
        if provider_id is not SENTINEL:
            self.provider_id = self._define_str("provider_id", provider_id)
        if field is not SENTINEL:
            self.field = self._define_str("field", field)
        if message is not SENTINEL:
            self.message = self._define_str("message", message)
        if kind is not SENTINEL:
            self.kind = self._define_str("kind", kind)
        self._kwargs = kwargs


@JsonMap({})
class ProviderAuthError1(ApiError):
    """ProviderAuthError1

    :param name: name
    :type name: ProviderAuthError1Name
    :param data: data
    :type data: ProviderAuthError1Data
    """

    def __init__(
        self, name: ProviderAuthError1Name, data: ProviderAuthError1Data, **kwargs
    ):
        """ProviderAuthError1

        :param name: name
        :type name: ProviderAuthError1Name
        :param data: data
        :type data: ProviderAuthError1Data
        """
        self.name = self._enum_matching(name, ProviderAuthError1Name.list(), "name")
        self.data = self._define_object(data, ProviderAuthError1Data)
        self._kwargs = kwargs
