# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .model import Model


class ProviderSource(Enum):
    """An enumeration representing different categories.

    :cvar ENV: "env"
    :vartype ENV: str
    :cvar CONFIG: "config"
    :vartype CONFIG: str
    :cvar CUSTOM: "custom"
    :vartype CUSTOM: str
    :cvar API: "api"
    :vartype API: str
    """

    ENV = "env"
    CONFIG = "config"
    CUSTOM = "custom"
    API = "api"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ProviderSource._member_map_.values()))


@JsonMap({"id_": "id"})
class Provider(BaseModel):
    """Provider

    :param id_: id_
    :type id_: str
    :param name: name
    :type name: str
    :param source: source
    :type source: ProviderSource
    :param env: env
    :type env: List[str]
    :param key: key, defaults to None
    :type key: str, optional
    :param options: options
    :type options: dict
    :param models: models
    :type models: dict
    """

    def __init__(
        self,
        id_: str,
        name: str,
        source: ProviderSource,
        env: List[str],
        options: dict,
        models: dict,
        key: str = SENTINEL,
        **kwargs,
    ):
        """Provider

        :param id_: id_
        :type id_: str
        :param name: name
        :type name: str
        :param source: source
        :type source: ProviderSource
        :param env: env
        :type env: List[str]
        :param key: key, defaults to None
        :type key: str, optional
        :param options: options
        :type options: dict
        :param models: models
        :type models: dict
        """
        self.id_ = self._define_str("id_", id_)
        self.name = self._define_str("name", name)
        self.source = self._enum_matching(source, ProviderSource.list(), "source")
        self.env = env
        if key is not SENTINEL:
            self.key = self._define_str("key", key)
        self.options = options
        self.models = models
        self._kwargs = kwargs
