# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class Size(BaseModel):
    """Size

    :param rows: rows
    :type rows: int
    :param cols: cols
    :type cols: int
    """

    def __init__(self, rows: int, cols: int, **kwargs):
        """Size

        :param rows: rows
        :type rows: int
        :param cols: cols
        :type cols: int
        """
        self.rows = self._define_number("rows", rows)
        self.cols = self._define_number("cols", cols)
        self._kwargs = kwargs


@JsonMap({})
class PtyUpdateRequest(BaseModel):
    """PtyUpdateRequest

    :param title: title, defaults to None
    :type title: str, optional
    :param size: size, defaults to None
    :type size: Size, optional
    """

    def __init__(self, title: str = SENTINEL, size: Size = SENTINEL, **kwargs):
        """PtyUpdateRequest

        :param title: title, defaults to None
        :type title: str, optional
        :param size: size, defaults to None
        :type size: Size, optional
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        if size is not SENTINEL:
            self.size = self._define_object(size, Size)
        self._kwargs = kwargs
