# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class PtyConnectTokenOkResponse(BaseModel):
    """WebSocket connect token

    :param ticket: ticket
    :type ticket: str
    :param expires_in: expires_in
    :type expires_in: int
    """

    def __init__(self, ticket: str, expires_in: int, **kwargs):
        """WebSocket connect token

        :param ticket: ticket
        :type ticket: str
        :param expires_in: expires_in
        :type expires_in: int
        """
        self.ticket = self._define_str("ticket", ticket)
        self.expires_in = self._define_number("expires_in", expires_in)
        self._kwargs = kwargs
