# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"session_id": "sessionID", "request_id": "requestID"})
class QuestionRejected(BaseModel):
    """QuestionRejected

    :param session_id: session_id
    :type session_id: str
    :param request_id: request_id
    :type request_id: str
    """

    def __init__(self, session_id: str, request_id: str, **kwargs):
        """QuestionRejected

        :param session_id: session_id
        :type session_id: str
        :param request_id: request_id
        :type request_id: str
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.request_id = self._define_str("request_id", request_id, pattern="^que")
        self._kwargs = kwargs
