# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Start(BaseModel):
    """Start

    :param line: line
    :type line: int
    :param character: character
    :type character: int
    """

    def __init__(self, line: int, character: int, **kwargs):
        """Start

        :param line: line
        :type line: int
        :param character: character
        :type character: int
        """
        self.line = self._define_number("line", line, ge=0)
        self.character = self._define_number("character", character, ge=0)
        self._kwargs = kwargs


@JsonMap({})
class End(BaseModel):
    """End

    :param line: line
    :type line: int
    :param character: character
    :type character: int
    """

    def __init__(self, line: int, character: int, **kwargs):
        """End

        :param line: line
        :type line: int
        :param character: character
        :type character: int
        """
        self.line = self._define_number("line", line, ge=0)
        self.character = self._define_number("character", character, ge=0)
        self._kwargs = kwargs


@JsonMap({})
class Range(BaseModel):
    """Range

    :param start: start
    :type start: Start
    :param end: end
    :type end: End
    """

    def __init__(self, start: Start, end: End, **kwargs):
        """Range

        :param start: start
        :type start: Start
        :param end: end
        :type end: End
        """
        self.start = self._define_object(start, Start)
        self.end = self._define_object(end, End)
        self._kwargs = kwargs
