# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class ReasoningPartType(Enum):
    """An enumeration representing different categories.

    :cvar REASONING: "reasoning"
    :vartype REASONING: str
    """

    REASONING = "reasoning"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ReasoningPartType._member_map_.values()))


@JsonMap({})
class ReasoningPartTime(BaseModel):
    """ReasoningPartTime

    :param start: start
    :type start: int
    :param end: end, defaults to None
    :type end: int, optional
    """

    def __init__(self, start: int, end: int = SENTINEL, **kwargs):
        """ReasoningPartTime

        :param start: start
        :type start: int
        :param end: end, defaults to None
        :type end: int, optional
        """
        self.start = self._define_number("start", start, ge=0)
        if end is not SENTINEL:
            self.end = self._define_number("end", end, ge=0)
        self._kwargs = kwargs


@JsonMap(
    {"id_": "id", "session_id": "sessionID", "message_id": "messageID", "type_": "type"}
)
class ReasoningPart(BaseModel):
    """ReasoningPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: ReasoningPartType
    :param text: text
    :type text: str
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    :param time: time
    :type time: ReasoningPartTime
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: ReasoningPartType,
        text: str,
        time: ReasoningPartTime,
        metadata: dict = SENTINEL,
        **kwargs
    ):
        """ReasoningPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: ReasoningPartType
        :param text: text
        :type text: str
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        :param time: time
        :type time: ReasoningPartTime
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, ReasoningPartType.list(), "type_")
        self.text = self._define_str("text", text)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self.time = self._define_object(time, ReasoningPartTime)
        self._kwargs = kwargs
