# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .file_part_source_text import FilePartSourceText


class ResourceSourceType(Enum):
    """An enumeration representing different categories.

    :cvar RESOURCE: "resource"
    :vartype RESOURCE: str
    """

    RESOURCE = "resource"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ResourceSourceType._member_map_.values()))


@JsonMap({"type_": "type", "client_name": "clientName"})
class ResourceSource(BaseModel):
    """ResourceSource

    :param text: text
    :type text: FilePartSourceText
    :param type_: type_
    :type type_: ResourceSourceType
    :param client_name: client_name
    :type client_name: str
    :param uri: uri
    :type uri: str
    """

    def __init__(
        self,
        text: FilePartSourceText,
        type_: ResourceSourceType,
        client_name: str,
        uri: str,
        **kwargs,
    ):
        """ResourceSource

        :param text: text
        :type text: FilePartSourceText
        :param type_: type_
        :type type_: ResourceSourceType
        :param client_name: client_name
        :type client_name: str
        :param uri: uri
        :type uri: str
        """
        self.text = self._define_object(text, FilePartSourceText)
        self.type_ = self._enum_matching(type_, ResourceSourceType.list(), "type_")
        self.client_name = self._define_str("client_name", client_name)
        self.uri = self._define_str("uri", uri)
        self._kwargs = kwargs
