# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel
from .utils.sentinel import SENTINEL
from .output_format import OutputFormat, OutputFormatGuard
from .output_format_text import OutputFormatText
from .output_format_json_schema import OutputFormatJsonSchema
from .text_part_input import TextPartInput
from .file_part_input import FilePartInput
from .agent_part_input import AgentPartInput
from .subtask_part_input import SubtaskPartInput


@JsonMap({"provider_id": "providerID", "model_id": "modelID"})
class SessionPromptAsyncRequestModel(BaseModel):
    """SessionPromptAsyncRequestModel

    :param provider_id: provider_id
    :type provider_id: str
    :param model_id: model_id
    :type model_id: str
    """

    def __init__(self, provider_id: str, model_id: str, **kwargs):
        """SessionPromptAsyncRequestModel

        :param provider_id: provider_id
        :type provider_id: str
        :param model_id: model_id
        :type model_id: str
        """
        self.provider_id = self._define_str("provider_id", provider_id)
        self.model_id = self._define_str("model_id", model_id)
        self._kwargs = kwargs


class SessionPromptAsyncRequestPartsGuard(OneOfBaseModel):
    class_list = {
        "TextPartInput": TextPartInput,
        "FilePartInput": FilePartInput,
        "AgentPartInput": AgentPartInput,
        "SubtaskPartInput": SubtaskPartInput,
    }


SessionPromptAsyncRequestParts = Union[
    TextPartInput, FilePartInput, AgentPartInput, SubtaskPartInput
]


@JsonMap({"message_id": "messageID", "no_reply": "noReply"})
class SessionPromptAsyncRequest(BaseModel):
    """SessionPromptAsyncRequest

    :param message_id: message_id, defaults to None
    :type message_id: str, optional
    :param model: model, defaults to None
    :type model: SessionPromptAsyncRequestModel, optional
    :param agent: agent, defaults to None
    :type agent: str, optional
    :param no_reply: no_reply, defaults to None
    :type no_reply: bool, optional
    :param tools: tools, defaults to None
    :type tools: dict, optional
    :param format: format, defaults to None
    :type format: OutputFormat, optional
    :param system: system, defaults to None
    :type system: str, optional
    :param variant: variant, defaults to None
    :type variant: str, optional
    :param parts: parts
    :type parts: List[SessionPromptAsyncRequestParts]
    """

    def __init__(
        self,
        parts: List[SessionPromptAsyncRequestParts],
        message_id: str = SENTINEL,
        model: SessionPromptAsyncRequestModel = SENTINEL,
        agent: str = SENTINEL,
        no_reply: bool = SENTINEL,
        tools: dict = SENTINEL,
        format: OutputFormat = SENTINEL,
        system: str = SENTINEL,
        variant: str = SENTINEL,
        **kwargs,
    ):
        """SessionPromptAsyncRequest

        :param message_id: message_id, defaults to None
        :type message_id: str, optional
        :param model: model, defaults to None
        :type model: SessionPromptAsyncRequestModel, optional
        :param agent: agent, defaults to None
        :type agent: str, optional
        :param no_reply: no_reply, defaults to None
        :type no_reply: bool, optional
        :param tools: tools, defaults to None
        :type tools: dict, optional
        :param format: format, defaults to None
        :type format: OutputFormat, optional
        :param system: system, defaults to None
        :type system: str, optional
        :param variant: variant, defaults to None
        :type variant: str, optional
        :param parts: parts
        :type parts: List[SessionPromptAsyncRequestParts]
        """
        if message_id is not SENTINEL:
            self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        if model is not SENTINEL:
            self.model = self._define_object(model, SessionPromptAsyncRequestModel)
        if agent is not SENTINEL:
            self.agent = self._define_str("agent", agent)
        if no_reply is not SENTINEL:
            self.no_reply = no_reply
        if tools is not SENTINEL:
            self.tools = tools
        if format is not SENTINEL:
            self.format = OutputFormatGuard.return_one_of(format)
        if system is not SENTINEL:
            self.system = self._define_str("system", system)
        if variant is not SENTINEL:
            self.variant = self._define_str("variant", variant)
        self.parts = self._define_list(parts, SessionPromptAsyncRequestParts)
        self._kwargs = kwargs
