# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"provider_id": "providerID", "model_id": "modelID"})
class SessionShellRequestModel(BaseModel):
    """SessionShellRequestModel

    :param provider_id: provider_id
    :type provider_id: str
    :param model_id: model_id
    :type model_id: str
    """

    def __init__(self, provider_id: str, model_id: str, **kwargs):
        """SessionShellRequestModel

        :param provider_id: provider_id
        :type provider_id: str
        :param model_id: model_id
        :type model_id: str
        """
        self.provider_id = self._define_str("provider_id", provider_id)
        self.model_id = self._define_str("model_id", model_id)
        self._kwargs = kwargs


@JsonMap({"message_id": "messageID"})
class SessionShellRequest(BaseModel):
    """SessionShellRequest

    :param message_id: message_id, defaults to None
    :type message_id: str, optional
    :param agent: agent
    :type agent: str
    :param model: model, defaults to None
    :type model: SessionShellRequestModel, optional
    :param command: command
    :type command: str
    """

    def __init__(
        self,
        agent: str,
        command: str,
        message_id: str = SENTINEL,
        model: SessionShellRequestModel = SENTINEL,
        **kwargs
    ):
        """SessionShellRequest

        :param message_id: message_id, defaults to None
        :type message_id: str, optional
        :param agent: agent
        :type agent: str
        :param model: model, defaults to None
        :type model: SessionShellRequestModel, optional
        :param command: command
        :type command: str
        """
        if message_id is not SENTINEL:
            self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.agent = self._define_str("agent", agent)
        if model is not SENTINEL:
            self.model = self._define_object(model, SessionShellRequestModel)
        self.command = self._define_str("command", command)
        self._kwargs = kwargs
