# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class SessionMessageToolStatePendingStatus(Enum):
    """An enumeration representing different categories.

    :cvar PENDING: "pending"
    :vartype PENDING: str
    """

    PENDING = "pending"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SessionMessageToolStatePendingStatus._member_map_.values(),
            )
        )


@JsonMap({})
class SessionMessageToolStatePending(BaseModel):
    """SessionMessageToolStatePending

    :param status: status
    :type status: SessionMessageToolStatePendingStatus
    :param input: input
    :type input: str
    """

    def __init__(
        self, status: SessionMessageToolStatePendingStatus, input: str, **kwargs
    ):
        """SessionMessageToolStatePending

        :param status: status
        :type status: SessionMessageToolStatePendingStatus
        :param input: input
        :type input: str
        """
        self.status = self._enum_matching(
            status, SessionMessageToolStatePendingStatus.list(), "status"
        )
        self.input = self._define_str("input", input)
        self._kwargs = kwargs
