# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .message import Message, MessageGuard
from .user_message import UserMessage
from .assistant_message import AssistantMessage
from .part import Part, PartGuard
from .text_part import TextPart
from .subtask_part import SubtaskPart
from .reasoning_part import ReasoningPart
from .file_part import FilePart
from .tool_part import ToolPart
from .step_start_part import StepStartPart
from .step_finish_part import StepFinishPart
from .snapshot_part import SnapshotPart
from .patch_part import PatchPart
from .agent_part import AgentPart
from .retry_part import RetryPart
from .compaction_part import CompactionPart


@JsonMap({})
class SessionMessageOkResponse(BaseModel):
    """Message

    :param info: info
    :type info: Message
    :param parts: parts
    :type parts: List[Part]
    """

    def __init__(self, info: Message, parts: List[Part], **kwargs):
        """Message

        :param info: info
        :type info: Message
        :param parts: parts
        :type parts: List[Part]
        """
        self.info = MessageGuard.return_one_of(info)
        self.parts = self._define_list(parts, Part)
        self._kwargs = kwargs
