# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap(
    {
        "status_code": "statusCode",
        "is_retryable": "isRetryable",
        "response_headers": "responseHeaders",
        "response_body": "responseBody",
    }
)
class SessionNextRetryError(BaseModel):
    """SessionNextRetryError

    :param message: message
    :type message: str
    :param status_code: status_code, defaults to None
    :type status_code: float, optional
    :param is_retryable: is_retryable
    :type is_retryable: bool
    :param response_headers: response_headers, defaults to None
    :type response_headers: dict, optional
    :param response_body: response_body, defaults to None
    :type response_body: str, optional
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(
        self,
        message: str,
        is_retryable: bool,
        status_code: float = SENTINEL,
        response_headers: dict = SENTINEL,
        response_body: str = SENTINEL,
        metadata: dict = SENTINEL,
        **kwargs
    ):
        """SessionNextRetryError

        :param message: message
        :type message: str
        :param status_code: status_code, defaults to None
        :type status_code: float, optional
        :param is_retryable: is_retryable
        :type is_retryable: bool
        :param response_headers: response_headers, defaults to None
        :type response_headers: dict, optional
        :param response_body: response_body, defaults to None
        :type response_body: str, optional
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.message = self._define_str("message", message)
        if status_code is not SENTINEL:
            self.status_code = self._define_number("status_code", status_code)
        self.is_retryable = is_retryable
        if response_headers is not SENTINEL:
            self.response_headers = response_headers
        if response_body is not SENTINEL:
            self.response_body = self._define_str("response_body", response_body)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs
