# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class SessionMessageModelSwitchedTime(BaseModel):
    """SessionMessageModelSwitchedTime

    :param created: created
    :type created: float
    """

    def __init__(self, created: float, **kwargs):
        """SessionMessageModelSwitchedTime

        :param created: created
        :type created: float
        """
        self.created = self._define_number("created", created)
        self._kwargs = kwargs


class SessionMessageModelSwitchedType(Enum):
    """An enumeration representing different categories.

    :cvar MODELSWITCHED: "model-switched"
    :vartype MODELSWITCHED: str
    """

    MODELSWITCHED = "model-switched"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, SessionMessageModelSwitchedType._member_map_.values()
            )
        )


@JsonMap({"id_": "id", "provider_id": "providerID"})
class SessionMessageModelSwitchedModel(BaseModel):
    """SessionMessageModelSwitchedModel

    :param id_: id_
    :type id_: str
    :param provider_id: provider_id
    :type provider_id: str
    :param variant: variant
    :type variant: str
    """

    def __init__(self, id_: str, provider_id: str, variant: str, **kwargs):
        """SessionMessageModelSwitchedModel

        :param id_: id_
        :type id_: str
        :param provider_id: provider_id
        :type provider_id: str
        :param variant: variant
        :type variant: str
        """
        self.id_ = self._define_str("id_", id_)
        self.provider_id = self._define_str("provider_id", provider_id)
        self.variant = self._define_str("variant", variant)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "type_": "type"})
class SessionMessageModelSwitched(BaseModel):
    """SessionMessageModelSwitched

    :param id_: id_
    :type id_: str
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    :param time: time
    :type time: SessionMessageModelSwitchedTime
    :param type_: type_
    :type type_: SessionMessageModelSwitchedType
    :param model: model
    :type model: SessionMessageModelSwitchedModel
    """

    def __init__(
        self,
        id_: str,
        time: SessionMessageModelSwitchedTime,
        type_: SessionMessageModelSwitchedType,
        model: SessionMessageModelSwitchedModel,
        metadata: dict = SENTINEL,
        **kwargs
    ):
        """SessionMessageModelSwitched

        :param id_: id_
        :type id_: str
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        :param time: time
        :type time: SessionMessageModelSwitchedTime
        :param type_: type_
        :type type_: SessionMessageModelSwitchedType
        :param model: model
        :type model: SessionMessageModelSwitchedModel
        """
        self.id_ = self._define_str("id_", id_)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self.time = self._define_object(time, SessionMessageModelSwitchedTime)
        self.type_ = self._enum_matching(
            type_, SessionMessageModelSwitchedType.list(), "type_"
        )
        self.model = self._define_object(model, SessionMessageModelSwitchedModel)
        self._kwargs = kwargs
