# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"message_id": "messageID", "part_id": "partID"})
class SessionRevertRequest(BaseModel):
    """SessionRevertRequest

    :param message_id: message_id
    :type message_id: str
    :param part_id: part_id, defaults to None
    :type part_id: str, optional
    """

    def __init__(self, message_id: str, part_id: str = SENTINEL, **kwargs):
        """SessionRevertRequest

        :param message_id: message_id
        :type message_id: str
        :param part_id: part_id, defaults to None
        :type part_id: str, optional
        """
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        if part_id is not SENTINEL:
            self.part_id = self._define_str("part_id", part_id, pattern="^prt")
        self._kwargs = kwargs
