# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .permission_rule import PermissionRule


@JsonMap({})
class SessionUpdateRequestTime(BaseModel):
    """SessionUpdateRequestTime

    :param archived: archived, defaults to None
    :type archived: float, optional
    """

    def __init__(self, archived: float = SENTINEL, **kwargs):
        """SessionUpdateRequestTime

        :param archived: archived, defaults to None
        :type archived: float, optional
        """
        if archived is not SENTINEL:
            self.archived = self._define_number("archived", archived)
        self._kwargs = kwargs


@JsonMap({})
class SessionUpdateRequest(BaseModel):
    """SessionUpdateRequest

    :param title: title, defaults to None
    :type title: str, optional
    :param permission: permission, defaults to None
    :type permission: List[PermissionRule], optional
    :param time: time, defaults to None
    :type time: SessionUpdateRequestTime, optional
    """

    def __init__(
        self,
        title: str = SENTINEL,
        permission: List[PermissionRule] = SENTINEL,
        time: SessionUpdateRequestTime = SENTINEL,
        **kwargs,
    ):
        """SessionUpdateRequest

        :param title: title, defaults to None
        :type title: str, optional
        :param permission: permission, defaults to None
        :type permission: List[PermissionRule], optional
        :param time: time, defaults to None
        :type time: SessionUpdateRequestTime, optional
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        if permission is not SENTINEL:
            self.permission = self._define_list(permission, PermissionRule)
        if time is not SENTINEL:
            self.time = self._define_object(time, SessionUpdateRequestTime)
        self._kwargs = kwargs
