# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"id_": "id", "provider_id": "providerID"})
class SessionInfoModel(BaseModel):
    """SessionInfoModel

    :param id_: id_
    :type id_: str
    :param provider_id: provider_id
    :type provider_id: str
    :param variant: variant
    :type variant: str
    """

    def __init__(self, id_: str, provider_id: str, variant: str, **kwargs):
        """SessionInfoModel

        :param id_: id_
        :type id_: str
        :param provider_id: provider_id
        :type provider_id: str
        :param variant: variant
        :type variant: str
        """
        self.id_ = self._define_str("id_", id_)
        self.provider_id = self._define_str("provider_id", provider_id)
        self.variant = self._define_str("variant", variant)
        self._kwargs = kwargs


@JsonMap({})
class TokensCache8(BaseModel):
    """TokensCache8

    :param read: read
    :type read: float
    :param write: write
    :type write: float
    """

    def __init__(self, read: float, write: float, **kwargs):
        """TokensCache8

        :param read: read
        :type read: float
        :param write: write
        :type write: float
        """
        self.read = self._define_number("read", read)
        self.write = self._define_number("write", write)
        self._kwargs = kwargs


@JsonMap({})
class SessionInfoTokens(BaseModel):
    """SessionInfoTokens

    :param input: input
    :type input: float
    :param output: output
    :type output: float
    :param reasoning: reasoning
    :type reasoning: float
    :param cache: cache
    :type cache: TokensCache8
    """

    def __init__(
        self,
        input: float,
        output: float,
        reasoning: float,
        cache: TokensCache8,
        **kwargs
    ):
        """SessionInfoTokens

        :param input: input
        :type input: float
        :param output: output
        :type output: float
        :param reasoning: reasoning
        :type reasoning: float
        :param cache: cache
        :type cache: TokensCache8
        """
        self.input = self._define_number("input", input)
        self.output = self._define_number("output", output)
        self.reasoning = self._define_number("reasoning", reasoning)
        self.cache = self._define_object(cache, TokensCache8)
        self._kwargs = kwargs


@JsonMap({})
class SessionInfoTime(BaseModel):
    """SessionInfoTime

    :param created: created
    :type created: float
    :param updated: updated
    :type updated: float
    :param archived: archived, defaults to None
    :type archived: float, optional
    """

    def __init__(
        self, created: float, updated: float, archived: float = SENTINEL, **kwargs
    ):
        """SessionInfoTime

        :param created: created
        :type created: float
        :param updated: updated
        :type updated: float
        :param archived: archived, defaults to None
        :type archived: float, optional
        """
        self.created = self._define_number("created", created)
        self.updated = self._define_number("updated", updated)
        if archived is not SENTINEL:
            self.archived = self._define_number("archived", archived)
        self._kwargs = kwargs


@JsonMap(
    {
        "id_": "id",
        "parent_id": "parentID",
        "project_id": "projectID",
        "workspace_id": "workspaceID",
    }
)
class SessionInfo(BaseModel):
    """SessionInfo

    :param id_: id_
    :type id_: str
    :param parent_id: parent_id, defaults to None
    :type parent_id: str, optional
    :param project_id: project_id
    :type project_id: str
    :param workspace_id: workspace_id, defaults to None
    :type workspace_id: str, optional
    :param path: path, defaults to None
    :type path: str, optional
    :param agent: agent, defaults to None
    :type agent: str, optional
    :param model: model, defaults to None
    :type model: SessionInfoModel, optional
    :param cost: cost
    :type cost: float
    :param tokens: tokens
    :type tokens: SessionInfoTokens
    :param time: time
    :type time: SessionInfoTime
    :param title: title
    :type title: str
    """

    def __init__(
        self,
        id_: str,
        project_id: str,
        cost: float,
        tokens: SessionInfoTokens,
        time: SessionInfoTime,
        title: str,
        parent_id: str = SENTINEL,
        workspace_id: str = SENTINEL,
        path: str = SENTINEL,
        agent: str = SENTINEL,
        model: SessionInfoModel = SENTINEL,
        **kwargs
    ):
        """SessionInfo

        :param id_: id_
        :type id_: str
        :param parent_id: parent_id, defaults to None
        :type parent_id: str, optional
        :param project_id: project_id
        :type project_id: str
        :param workspace_id: workspace_id, defaults to None
        :type workspace_id: str, optional
        :param path: path, defaults to None
        :type path: str, optional
        :param agent: agent, defaults to None
        :type agent: str, optional
        :param model: model, defaults to None
        :type model: SessionInfoModel, optional
        :param cost: cost
        :type cost: float
        :param tokens: tokens
        :type tokens: SessionInfoTokens
        :param time: time
        :type time: SessionInfoTime
        :param title: title
        :type title: str
        """
        self.id_ = self._define_str("id_", id_, pattern="^ses")
        if parent_id is not SENTINEL:
            self.parent_id = self._define_str("parent_id", parent_id, pattern="^ses")
        self.project_id = self._define_str("project_id", project_id)
        if workspace_id is not SENTINEL:
            self.workspace_id = self._define_str(
                "workspace_id", workspace_id, pattern="^wrk"
            )
        if path is not SENTINEL:
            self.path = self._define_str("path", path)
        if agent is not SENTINEL:
            self.agent = self._define_str("agent", agent)
        if model is not SENTINEL:
            self.model = self._define_object(model, SessionInfoModel)
        self.cost = self._define_number("cost", cost)
        self.tokens = self._define_object(tokens, SessionInfoTokens)
        self.time = self._define_object(time, SessionInfoTime)
        self.title = self._define_str("title", title)
        self._kwargs = kwargs
