# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class SubtaskPartType(Enum):
    """An enumeration representing different categories.

    :cvar SUBTASK: "subtask"
    :vartype SUBTASK: str
    """

    SUBTASK = "subtask"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, SubtaskPartType._member_map_.values()))


@JsonMap({"provider_id": "providerID", "model_id": "modelID"})
class SubtaskPartModel(BaseModel):
    """SubtaskPartModel

    :param provider_id: provider_id
    :type provider_id: str
    :param model_id: model_id
    :type model_id: str
    """

    def __init__(self, provider_id: str, model_id: str, **kwargs):
        """SubtaskPartModel

        :param provider_id: provider_id
        :type provider_id: str
        :param model_id: model_id
        :type model_id: str
        """
        self.provider_id = self._define_str("provider_id", provider_id)
        self.model_id = self._define_str("model_id", model_id)
        self._kwargs = kwargs


@JsonMap(
    {"id_": "id", "session_id": "sessionID", "message_id": "messageID", "type_": "type"}
)
class SubtaskPart(BaseModel):
    """SubtaskPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: SubtaskPartType
    :param prompt: prompt
    :type prompt: str
    :param description: description
    :type description: str
    :param agent: agent
    :type agent: str
    :param model: model, defaults to None
    :type model: SubtaskPartModel, optional
    :param command: command, defaults to None
    :type command: str, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: SubtaskPartType,
        prompt: str,
        description: str,
        agent: str,
        model: SubtaskPartModel = SENTINEL,
        command: str = SENTINEL,
        **kwargs
    ):
        """SubtaskPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: SubtaskPartType
        :param prompt: prompt
        :type prompt: str
        :param description: description
        :type description: str
        :param agent: agent
        :type agent: str
        :param model: model, defaults to None
        :type model: SubtaskPartModel, optional
        :param command: command, defaults to None
        :type command: str, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, SubtaskPartType.list(), "type_")
        self.prompt = self._define_str("prompt", prompt)
        self.description = self._define_str("description", description)
        self.agent = self._define_str("agent", agent)
        if model is not SENTINEL:
            self.model = self._define_object(model, SubtaskPartModel)
        if command is not SENTINEL:
            self.command = self._define_str("command", command)
        self._kwargs = kwargs
