# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .file_part_source_text import FilePartSourceText
from .range import Range


class SymbolSourceType(Enum):
    """An enumeration representing different categories.

    :cvar SYMBOL: "symbol"
    :vartype SYMBOL: str
    """

    SYMBOL = "symbol"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, SymbolSourceType._member_map_.values()))


@JsonMap({"type_": "type"})
class SymbolSource(BaseModel):
    """SymbolSource

    :param text: text
    :type text: FilePartSourceText
    :param type_: type_
    :type type_: SymbolSourceType
    :param path: path
    :type path: str
    :param range: range
    :type range: Range
    :param name: name
    :type name: str
    :param kind: kind
    :type kind: int
    """

    def __init__(
        self,
        text: FilePartSourceText,
        type_: SymbolSourceType,
        path: str,
        range: Range,
        name: str,
        kind: int,
        **kwargs,
    ):
        """SymbolSource

        :param text: text
        :type text: FilePartSourceText
        :param type_: type_
        :type type_: SymbolSourceType
        :param path: path
        :type path: str
        :param range: range
        :type range: Range
        :param name: name
        :type name: str
        :param kind: kind
        :type kind: int
        """
        self.text = self._define_object(text, FilePartSourceText)
        self.type_ = self._enum_matching(type_, SymbolSourceType.list(), "type_")
        self.path = self._define_str("path", path)
        self.range = self._define_object(range, Range)
        self.name = self._define_str("name", name)
        self.kind = self._define_number("kind", kind, ge=0)
        self._kwargs = kwargs
