# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .session import Session


class SyncEventSessionDeletedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventSessionDeletedType._member_map_.values())
        )


class SyncEventSessionDeletedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONDELETED1: "session.deleted.1"
    :vartype SESSIONDELETED1: str
    """

    SESSIONDELETED1 = "session.deleted.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventSessionDeletedName._member_map_.values())
        )


class SyncEventSessionDeletedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionDeletedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class SyncEventSessionDeletedData(BaseModel):
    """SyncEventSessionDeletedData

    :param session_id: session_id
    :type session_id: str
    :param info: info
    :type info: Session
    """

    def __init__(self, session_id: str, info: Session, **kwargs):
        """SyncEventSessionDeletedData

        :param session_id: session_id
        :type session_id: str
        :param info: info
        :type info: Session
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.info = self._define_object(info, Session)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionDeleted(BaseModel):
    """SyncEventSessionDeleted

    :param type_: type_
    :type type_: SyncEventSessionDeletedType
    :param name: name
    :type name: SyncEventSessionDeletedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionDeletedAggregateId
    :param data: data
    :type data: SyncEventSessionDeletedData
    """

    def __init__(
        self,
        type_: SyncEventSessionDeletedType,
        name: SyncEventSessionDeletedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionDeletedAggregateId,
        data: SyncEventSessionDeletedData,
        **kwargs,
    ):
        """SyncEventSessionDeleted

        :param type_: type_
        :type type_: SyncEventSessionDeletedType
        :param name: name
        :type name: SyncEventSessionDeletedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionDeletedAggregateId
        :param data: data
        :type data: SyncEventSessionDeletedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionDeletedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionDeletedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id, SyncEventSessionDeletedAggregateId.list(), "aggregate_id"
        )
        self.data = self._define_object(data, SyncEventSessionDeletedData)
        self._kwargs = kwargs
