# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class SyncEventSessionNextTextEndedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextTextEndedType._member_map_.values(),
            )
        )


class SyncEventSessionNextTextEndedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTTEXTENDED1: "session.next.text.ended.1"
    :vartype SESSIONNEXTTEXTENDED1: str
    """

    SESSIONNEXTTEXTENDED1 = "session.next.text.ended.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextTextEndedName._member_map_.values(),
            )
        )


class SyncEventSessionNextTextEndedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextTextEndedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class SyncEventSessionNextTextEndedData(BaseModel):
    """SyncEventSessionNextTextEndedData

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param text: text
    :type text: str
    """

    def __init__(self, timestamp: float, session_id: str, text: str, **kwargs):
        """SyncEventSessionNextTextEndedData

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param text: text
        :type text: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.text = self._define_str("text", text)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionNextTextEnded(BaseModel):
    """SyncEventSessionNextTextEnded

    :param type_: type_
    :type type_: SyncEventSessionNextTextEndedType
    :param name: name
    :type name: SyncEventSessionNextTextEndedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionNextTextEndedAggregateId
    :param data: data
    :type data: SyncEventSessionNextTextEndedData
    """

    def __init__(
        self,
        type_: SyncEventSessionNextTextEndedType,
        name: SyncEventSessionNextTextEndedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionNextTextEndedAggregateId,
        data: SyncEventSessionNextTextEndedData,
        **kwargs
    ):
        """SyncEventSessionNextTextEnded

        :param type_: type_
        :type type_: SyncEventSessionNextTextEndedType
        :param name: name
        :type name: SyncEventSessionNextTextEndedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionNextTextEndedAggregateId
        :param data: data
        :type data: SyncEventSessionNextTextEndedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionNextTextEndedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionNextTextEndedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id,
            SyncEventSessionNextTextEndedAggregateId.list(),
            "aggregate_id",
        )
        self.data = self._define_object(data, SyncEventSessionNextTextEndedData)
        self._kwargs = kwargs
