# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"session_id": "sessionID"})
class SyncStealRequest(BaseModel):
    """SyncStealRequest

    :param session_id: session_id
    :type session_id: str
    """

    def __init__(self, session_id: str, **kwargs):
        """SyncStealRequest

        :param session_id: session_id
        :type session_id: str
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self._kwargs = kwargs
