# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class SyncEventSessionNextCompactionStartedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextCompactionStartedType._member_map_.values(),
            )
        )


class SyncEventSessionNextCompactionStartedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTCOMPACTIONSTARTED1: "session.next.compaction.started.1"
    :vartype SESSIONNEXTCOMPACTIONSTARTED1: str
    """

    SESSIONNEXTCOMPACTIONSTARTED1 = "session.next.compaction.started.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextCompactionStartedName._member_map_.values(),
            )
        )


class SyncEventSessionNextCompactionStartedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextCompactionStartedAggregateId._member_map_.values(),
            )
        )


class DataReason1(Enum):
    """An enumeration representing different categories.

    :cvar AUTO: "auto"
    :vartype AUTO: str
    :cvar MANUAL: "manual"
    :vartype MANUAL: str
    """

    AUTO = "auto"
    MANUAL = "manual"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, DataReason1._member_map_.values()))


@JsonMap({"session_id": "sessionID"})
class SyncEventSessionNextCompactionStartedData(BaseModel):
    """SyncEventSessionNextCompactionStartedData

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param reason: reason
    :type reason: DataReason1
    """

    def __init__(
        self, timestamp: float, session_id: str, reason: DataReason1, **kwargs
    ):
        """SyncEventSessionNextCompactionStartedData

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param reason: reason
        :type reason: DataReason1
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.reason = self._enum_matching(reason, DataReason1.list(), "reason")
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionNextCompactionStarted(BaseModel):
    """SyncEventSessionNextCompactionStarted

    :param type_: type_
    :type type_: SyncEventSessionNextCompactionStartedType
    :param name: name
    :type name: SyncEventSessionNextCompactionStartedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionNextCompactionStartedAggregateId
    :param data: data
    :type data: SyncEventSessionNextCompactionStartedData
    """

    def __init__(
        self,
        type_: SyncEventSessionNextCompactionStartedType,
        name: SyncEventSessionNextCompactionStartedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionNextCompactionStartedAggregateId,
        data: SyncEventSessionNextCompactionStartedData,
        **kwargs
    ):
        """SyncEventSessionNextCompactionStarted

        :param type_: type_
        :type type_: SyncEventSessionNextCompactionStartedType
        :param name: name
        :type name: SyncEventSessionNextCompactionStartedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionNextCompactionStartedAggregateId
        :param data: data
        :type data: SyncEventSessionNextCompactionStartedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionNextCompactionStartedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionNextCompactionStartedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id,
            SyncEventSessionNextCompactionStartedAggregateId.list(),
            "aggregate_id",
        )
        self.data = self._define_object(data, SyncEventSessionNextCompactionStartedData)
        self._kwargs = kwargs
