# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .session import Session


class SyncEventSessionCreatedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventSessionCreatedType._member_map_.values())
        )


class SyncEventSessionCreatedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONCREATED1: "session.created.1"
    :vartype SESSIONCREATED1: str
    """

    SESSIONCREATED1 = "session.created.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventSessionCreatedName._member_map_.values())
        )


class SyncEventSessionCreatedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionCreatedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class SyncEventSessionCreatedData(BaseModel):
    """SyncEventSessionCreatedData

    :param session_id: session_id
    :type session_id: str
    :param info: info
    :type info: Session
    """

    def __init__(self, session_id: str, info: Session, **kwargs):
        """SyncEventSessionCreatedData

        :param session_id: session_id
        :type session_id: str
        :param info: info
        :type info: Session
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.info = self._define_object(info, Session)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionCreated(BaseModel):
    """SyncEventSessionCreated

    :param type_: type_
    :type type_: SyncEventSessionCreatedType
    :param name: name
    :type name: SyncEventSessionCreatedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionCreatedAggregateId
    :param data: data
    :type data: SyncEventSessionCreatedData
    """

    def __init__(
        self,
        type_: SyncEventSessionCreatedType,
        name: SyncEventSessionCreatedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionCreatedAggregateId,
        data: SyncEventSessionCreatedData,
        **kwargs,
    ):
        """SyncEventSessionCreated

        :param type_: type_
        :type type_: SyncEventSessionCreatedType
        :param name: name
        :type name: SyncEventSessionCreatedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionCreatedAggregateId
        :param data: data
        :type data: SyncEventSessionCreatedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionCreatedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionCreatedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id, SyncEventSessionCreatedAggregateId.list(), "aggregate_id"
        )
        self.data = self._define_object(data, SyncEventSessionCreatedData)
        self._kwargs = kwargs
