# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .session_error_unknown import SessionErrorUnknown


class SyncEventSessionNextToolFailedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolFailedType._member_map_.values(),
            )
        )


class SyncEventSessionNextToolFailedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTTOOLFAILED1: "session.next.tool.failed.1"
    :vartype SESSIONNEXTTOOLFAILED1: str
    """

    SESSIONNEXTTOOLFAILED1 = "session.next.tool.failed.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolFailedName._member_map_.values(),
            )
        )


class SyncEventSessionNextToolFailedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolFailedAggregateId._member_map_.values(),
            )
        )


@JsonMap({})
class DataProvider3(BaseModel):
    """DataProvider3

    :param executed: executed
    :type executed: bool
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(self, executed: bool, metadata: dict = SENTINEL, **kwargs):
        """DataProvider3

        :param executed: executed
        :type executed: bool
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.executed = executed
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class SyncEventSessionNextToolFailedData(BaseModel):
    """SyncEventSessionNextToolFailedData

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param error: error
    :type error: SessionErrorUnknown
    :param provider: provider
    :type provider: DataProvider3
    """

    def __init__(
        self,
        timestamp: float,
        session_id: str,
        call_id: str,
        error: SessionErrorUnknown,
        provider: DataProvider3,
        **kwargs,
    ):
        """SyncEventSessionNextToolFailedData

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param error: error
        :type error: SessionErrorUnknown
        :param provider: provider
        :type provider: DataProvider3
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.error = self._define_object(error, SessionErrorUnknown)
        self.provider = self._define_object(provider, DataProvider3)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionNextToolFailed(BaseModel):
    """SyncEventSessionNextToolFailed

    :param type_: type_
    :type type_: SyncEventSessionNextToolFailedType
    :param name: name
    :type name: SyncEventSessionNextToolFailedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionNextToolFailedAggregateId
    :param data: data
    :type data: SyncEventSessionNextToolFailedData
    """

    def __init__(
        self,
        type_: SyncEventSessionNextToolFailedType,
        name: SyncEventSessionNextToolFailedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionNextToolFailedAggregateId,
        data: SyncEventSessionNextToolFailedData,
        **kwargs,
    ):
        """SyncEventSessionNextToolFailed

        :param type_: type_
        :type type_: SyncEventSessionNextToolFailedType
        :param name: name
        :type name: SyncEventSessionNextToolFailedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionNextToolFailedAggregateId
        :param data: data
        :type data: SyncEventSessionNextToolFailedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionNextToolFailedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionNextToolFailedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id,
            SyncEventSessionNextToolFailedAggregateId.list(),
            "aggregate_id",
        )
        self.data = self._define_object(data, SyncEventSessionNextToolFailedData)
        self._kwargs = kwargs
