# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class SyncEventSessionNextShellEndedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextShellEndedType._member_map_.values(),
            )
        )


class SyncEventSessionNextShellEndedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTSHELLENDED1: "session.next.shell.ended.1"
    :vartype SESSIONNEXTSHELLENDED1: str
    """

    SESSIONNEXTSHELLENDED1 = "session.next.shell.ended.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextShellEndedName._member_map_.values(),
            )
        )


class SyncEventSessionNextShellEndedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextShellEndedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class SyncEventSessionNextShellEndedData(BaseModel):
    """SyncEventSessionNextShellEndedData

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param output: output
    :type output: str
    """

    def __init__(
        self, timestamp: float, session_id: str, call_id: str, output: str, **kwargs
    ):
        """SyncEventSessionNextShellEndedData

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param output: output
        :type output: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.output = self._define_str("output", output)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionNextShellEnded(BaseModel):
    """SyncEventSessionNextShellEnded

    :param type_: type_
    :type type_: SyncEventSessionNextShellEndedType
    :param name: name
    :type name: SyncEventSessionNextShellEndedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionNextShellEndedAggregateId
    :param data: data
    :type data: SyncEventSessionNextShellEndedData
    """

    def __init__(
        self,
        type_: SyncEventSessionNextShellEndedType,
        name: SyncEventSessionNextShellEndedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionNextShellEndedAggregateId,
        data: SyncEventSessionNextShellEndedData,
        **kwargs
    ):
        """SyncEventSessionNextShellEnded

        :param type_: type_
        :type type_: SyncEventSessionNextShellEndedType
        :param name: name
        :type name: SyncEventSessionNextShellEndedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionNextShellEndedAggregateId
        :param data: data
        :type data: SyncEventSessionNextShellEndedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionNextShellEndedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionNextShellEndedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id,
            SyncEventSessionNextShellEndedAggregateId.list(),
            "aggregate_id",
        )
        self.data = self._define_object(data, SyncEventSessionNextShellEndedData)
        self._kwargs = kwargs
