# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .part import Part, PartGuard
from .text_part import TextPart
from .subtask_part import SubtaskPart
from .reasoning_part import ReasoningPart
from .file_part import FilePart
from .tool_part import ToolPart
from .step_start_part import StepStartPart
from .step_finish_part import StepFinishPart
from .snapshot_part import SnapshotPart
from .patch_part import PatchPart
from .agent_part import AgentPart
from .retry_part import RetryPart
from .compaction_part import CompactionPart


class SyncEventMessagePartUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, SyncEventMessagePartUpdatedType._member_map_.values()
            )
        )


class SyncEventMessagePartUpdatedName(Enum):
    """An enumeration representing different categories.

    :cvar MESSAGEPARTUPDATED1: "message.part.updated.1"
    :vartype MESSAGEPARTUPDATED1: str
    """

    MESSAGEPARTUPDATED1 = "message.part.updated.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, SyncEventMessagePartUpdatedName._member_map_.values()
            )
        )


class SyncEventMessagePartUpdatedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventMessagePartUpdatedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class SyncEventMessagePartUpdatedData(BaseModel):
    """SyncEventMessagePartUpdatedData

    :param session_id: session_id
    :type session_id: str
    :param part: part
    :type part: Part
    :param time: time
    :type time: int
    """

    def __init__(self, session_id: str, part: Part, time: int, **kwargs):
        """SyncEventMessagePartUpdatedData

        :param session_id: session_id
        :type session_id: str
        :param part: part
        :type part: Part
        :param time: time
        :type time: int
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.part = PartGuard.return_one_of(part)
        self.time = self._define_number("time", time, ge=0)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventMessagePartUpdated(BaseModel):
    """SyncEventMessagePartUpdated

    :param type_: type_
    :type type_: SyncEventMessagePartUpdatedType
    :param name: name
    :type name: SyncEventMessagePartUpdatedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventMessagePartUpdatedAggregateId
    :param data: data
    :type data: SyncEventMessagePartUpdatedData
    """

    def __init__(
        self,
        type_: SyncEventMessagePartUpdatedType,
        name: SyncEventMessagePartUpdatedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventMessagePartUpdatedAggregateId,
        data: SyncEventMessagePartUpdatedData,
        **kwargs,
    ):
        """SyncEventMessagePartUpdated

        :param type_: type_
        :type type_: SyncEventMessagePartUpdatedType
        :param name: name
        :type name: SyncEventMessagePartUpdatedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventMessagePartUpdatedAggregateId
        :param data: data
        :type data: SyncEventMessagePartUpdatedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventMessagePartUpdatedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventMessagePartUpdatedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id, SyncEventMessagePartUpdatedAggregateId.list(), "aggregate_id"
        )
        self.data = self._define_object(data, SyncEventMessagePartUpdatedData)
        self._kwargs = kwargs
