# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .message import Message, MessageGuard
from .user_message import UserMessage
from .assistant_message import AssistantMessage


class SyncEventMessageUpdatedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventMessageUpdatedType._member_map_.values())
        )


class SyncEventMessageUpdatedName(Enum):
    """An enumeration representing different categories.

    :cvar MESSAGEUPDATED1: "message.updated.1"
    :vartype MESSAGEUPDATED1: str
    """

    MESSAGEUPDATED1 = "message.updated.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, SyncEventMessageUpdatedName._member_map_.values())
        )


class SyncEventMessageUpdatedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventMessageUpdatedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID"})
class SyncEventMessageUpdatedData(BaseModel):
    """SyncEventMessageUpdatedData

    :param session_id: session_id
    :type session_id: str
    :param info: info
    :type info: Message
    """

    def __init__(self, session_id: str, info: Message, **kwargs):
        """SyncEventMessageUpdatedData

        :param session_id: session_id
        :type session_id: str
        :param info: info
        :type info: Message
        """
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.info = MessageGuard.return_one_of(info)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventMessageUpdated(BaseModel):
    """SyncEventMessageUpdated

    :param type_: type_
    :type type_: SyncEventMessageUpdatedType
    :param name: name
    :type name: SyncEventMessageUpdatedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventMessageUpdatedAggregateId
    :param data: data
    :type data: SyncEventMessageUpdatedData
    """

    def __init__(
        self,
        type_: SyncEventMessageUpdatedType,
        name: SyncEventMessageUpdatedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventMessageUpdatedAggregateId,
        data: SyncEventMessageUpdatedData,
        **kwargs,
    ):
        """SyncEventMessageUpdated

        :param type_: type_
        :type type_: SyncEventMessageUpdatedType
        :param name: name
        :type name: SyncEventMessageUpdatedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventMessageUpdatedAggregateId
        :param data: data
        :type data: SyncEventMessageUpdatedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventMessageUpdatedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventMessageUpdatedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id, SyncEventMessageUpdatedAggregateId.list(), "aggregate_id"
        )
        self.data = self._define_object(data, SyncEventMessageUpdatedData)
        self._kwargs = kwargs
