# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id", "aggregate_id": "aggregateID", "type_": "type"})
class Events(BaseModel):
    """Events

    :param id_: id_
    :type id_: str
    :param aggregate_id: aggregate_id
    :type aggregate_id: str
    :param seq: seq
    :type seq: int
    :param type_: type_
    :type type_: str
    :param data: data
    :type data: dict
    """

    def __init__(
        self, id_: str, aggregate_id: str, seq: int, type_: str, data: dict, **kwargs
    ):
        """Events

        :param id_: id_
        :type id_: str
        :param aggregate_id: aggregate_id
        :type aggregate_id: str
        :param seq: seq
        :type seq: int
        :param type_: type_
        :type type_: str
        :param data: data
        :type data: dict
        """
        self.id_ = self._define_str("id_", id_)
        self.aggregate_id = self._define_str("aggregate_id", aggregate_id)
        self.seq = self._define_number("seq", seq, ge=0)
        self.type_ = self._define_str("type_", type_)
        self.data = data
        self._kwargs = kwargs


@JsonMap({})
class SyncReplayRequest(BaseModel):
    """SyncReplayRequest

    :param directory: directory
    :type directory: str
    :param events: events
    :type events: List[Events]
    """

    def __init__(self, directory: str, events: List[Events], **kwargs):
        """SyncReplayRequest

        :param directory: directory
        :type directory: str
        :param events: events
        :type events: List[Events]
        """
        self.directory = self._define_str("directory", directory)
        self.events = self._define_list(events, Events)
        self._kwargs = kwargs
