# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class SyncEventSessionNextToolInputEndedType(Enum):
    """An enumeration representing different categories.

    :cvar SYNC: "sync"
    :vartype SYNC: str
    """

    SYNC = "sync"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolInputEndedType._member_map_.values(),
            )
        )


class SyncEventSessionNextToolInputEndedName(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONNEXTTOOLINPUTENDED1: "session.next.tool.input.ended.1"
    :vartype SESSIONNEXTTOOLINPUTENDED1: str
    """

    SESSIONNEXTTOOLINPUTENDED1 = "session.next.tool.input.ended.1"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolInputEndedName._member_map_.values(),
            )
        )


class SyncEventSessionNextToolInputEndedAggregateId(Enum):
    """An enumeration representing different categories.

    :cvar SESSIONID: "sessionID"
    :vartype SESSIONID: str
    """

    SESSIONID = "sessionID"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                SyncEventSessionNextToolInputEndedAggregateId._member_map_.values(),
            )
        )


@JsonMap({"session_id": "sessionID", "call_id": "callID"})
class SyncEventSessionNextToolInputEndedData(BaseModel):
    """SyncEventSessionNextToolInputEndedData

    :param timestamp: timestamp
    :type timestamp: float
    :param session_id: session_id
    :type session_id: str
    :param call_id: call_id
    :type call_id: str
    :param text: text
    :type text: str
    """

    def __init__(
        self, timestamp: float, session_id: str, call_id: str, text: str, **kwargs
    ):
        """SyncEventSessionNextToolInputEndedData

        :param timestamp: timestamp
        :type timestamp: float
        :param session_id: session_id
        :type session_id: str
        :param call_id: call_id
        :type call_id: str
        :param text: text
        :type text: str
        """
        self.timestamp = self._define_number("timestamp", timestamp)
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.call_id = self._define_str("call_id", call_id)
        self.text = self._define_str("text", text)
        self._kwargs = kwargs


@JsonMap({"type_": "type", "id_": "id", "aggregate_id": "aggregateID"})
class SyncEventSessionNextToolInputEnded(BaseModel):
    """SyncEventSessionNextToolInputEnded

    :param type_: type_
    :type type_: SyncEventSessionNextToolInputEndedType
    :param name: name
    :type name: SyncEventSessionNextToolInputEndedName
    :param id_: id_
    :type id_: str
    :param seq: seq
    :type seq: float
    :param aggregate_id: aggregate_id
    :type aggregate_id: SyncEventSessionNextToolInputEndedAggregateId
    :param data: data
    :type data: SyncEventSessionNextToolInputEndedData
    """

    def __init__(
        self,
        type_: SyncEventSessionNextToolInputEndedType,
        name: SyncEventSessionNextToolInputEndedName,
        id_: str,
        seq: float,
        aggregate_id: SyncEventSessionNextToolInputEndedAggregateId,
        data: SyncEventSessionNextToolInputEndedData,
        **kwargs
    ):
        """SyncEventSessionNextToolInputEnded

        :param type_: type_
        :type type_: SyncEventSessionNextToolInputEndedType
        :param name: name
        :type name: SyncEventSessionNextToolInputEndedName
        :param id_: id_
        :type id_: str
        :param seq: seq
        :type seq: float
        :param aggregate_id: aggregate_id
        :type aggregate_id: SyncEventSessionNextToolInputEndedAggregateId
        :param data: data
        :type data: SyncEventSessionNextToolInputEndedData
        """
        self.type_ = self._enum_matching(
            type_, SyncEventSessionNextToolInputEndedType.list(), "type_"
        )
        self.name = self._enum_matching(
            name, SyncEventSessionNextToolInputEndedName.list(), "name"
        )
        self.id_ = self._define_str("id_", id_)
        self.seq = self._define_number("seq", seq)
        self.aggregate_id = self._enum_matching(
            aggregate_id,
            SyncEventSessionNextToolInputEndedAggregateId.list(),
            "aggregate_id",
        )
        self.data = self._define_object(data, SyncEventSessionNextToolInputEndedData)
        self._kwargs = kwargs
