# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class TextPartType(Enum):
    """An enumeration representing different categories.

    :cvar TEXT: "text"
    :vartype TEXT: str
    """

    TEXT = "text"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, TextPartType._member_map_.values()))


@JsonMap({})
class TextPartTime(BaseModel):
    """TextPartTime

    :param start: start
    :type start: int
    :param end: end, defaults to None
    :type end: int, optional
    """

    def __init__(self, start: int, end: int = SENTINEL, **kwargs):
        """TextPartTime

        :param start: start
        :type start: int
        :param end: end, defaults to None
        :type end: int, optional
        """
        self.start = self._define_number("start", start, ge=0)
        if end is not SENTINEL:
            self.end = self._define_number("end", end, ge=0)
        self._kwargs = kwargs


@JsonMap(
    {"id_": "id", "session_id": "sessionID", "message_id": "messageID", "type_": "type"}
)
class TextPart(BaseModel):
    """TextPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: TextPartType
    :param text: text
    :type text: str
    :param synthetic: synthetic, defaults to None
    :type synthetic: bool, optional
    :param ignored: ignored, defaults to None
    :type ignored: bool, optional
    :param time: time, defaults to None
    :type time: TextPartTime, optional
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: TextPartType,
        text: str,
        synthetic: bool = SENTINEL,
        ignored: bool = SENTINEL,
        time: TextPartTime = SENTINEL,
        metadata: dict = SENTINEL,
        **kwargs
    ):
        """TextPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: TextPartType
        :param text: text
        :type text: str
        :param synthetic: synthetic, defaults to None
        :type synthetic: bool, optional
        :param ignored: ignored, defaults to None
        :type ignored: bool, optional
        :param time: time, defaults to None
        :type time: TextPartTime, optional
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, TextPartType.list(), "type_")
        self.text = self._define_str("text", text)
        if synthetic is not SENTINEL:
            self.synthetic = synthetic
        if ignored is not SENTINEL:
            self.ignored = ignored
        if time is not SENTINEL:
            self.time = self._define_object(time, TextPartTime)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs
