# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class ToolListItem(BaseModel):
    """ToolListItem

    :param id_: id_
    :type id_: str
    :param description: description
    :type description: str
    :param parameters: parameters
    :type parameters: any
    """

    def __init__(self, id_: str, description: str, parameters: any, **kwargs):
        """ToolListItem

        :param id_: id_
        :type id_: str
        :param description: description
        :type description: str
        :param parameters: parameters
        :type parameters: any
        """
        self.id_ = self._define_str("id_", id_)
        self.description = self._define_str("description", description)
        self.parameters = parameters
        self._kwargs = kwargs
