# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .tool_state import ToolState, ToolStateGuard
from .tool_state_pending import ToolStatePending
from .tool_state_running import ToolStateRunning
from .tool_state_completed import ToolStateCompleted
from .tool_state_error import ToolStateError


class ToolPartType(Enum):
    """An enumeration representing different categories.

    :cvar TOOL: "tool"
    :vartype TOOL: str
    """

    TOOL = "tool"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, ToolPartType._member_map_.values()))


@JsonMap(
    {
        "id_": "id",
        "session_id": "sessionID",
        "message_id": "messageID",
        "type_": "type",
        "call_id": "callID",
    }
)
class ToolPart(BaseModel):
    """ToolPart

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param message_id: message_id
    :type message_id: str
    :param type_: type_
    :type type_: ToolPartType
    :param call_id: call_id
    :type call_id: str
    :param tool: tool
    :type tool: str
    :param state: state
    :type state: ToolState
    :param metadata: metadata, defaults to None
    :type metadata: dict, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        message_id: str,
        type_: ToolPartType,
        call_id: str,
        tool: str,
        state: ToolState,
        metadata: dict = SENTINEL,
        **kwargs,
    ):
        """ToolPart

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param type_: type_
        :type type_: ToolPartType
        :param call_id: call_id
        :type call_id: str
        :param tool: tool
        :type tool: str
        :param state: state
        :type state: ToolState
        :param metadata: metadata, defaults to None
        :type metadata: dict, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^prt")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.message_id = self._define_str("message_id", message_id, pattern="^msg")
        self.type_ = self._enum_matching(type_, ToolPartType.list(), "type_")
        self.call_id = self._define_str("call_id", call_id)
        self.tool = self._define_str("tool", tool)
        self.state = ToolStateGuard.return_one_of(state)
        if metadata is not SENTINEL:
            self.metadata = metadata
        self._kwargs = kwargs
