# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class ToolStatePendingStatus(Enum):
    """An enumeration representing different categories.

    :cvar PENDING: "pending"
    :vartype PENDING: str
    """

    PENDING = "pending"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, ToolStatePendingStatus._member_map_.values())
        )


@JsonMap({})
class ToolStatePending(BaseModel):
    """ToolStatePending

    :param status: status
    :type status: ToolStatePendingStatus
    :param input: input
    :type input: dict
    :param raw: raw
    :type raw: str
    """

    def __init__(self, status: ToolStatePendingStatus, input: dict, raw: str, **kwargs):
        """ToolStatePending

        :param status: status
        :type status: ToolStatePendingStatus
        :param input: input
        :type input: dict
        :param raw: raw
        :type raw: str
        """
        self.status = self._enum_matching(
            status, ToolStatePendingStatus.list(), "status"
        )
        self.input = input
        self.raw = self._define_str("raw", raw)
        self._kwargs = kwargs
