# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class TuiShowToastRequestVariant(Enum):
    """An enumeration representing different categories.

    :cvar INFO: "info"
    :vartype INFO: str
    :cvar SUCCESS: "success"
    :vartype SUCCESS: str
    :cvar WARNING: "warning"
    :vartype WARNING: str
    :cvar ERROR: "error"
    :vartype ERROR: str
    """

    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, TuiShowToastRequestVariant._member_map_.values())
        )


@JsonMap({})
class TuiShowToastRequest(BaseModel):
    """TuiShowToastRequest

    :param title: title, defaults to None
    :type title: str, optional
    :param message: message
    :type message: str
    :param variant: variant
    :type variant: TuiShowToastRequestVariant
    :param duration: duration, defaults to None
    :type duration: int, optional
    """

    def __init__(
        self,
        message: str,
        variant: TuiShowToastRequestVariant,
        title: str = SENTINEL,
        duration: int = SENTINEL,
        **kwargs
    ):
        """TuiShowToastRequest

        :param title: title, defaults to None
        :type title: str, optional
        :param message: message
        :type message: str
        :param variant: variant
        :type variant: TuiShowToastRequestVariant
        :param duration: duration, defaults to None
        :type duration: int, optional
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        self.message = self._define_str("message", message)
        self.variant = self._enum_matching(
            variant, TuiShowToastRequestVariant.list(), "variant"
        )
        if duration is not SENTINEL:
            self.duration = self._define_number("duration", duration)
        self._kwargs = kwargs
