# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class TuiExecuteCommandRequest(BaseModel):
    """TuiExecuteCommandRequest

    :param command: command
    :type command: str
    """

    def __init__(self, command: str, **kwargs):
        """TuiExecuteCommandRequest

        :param command: command
        :type command: str
        """
        self.command = self._define_str("command", command)
        self._kwargs = kwargs
