# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


class EventTuiToastShowType2(Enum):
    """An enumeration representing different categories.

    :cvar TUITOASTSHOW: "tui.toast.show"
    :vartype TUITOASTSHOW: str
    """

    TUITOASTSHOW = "tui.toast.show"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, EventTuiToastShowType2._member_map_.values())
        )


class PropertiesVariant3(Enum):
    """An enumeration representing different categories.

    :cvar INFO: "info"
    :vartype INFO: str
    :cvar SUCCESS: "success"
    :vartype SUCCESS: str
    :cvar WARNING: "warning"
    :vartype WARNING: str
    :cvar ERROR: "error"
    :vartype ERROR: str
    """

    INFO = "info"
    SUCCESS = "success"
    WARNING = "warning"
    ERROR = "error"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, PropertiesVariant3._member_map_.values()))


@JsonMap({})
class EventTuiToastShowProperties2(BaseModel):
    """EventTuiToastShowProperties2

    :param title: title, defaults to None
    :type title: str, optional
    :param message: message
    :type message: str
    :param variant: variant
    :type variant: PropertiesVariant3
    :param duration: duration, defaults to None
    :type duration: int, optional
    """

    def __init__(
        self,
        message: str,
        variant: PropertiesVariant3,
        title: str = SENTINEL,
        duration: int = SENTINEL,
        **kwargs
    ):
        """EventTuiToastShowProperties2

        :param title: title, defaults to None
        :type title: str, optional
        :param message: message
        :type message: str
        :param variant: variant
        :type variant: PropertiesVariant3
        :param duration: duration, defaults to None
        :type duration: int, optional
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        self.message = self._define_str("message", message)
        self.variant = self._enum_matching(
            variant, PropertiesVariant3.list(), "variant"
        )
        if duration is not SENTINEL:
            self.duration = self._define_number("duration", duration)
        self._kwargs = kwargs


@JsonMap({"type_": "type"})
class TuiPublishRequest3(BaseModel):
    """TuiPublishRequest3

    :param type_: type_
    :type type_: EventTuiToastShowType2
    :param properties: properties
    :type properties: EventTuiToastShowProperties2
    """

    def __init__(
        self,
        type_: EventTuiToastShowType2,
        properties: EventTuiToastShowProperties2,
        **kwargs
    ):
        """TuiPublishRequest3

        :param type_: type_
        :type type_: EventTuiToastShowType2
        :param properties: properties
        :type properties: EventTuiToastShowProperties2
        """
        self.type_ = self._enum_matching(type_, EventTuiToastShowType2.list(), "type_")
        self.properties = self._define_object(properties, EventTuiToastShowProperties2)
        self._kwargs = kwargs
