# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class TuiControlNextOkResponse(BaseModel):
    """Next TUI request

    :param path: path
    :type path: str
    :param body: body
    :type body: any
    """

    def __init__(self, path: str, body: any, **kwargs):
        """Next TUI request

        :param path: path
        :type path: str
        :param body: body
        :type body: any
        """
        self.path = self._define_str("path", path)
        self.body = body
        self._kwargs = kwargs
