# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class TuiAppendPromptRequest(BaseModel):
    """TuiAppendPromptRequest

    :param text: text
    :type text: str
    """

    def __init__(self, text: str, **kwargs):
        """TuiAppendPromptRequest

        :param text: text
        :type text: str
        """
        self.text = self._define_str("text", text)
        self._kwargs = kwargs
