# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from enum import Enum
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .output_format import OutputFormat, OutputFormatGuard
from .output_format_text import OutputFormatText
from .output_format_json_schema import OutputFormatJsonSchema
from .snapshot_file_diff import SnapshotFileDiff


class UserMessageRole(Enum):
    """An enumeration representing different categories.

    :cvar USER: "user"
    :vartype USER: str
    """

    USER = "user"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, UserMessageRole._member_map_.values()))


@JsonMap({})
class UserMessageTime(BaseModel):
    """UserMessageTime

    :param created: created
    :type created: int
    """

    def __init__(self, created: int, **kwargs):
        """UserMessageTime

        :param created: created
        :type created: int
        """
        self.created = self._define_number("created", created, ge=0)
        self._kwargs = kwargs


@JsonMap({})
class UserMessageSummary(BaseModel):
    """UserMessageSummary

    :param title: title, defaults to None
    :type title: str, optional
    :param body: body, defaults to None
    :type body: str, optional
    :param diffs: diffs
    :type diffs: List[SnapshotFileDiff]
    """

    def __init__(
        self,
        diffs: List[SnapshotFileDiff],
        title: str = SENTINEL,
        body: str = SENTINEL,
        **kwargs,
    ):
        """UserMessageSummary

        :param title: title, defaults to None
        :type title: str, optional
        :param body: body, defaults to None
        :type body: str, optional
        :param diffs: diffs
        :type diffs: List[SnapshotFileDiff]
        """
        if title is not SENTINEL:
            self.title = self._define_str("title", title)
        if body is not SENTINEL:
            self.body = self._define_str("body", body)
        self.diffs = self._define_list(diffs, SnapshotFileDiff)
        self._kwargs = kwargs


@JsonMap({"provider_id": "providerID", "model_id": "modelID"})
class UserMessageModel(BaseModel):
    """UserMessageModel

    :param provider_id: provider_id
    :type provider_id: str
    :param model_id: model_id
    :type model_id: str
    :param variant: variant, defaults to None
    :type variant: str, optional
    """

    def __init__(
        self, provider_id: str, model_id: str, variant: str = SENTINEL, **kwargs
    ):
        """UserMessageModel

        :param provider_id: provider_id
        :type provider_id: str
        :param model_id: model_id
        :type model_id: str
        :param variant: variant, defaults to None
        :type variant: str, optional
        """
        self.provider_id = self._define_str("provider_id", provider_id)
        self.model_id = self._define_str("model_id", model_id)
        if variant is not SENTINEL:
            self.variant = self._define_str("variant", variant)
        self._kwargs = kwargs


@JsonMap({"id_": "id", "session_id": "sessionID"})
class UserMessage(BaseModel):
    """UserMessage

    :param id_: id_
    :type id_: str
    :param session_id: session_id
    :type session_id: str
    :param role: role
    :type role: UserMessageRole
    :param time: time
    :type time: UserMessageTime
    :param format: format, defaults to None
    :type format: OutputFormat, optional
    :param summary: summary, defaults to None
    :type summary: UserMessageSummary, optional
    :param agent: agent
    :type agent: str
    :param model: model
    :type model: UserMessageModel
    :param system: system, defaults to None
    :type system: str, optional
    :param tools: tools, defaults to None
    :type tools: dict, optional
    """

    def __init__(
        self,
        id_: str,
        session_id: str,
        role: UserMessageRole,
        time: UserMessageTime,
        agent: str,
        model: UserMessageModel,
        format: OutputFormat = SENTINEL,
        summary: UserMessageSummary = SENTINEL,
        system: str = SENTINEL,
        tools: dict = SENTINEL,
        **kwargs,
    ):
        """UserMessage

        :param id_: id_
        :type id_: str
        :param session_id: session_id
        :type session_id: str
        :param role: role
        :type role: UserMessageRole
        :param time: time
        :type time: UserMessageTime
        :param format: format, defaults to None
        :type format: OutputFormat, optional
        :param summary: summary, defaults to None
        :type summary: UserMessageSummary, optional
        :param agent: agent
        :type agent: str
        :param model: model
        :type model: UserMessageModel
        :param system: system, defaults to None
        :type system: str, optional
        :param tools: tools, defaults to None
        :type tools: dict, optional
        """
        self.id_ = self._define_str("id_", id_, pattern="^msg")
        self.session_id = self._define_str("session_id", session_id, pattern="^ses")
        self.role = self._enum_matching(role, UserMessageRole.list(), "role")
        self.time = self._define_object(time, UserMessageTime)
        if format is not SENTINEL:
            self.format = OutputFormatGuard.return_one_of(format)
        if summary is not SENTINEL:
            self.summary = self._define_object(summary, UserMessageSummary)
        self.agent = self._define_str("agent", agent)
        self.model = self._define_object(model, UserMessageModel)
        if system is not SENTINEL:
            self.system = self._define_str("system", system)
        if tools is not SENTINEL:
            self.tools = tools
        self._kwargs = kwargs
