# This file was generated by liblab | https://liblab.com/

from enum import Enum
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel


class Roots2_3(Enum):
    """An enumeration representing different categories.

    :cvar TRUE: "true"
    :vartype TRUE: str
    :cvar FALSE: "false"
    :vartype FALSE: str
    """

    TRUE = "true"
    FALSE = "false"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Roots2_3._member_map_.values()))


class V2SessionListRootsGuard(OneOfBaseModel):
    class_list = {"bool": bool, "Roots2_3Enum": str}


V2SessionListRoots = Union[bool, str]
