# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .session_info import SessionInfo


@JsonMap({})
class V2SessionsResponseCursor(BaseModel):
    """V2SessionsResponseCursor

    :param previous: previous, defaults to None
    :type previous: str, optional
    :param next: next, defaults to None
    :type next: str, optional
    """

    def __init__(self, previous: str = SENTINEL, next: str = SENTINEL, **kwargs):
        """V2SessionsResponseCursor

        :param previous: previous, defaults to None
        :type previous: str, optional
        :param next: next, defaults to None
        :type next: str, optional
        """
        if previous is not SENTINEL:
            self.previous = self._define_str("previous", previous)
        if next is not SENTINEL:
            self.next = self._define_str("next", next)
        self._kwargs = kwargs


@JsonMap({})
class V2SessionsResponse(BaseModel):
    """V2SessionsResponse

    :param items: items
    :type items: List[SessionInfo]
    :param cursor: cursor
    :type cursor: V2SessionsResponseCursor
    """

    def __init__(
        self, items: List[SessionInfo], cursor: V2SessionsResponseCursor, **kwargs
    ):
        """V2SessionsResponse

        :param items: items
        :type items: List[SessionInfo]
        :param cursor: cursor
        :type cursor: V2SessionsResponseCursor
        """
        self.items = self._define_list(items, SessionInfo)
        self.cursor = self._define_object(cursor, V2SessionsResponseCursor)
        self._kwargs = kwargs
