# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class VcsApplyOkResponse(BaseModel):
    """VCS patch applied

    :param applied: applied
    :type applied: bool
    """

    def __init__(self, applied: bool, **kwargs):
        """VCS patch applied

        :param applied: applied
        :type applied: bool
        """
        self.applied = applied
        self._kwargs = kwargs
