# This file was generated by liblab | https://liblab.com/

from enum import Enum


class VcsDiffMode(Enum):
    """An enumeration representing different categories.

    :cvar GIT: "git"
    :vartype GIT: str
    :cvar BRANCH: "branch"
    :vartype BRANCH: str
    """

    GIT = "git"
    BRANCH = "branch"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, VcsDiffMode._member_map_.values()))
