# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class VcsApplyRequest(BaseModel):
    """VcsApplyRequest

    :param patch: patch
    :type patch: str
    """

    def __init__(self, patch: str, **kwargs):
        """VcsApplyRequest

        :param patch: patch
        :type patch: str
        """
        self.patch = self._define_str("patch", patch)
        self._kwargs = kwargs
