# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class WorktreeRemoveInput(BaseModel):
    """WorktreeRemoveInput

    :param directory: directory
    :type directory: str
    """

    def __init__(self, directory: str, **kwargs):
        """WorktreeRemoveInput

        :param directory: directory
        :type directory: str
        """
        self.directory = self._define_str("directory", directory)
        self._kwargs = kwargs
