# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.base_model import BaseModel


class WorktreeErrorName(Enum):
    """An enumeration representing different categories.

    :cvar WORKTREENOTGITERROR: "WorktreeNotGitError"
    :vartype WORKTREENOTGITERROR: str
    :cvar WORKTREENAMEGENERATIONFAILEDERROR: "WorktreeNameGenerationFailedError"
    :vartype WORKTREENAMEGENERATIONFAILEDERROR: str
    :cvar WORKTREECREATEFAILEDERROR: "WorktreeCreateFailedError"
    :vartype WORKTREECREATEFAILEDERROR: str
    :cvar WORKTREESTARTCOMMANDFAILEDERROR: "WorktreeStartCommandFailedError"
    :vartype WORKTREESTARTCOMMANDFAILEDERROR: str
    :cvar WORKTREEREMOVEFAILEDERROR: "WorktreeRemoveFailedError"
    :vartype WORKTREEREMOVEFAILEDERROR: str
    :cvar WORKTREERESETFAILEDERROR: "WorktreeResetFailedError"
    :vartype WORKTREERESETFAILEDERROR: str
    :cvar WORKTREELISTFAILEDERROR: "WorktreeListFailedError"
    :vartype WORKTREELISTFAILEDERROR: str
    """

    WORKTREENOTGITERROR = "WorktreeNotGitError"
    WORKTREENAMEGENERATIONFAILEDERROR = "WorktreeNameGenerationFailedError"
    WORKTREECREATEFAILEDERROR = "WorktreeCreateFailedError"
    WORKTREESTARTCOMMANDFAILEDERROR = "WorktreeStartCommandFailedError"
    WORKTREEREMOVEFAILEDERROR = "WorktreeRemoveFailedError"
    WORKTREERESETFAILEDERROR = "WorktreeResetFailedError"
    WORKTREELISTFAILEDERROR = "WorktreeListFailedError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, WorktreeErrorName._member_map_.values()))


@JsonMap({})
class WorktreeErrorData(BaseModel):
    """WorktreeErrorData

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """WorktreeErrorData

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({})
class WorktreeError(ApiError):
    """WorktreeError

    :param name: name
    :type name: WorktreeErrorName
    :param data: data
    :type data: WorktreeErrorData
    """

    def __init__(self, name: WorktreeErrorName, data: WorktreeErrorData, **kwargs):
        """WorktreeError

        :param name: name
        :type name: WorktreeErrorName
        :param data: data
        :type data: WorktreeErrorData
        """
        self.name = self._enum_matching(name, WorktreeErrorName.list(), "name")
        self.data = self._define_object(data, WorktreeErrorData)
        self._kwargs = kwargs
