# This file was generated by liblab | https://liblab.com/

from enum import Enum
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class WorkspaceWarpErrorName(Enum):
    """An enumeration representing different categories.

    :cvar WORKSPACEWARPERROR: "WorkspaceWarpError"
    :vartype WORKSPACEWARPERROR: str
    """

    WORKSPACEWARPERROR = "WorkspaceWarpError"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, WorkspaceWarpErrorName._member_map_.values())
        )


@JsonMap({})
class WorkspaceWarpErrorData(BaseModel):
    """WorkspaceWarpErrorData

    :param message: message
    :type message: str
    """

    def __init__(self, message: str, **kwargs):
        """WorkspaceWarpErrorData

        :param message: message
        :type message: str
        """
        self.message = self._define_str("message", message)
        self._kwargs = kwargs


@JsonMap({})
class WorkspaceWarpError(BaseModel):
    """WorkspaceWarpError

    :param name: name
    :type name: WorkspaceWarpErrorName
    :param data: data
    :type data: WorkspaceWarpErrorData
    """

    def __init__(
        self, name: WorkspaceWarpErrorName, data: WorkspaceWarpErrorData, **kwargs
    ):
        """WorkspaceWarpError

        :param name: name
        :type name: WorkspaceWarpErrorName
        :param data: data
        :type data: WorkspaceWarpErrorData
        """
        self.name = self._enum_matching(name, WorkspaceWarpErrorName.list(), "name")
        self.data = self._define_object(data, WorkspaceWarpErrorData)
        self._kwargs = kwargs
