# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models import BadRequestError, Config, ConfigProvidersOkResponse


class ConfigService(BaseService):
    """
    Service class for ConfigService operations.
    Provides methods to interact with ConfigService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def config_get(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Config]:
        """Retrieve the current OpenCode configuration settings and preferences.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Config
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/config",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Config._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def config_update(
        self,
        request_body: Config = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Config]:
        """Update OpenCode configuration settings and preferences.

        :param request_body: The request body., defaults to None
        :type request_body: Config, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Config
        """

        Validator(Config).is_optional().validate(request_body)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/config",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("PATCH")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Config._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def config_providers(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[ConfigProvidersOkResponse]:
        """Get a list of all configured AI providers and their default models.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: ConfigProvidersOkResponse
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/config/providers",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=ConfigProvidersOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
