# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models import AppLogRequest, Auth, BadRequestError


class ControlService(BaseService):
    """
    Service class for ControlService operations.
    Provides methods to interact with ControlService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def auth_set(
        self, provider_id: str, request_body: Auth = None
    ) -> OpencodeResponse[bool]:
        """Set authentication credentials

        :param request_body: The request body., defaults to None
        :type request_body: Auth, optional
        :param provider_id: provider_id
        :type provider_id: str
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(Auth).is_optional().validate(request_body)
        Validator(str).validate(provider_id)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/auth/{{providerID}}",
                [self.get_access_token()],
            )
            .add_path("providerID", provider_id)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("PUT")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def auth_remove(self, provider_id: str) -> OpencodeResponse[bool]:
        """Remove authentication credentials

        :param provider_id: provider_id
        :type provider_id: str
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).validate(provider_id)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/auth/{{providerID}}",
                [self.get_access_token()],
            )
            .add_path("providerID", provider_id)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def app_log(
        self,
        request_body: AppLogRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Write a log entry to the server logs with specified level and metadata.

        :param request_body: The request body., defaults to None
        :type request_body: AppLogRequest, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(AppLogRequest).is_optional().validate(request_body)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/log",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
