# This file was generated by liblab | https://liblab.com/

from typing import Generator
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models.event import EventGuard
from ..models import Event


class EventService(BaseService):
    """
    Service class for EventService operations.
    Provides methods to interact with EventService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def event_subscribe(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> Generator[Event, None, None]:
        """Get events

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Generator[Event, None, None]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/event",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        for response, status, _ in self.stream_request(serialized_request):
            yield EventGuard.return_one_of(response)
