# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models import (
    Dirs,
    File,
    FileContent,
    FileNode,
    FindFilesType,
    FindTextOkResponse,
    Symbol,
)


class FileService(BaseService):
    """
    Service class for FileService operations.
    Provides methods to interact with FileService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def find_text(
        self, pattern: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[FindTextOkResponse]]:
        """Search for text patterns across files in the project using ripgrep.

        :param pattern: pattern
        :type pattern: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[FindTextOkResponse]
        """

        Validator(str).validate(pattern)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/find",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("pattern", pattern)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[FindTextOkResponse._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def find_files(
        self,
        query: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        dirs: Dirs = SENTINEL,
        type_: FindFilesType = SENTINEL,
        limit: int = SENTINEL,
    ) -> OpencodeResponse[List[str]]:
        """Search for files or directories by name or pattern in the project directory.

        :param query: query
        :type query: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        :param dirs: dirs, defaults to None
        :type dirs: Dirs, optional
        :param type_: type_, defaults to None
        :type type_: FindFilesType, optional
        :param limit: limit, defaults to None
        :type limit: int, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[str]
        """

        Validator(str).validate(query)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)
        Validator(Dirs).is_optional().validate(dirs)
        Validator(FindFilesType).is_optional().validate(type_)
        Validator(int).is_optional().min(1).max(200).validate(limit)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/find/file",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("query", query)
            .add_query("dirs", dirs)
            .add_query("type", type_)
            .add_query("limit", limit)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def find_symbols(
        self, query: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[Symbol]]:
        """Search for workspace symbols like functions, classes, and variables using LSP.

        :param query: query
        :type query: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[Symbol]
        """

        Validator(str).validate(query)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/find/symbol",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("query", query)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[Symbol._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def file_list(
        self, path: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[FileNode]]:
        """List files and directories in a specified path.

        :param path: path
        :type path: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[FileNode]
        """

        Validator(str).validate(path)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/file",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("path", path)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[FileNode._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def file_read(
        self, path: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[FileContent]:
        """Read the content of a specified file.

        :param path: path
        :type path: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: FileContent
        """

        Validator(str).validate(path)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/file/content",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("path", path)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=FileContent._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def file_status(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[File]]:
        """Get the git status of all files in the project.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[File]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/file/status",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[File._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
