# This file was generated by liblab | https://liblab.com/

from typing import Generator, Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.cast_models import cast_models
from ..models.global_upgrade_ok_response import GlobalUpgradeOkResponseGuard
from ..models import (
    BadRequestError,
    Config,
    GlobalEvent,
    GlobalHealthOkResponse,
    GlobalUpgradeOkResponse,
    GlobalUpgradeRequest,
)


class GlobalService(BaseService):
    """
    Service class for GlobalService operations.
    Provides methods to interact with GlobalService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def global_health(self) -> OpencodeResponse[GlobalHealthOkResponse]:
        """Get health information about the OpenCode server.

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: GlobalHealthOkResponse
        """

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/health",
                [self.get_access_token()],
            )
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=GlobalHealthOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def global_event(self) -> Generator[GlobalEvent, None, None]:
        """Subscribe to global events from the OpenCode system using server-sent events.

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Generator[GlobalEvent, None, None]
        """

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/event",
                [self.get_access_token()],
            )
            .serialize()
            .set_method("GET")
        )

        for response, status, _ in self.stream_request(serialized_request):
            yield GlobalEvent._unmap(response)

    @cast_models
    def global_config_get(self) -> OpencodeResponse[Config]:
        """Retrieve the current global OpenCode configuration settings and preferences.

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Config
        """

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/config",
                [self.get_access_token()],
            )
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Config._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def global_config_update(
        self, request_body: Config = None
    ) -> OpencodeResponse[Config]:
        """Update global OpenCode configuration settings and preferences.

        :param request_body: The request body., defaults to None
        :type request_body: Config, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Config
        """

        Validator(Config).is_optional().validate(request_body)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/config",
                [self.get_access_token()],
            )
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("PATCH")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Config._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def global_dispose(self) -> OpencodeResponse[bool]:
        """Clean up and dispose all OpenCode instances, releasing all resources.

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/dispose",
                [self.get_access_token()],
            )
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def global_upgrade(
        self, request_body: GlobalUpgradeRequest = None
    ) -> OpencodeResponse[GlobalUpgradeOkResponse]:
        """Upgrade opencode to the specified version or latest if not specified.

        :param request_body: The request body., defaults to None
        :type request_body: GlobalUpgradeRequest, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: GlobalUpgradeOkResponse
        """

        Validator(GlobalUpgradeRequest).is_optional().validate(request_body)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/global/upgrade",
                [self.get_access_token()],
            )
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=GlobalUpgradeOkResponseGuard.return_one_of(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
