# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models.mcp_status import McpStatusGuard
from ..models import (
    BadRequestError,
    McpAddRequest,
    McpAuthCallbackRequest,
    McpAuthRemoveOkResponse,
    McpAuthStartOkResponse,
    McpStatus,
    McpUnsupportedOAuthError,
    NotFoundError,
)


class McpService(BaseService):
    """
    Service class for McpService operations.
    Provides methods to interact with McpService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def mcp_status(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[dict]:
        """Get the status of all Model Context Protocol (MCP) servers.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: dict
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_add(
        self,
        request_body: McpAddRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[dict]:
        """Dynamically add a new Model Context Protocol (MCP) server to the system.

        :param request_body: The request body., defaults to None
        :type request_body: McpAddRequest, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: dict
        """

        Validator(McpAddRequest).is_optional().validate(request_body)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_auth_start(
        self, name: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[McpAuthStartOkResponse]:
        """Start OAuth authentication flow for a Model Context Protocol (MCP) server.

        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: McpAuthStartOkResponse
        """

        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/auth",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, McpUnsupportedOAuthError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=McpAuthStartOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_auth_remove(
        self, name: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[McpAuthRemoveOkResponse]:
        """Remove OAuth credentials for an MCP server.

        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: McpAuthRemoveOkResponse
        """

        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/auth",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=McpAuthRemoveOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_auth_callback(
        self,
        name: str,
        request_body: McpAuthCallbackRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[McpStatus]:
        """Complete OAuth authentication for a Model Context Protocol (MCP) server using the authorization code.

        :param request_body: The request body., defaults to None
        :type request_body: McpAuthCallbackRequest, optional
        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: McpStatus
        """

        Validator(McpAuthCallbackRequest).is_optional().validate(request_body)
        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/auth/callback",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=McpStatusGuard.return_one_of(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_auth_authenticate(
        self, name: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[McpStatus]:
        """Start OAuth flow and wait for callback (opens browser).

        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: McpStatus
        """

        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/auth/authenticate",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, McpUnsupportedOAuthError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=McpStatusGuard.return_one_of(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_connect(
        self, name: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[bool]:
        """Connect an MCP server.

        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/connect",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def mcp_disconnect(
        self, name: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[bool]:
        """Disconnect an MCP server.

        :param name: name
        :type name: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).validate(name)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/mcp/{{name}}/disconnect",
                [self.get_access_token()],
            )
            .add_path("name", name)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
