# This file was generated by liblab | https://liblab.com/

from typing import List, Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models.part import PartGuard
from ..models import (
    BadRequestError,
    EffectHttpApiErrorInternalServerError,
    NotFoundError,
    Part,
    PermissionRespondRequest,
    Scope,
    Session,
    SessionCommandOkResponse,
    SessionCommandRequest,
    SessionCreateRequest,
    SessionForkRequest,
    SessionInitRequest,
    SessionListRoots,
    SessionMessageOkResponse,
    SessionMessagesOkResponse,
    SessionPromptAsyncRequest,
    SessionPromptOkResponse,
    SessionPromptRequest,
    SessionRevertRequest,
    SessionShellOkResponse,
    SessionShellRequest,
    SessionSummarizeRequest,
    SessionUpdateRequest,
    SnapshotFileDiff,
    Todo,
)


class SessionService(BaseService):
    """
    Service class for SessionService operations.
    Provides methods to interact with SessionService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def session_list(
        self,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        scope: Scope = SENTINEL,
        path: str = SENTINEL,
        roots: SessionListRoots = SENTINEL,
        start: float = SENTINEL,
        search: str = SENTINEL,
        limit: float = SENTINEL,
    ) -> OpencodeResponse[List[Session]]:
        """Get a list of all OpenCode sessions, sorted by most recently updated.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        :param scope: scope, defaults to None
        :type scope: Scope, optional
        :param path: path, defaults to None
        :type path: str, optional
        :param roots: roots, defaults to None
        :type roots: SessionListRoots, optional
        :param start: start, defaults to None
        :type start: float, optional
        :param search: search, defaults to None
        :type search: str, optional
        :param limit: limit, defaults to None
        :type limit: float, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[Session]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)
        Validator(Scope).is_optional().validate(scope)
        Validator(str).is_optional().validate(path)
        Validator(SessionListRoots).is_optional().validate(roots)
        Validator(float).is_optional().validate(start)
        Validator(str).is_optional().validate(search)
        Validator(float).is_optional().validate(limit)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("scope", scope)
            .add_query("path", path)
            .add_query("roots", roots)
            .add_query("start", start)
            .add_query("search", search)
            .add_query("limit", limit)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[Session._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_create(
        self,
        request_body: SessionCreateRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Session]:
        """Create a new OpenCode session for interacting with AI assistants and managing conversations.

        :param request_body: The request body., defaults to None
        :type request_body: SessionCreateRequest, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(SessionCreateRequest).is_optional().validate(request_body)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_status(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[dict]:
        """Retrieve the current status of all sessions, including active, idle, and completed states.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: dict
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/status",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_get(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Session]:
        """Retrieve detailed information about a specific OpenCode session.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_update(
        self,
        session_id: str,
        request_body: SessionUpdateRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Session]:
        """Update properties of an existing session, such as title or other metadata.

        :param request_body: The request body., defaults to None
        :type request_body: SessionUpdateRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(SessionUpdateRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("PATCH")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_delete(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[bool]:
        """Delete a session and permanently remove all associated data, including messages and history.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_children(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[Session]]:
        """Retrieve all child sessions that were forked from the specified parent session.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[Session]
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/children",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[Session._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_todo(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[Todo]]:
        """Retrieve the todo list associated with a specific session, showing tasks and action items.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[Todo]
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/todo",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[Todo._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_diff(
        self,
        session_id: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        message_id: str = SENTINEL,
    ) -> OpencodeResponse[List[SnapshotFileDiff]]:
        """Get the file changes (diff) that resulted from a specific user message in the session.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        :param message_id: message_id, defaults to None
        :type message_id: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[SnapshotFileDiff]
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)
        Validator(str).is_optional().pattern("^msg").validate(message_id)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/diff",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("messageID", message_id)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[SnapshotFileDiff._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_messages(
        self,
        session_id: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        limit: int = SENTINEL,
        before: str = SENTINEL,
    ) -> OpencodeResponse[List[SessionMessagesOkResponse]]:
        """Retrieve all messages in a session, including user prompts and AI responses.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        :param limit: limit, defaults to None
        :type limit: int, optional
        :param before: before, defaults to None
        :type before: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[SessionMessagesOkResponse]
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)
        Validator(int).is_optional().min(0).max(9007199254740991).validate(limit)
        Validator(str).is_optional().validate(before)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("limit", limit)
            .add_query("before", before)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[SessionMessagesOkResponse._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_prompt(
        self,
        session_id: str,
        request_body: SessionPromptRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[SessionPromptOkResponse]:
        """Create and send a new message to a session, streaming the AI response.

        :param request_body: The request body., defaults to None
        :type request_body: SessionPromptRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: SessionPromptOkResponse
        """

        Validator(SessionPromptRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=SessionPromptOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_message(
        self,
        session_id: str,
        message_id: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[SessionMessageOkResponse]:
        """Retrieve a specific message from a session by its message ID.

        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: SessionMessageOkResponse
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).pattern("^msg").validate(message_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message/{{messageID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_path("messageID", message_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=SessionMessageOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_delete_message(
        self,
        session_id: str,
        message_id: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Permanently delete a specific message and all of its parts from a session without reverting file changes.

        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).pattern("^msg").validate(message_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message/{{messageID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_path("messageID", message_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_fork(
        self,
        session_id: str,
        request_body: SessionForkRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Session]:
        """Create a new session by forking an existing session at a specific message point.

        :param request_body: The request body., defaults to None
        :type request_body: SessionForkRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(SessionForkRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/fork",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_abort(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[bool]:
        """Abort an active session and stop any ongoing AI processing or command execution.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/abort",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_init(
        self,
        session_id: str,
        request_body: SessionInitRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Analyze the current application and create an AGENTS.md file with project-specific agent configurations.

        :param request_body: The request body., defaults to None
        :type request_body: SessionInitRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(SessionInitRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/init",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_share(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Session]:
        """Create a shareable link for a session, allowing others to view the conversation.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/share",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(404, NotFoundError)
            .add_error(500, EffectHttpApiErrorInternalServerError)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_unshare(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Session]:
        """Remove the shareable link for a session, making it private again.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/share",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(404, NotFoundError)
            .add_error(500, EffectHttpApiErrorInternalServerError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_summarize(
        self,
        session_id: str,
        request_body: SessionSummarizeRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Generate a concise summary of the session using AI compaction to preserve key information.

        :param request_body: The request body., defaults to None
        :type request_body: SessionSummarizeRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(SessionSummarizeRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/summarize",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_prompt_async(
        self,
        session_id: str,
        request_body: SessionPromptAsyncRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> None:
        """Create and send a new message to a session asynchronously, starting the session if needed and returning immediately.

        :param request_body: The request body., defaults to None
        :type request_body: SessionPromptAsyncRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: None
        """

        Validator(SessionPromptAsyncRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/prompt_async",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, content = self.send_request(serialized_request)

    @cast_models
    def session_command(
        self,
        session_id: str,
        request_body: SessionCommandRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[SessionCommandOkResponse]:
        """Send a new command to a session for execution by the AI assistant.

        :param request_body: The request body., defaults to None
        :type request_body: SessionCommandRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: SessionCommandOkResponse
        """

        Validator(SessionCommandRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/command",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=SessionCommandOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_shell(
        self,
        session_id: str,
        request_body: SessionShellRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[SessionShellOkResponse]:
        """Execute a shell command within the session context and return the AI's response.

        :param request_body: The request body., defaults to None
        :type request_body: SessionShellRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: SessionShellOkResponse
        """

        Validator(SessionShellRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/shell",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=SessionShellOkResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_revert(
        self,
        session_id: str,
        request_body: SessionRevertRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Session]:
        """Revert a specific message in a session, undoing its effects and restoring the previous state.

        :param request_body: The request body., defaults to None
        :type request_body: SessionRevertRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(SessionRevertRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/revert",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def session_unrevert(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Session]:
        """Restore all previously reverted messages in a session.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Session
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/unrevert",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Session._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def permission_respond(
        self,
        session_id: str,
        permission_id: str,
        request_body: PermissionRespondRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Approve or deny a permission request from the AI assistant.

        :param request_body: The request body., defaults to None
        :type request_body: PermissionRespondRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param permission_id: permission_id
        :type permission_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(PermissionRespondRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).pattern("^per").validate(permission_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/permissions/{{permissionID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_path("permissionID", permission_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def part_update(
        self,
        session_id: str,
        message_id: str,
        part_id: str,
        request_body: Part = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Part]:
        """Update a part in a message.

        :param request_body: The request body., defaults to None
        :type request_body: Part, optional
        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param part_id: part_id
        :type part_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Part
        """

        Validator(Part).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).pattern("^msg").validate(message_id)
        Validator(str).pattern("^prt").validate(part_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message/{{messageID}}/part/{{partID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_path("messageID", message_id)
            .add_path("partID", part_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("PATCH")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=PartGuard.return_one_of(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def part_delete(
        self,
        session_id: str,
        message_id: str,
        part_id: str,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[bool]:
        """Delete a part from a message.

        :param session_id: session_id
        :type session_id: str
        :param message_id: message_id
        :type message_id: str
        :param part_id: part_id
        :type part_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: bool
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).pattern("^msg").validate(message_id)
        Validator(str).pattern("^prt").validate(part_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/session/{{sessionID}}/message/{{messageID}}/part/{{partID}}",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_path("messageID", message_id)
            .add_path("partID", part_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .add_error(404, NotFoundError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=response,
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
