# This file was generated by liblab | https://liblab.com/

from typing import List, Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models.session_message import SessionMessageGuard
from ..models import (
    BadRequestError,
    SessionMessage,
    V2SessionListOrder,
    V2SessionListRoots,
    V2SessionPromptRequest,
    V2SessionsResponse,
)


class V2Service(BaseService):
    """
    Service class for V2Service operations.
    Provides methods to interact with V2Service-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def v2_session_list(
        self,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
        limit: float = SENTINEL,
        order: V2SessionListOrder = SENTINEL,
        path: str = SENTINEL,
        roots: V2SessionListRoots = SENTINEL,
        start: float = SENTINEL,
        search: str = SENTINEL,
        cursor: str = SENTINEL,
    ) -> OpencodeResponse[V2SessionsResponse]:
        """Retrieve sessions in the requested order. Items keep that order across pages; use cursor.next or cursor.previous to move through the ordered list.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        :param limit: limit, defaults to None
        :type limit: float, optional
        :param order: order, defaults to None
        :type order: V2SessionListOrder, optional
        :param path: path, defaults to None
        :type path: str, optional
        :param roots: roots, defaults to None
        :type roots: V2SessionListRoots, optional
        :param start: start, defaults to None
        :type start: float, optional
        :param search: search, defaults to None
        :type search: str, optional
        :param cursor: cursor, defaults to None
        :type cursor: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: V2SessionsResponse
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)
        Validator(float).is_optional().validate(limit)
        Validator(V2SessionListOrder).is_optional().validate(order)
        Validator(str).is_optional().validate(path)
        Validator(V2SessionListRoots).is_optional().validate(roots)
        Validator(float).is_optional().validate(start)
        Validator(str).is_optional().validate(search)
        Validator(str).is_optional().validate(cursor)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/api/session",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_query("limit", limit)
            .add_query("order", order)
            .add_query("path", path)
            .add_query("roots", roots)
            .add_query("start", start)
            .add_query("search", search)
            .add_query("cursor", cursor)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=V2SessionsResponse._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def v2_session_prompt(
        self,
        session_id: str,
        request_body: V2SessionPromptRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[SessionMessage]:
        """Create a v2 session message and queue it for the agent loop.

        :param request_body: The request body., defaults to None
        :type request_body: V2SessionPromptRequest, optional
        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: SessionMessage
        """

        Validator(V2SessionPromptRequest).is_optional().validate(request_body)
        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/api/session/{{sessionID}}/prompt",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=SessionMessageGuard.return_one_of(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def v2_session_compact(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> None:
        """Compact a v2 session conversation.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/api/session/{{sessionID}}/compact",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
        )

        self.send_request(serialized_request)

    @cast_models
    def v2_session_wait(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> None:
        """Wait for a v2 session agent loop to become idle.

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/api/session/{{sessionID}}/wait",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
        )

        self.send_request(serialized_request)

    @cast_models
    def v2_session_context(
        self, session_id: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[SessionMessage]]:
        """Retrieve the active context messages for a v2 session (all messages after the last compaction).

        :param session_id: session_id
        :type session_id: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[SessionMessage]
        """

        Validator(str).pattern("^ses").validate(session_id)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/api/session/{{sessionID}}/context",
                [self.get_access_token()],
            )
            .add_path("sessionID", session_id)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[SessionMessageGuard.return_one_of(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )
