# This file was generated by liblab | https://liblab.com/

from typing import List, Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.transport.opencode_response import OpencodeResponse, OpencodeMetadata
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models.experimental_workspace_warp_bad_request_response import (
    ExperimentalWorkspaceWarpBadRequestResponseGuard,
)
from ..models import (
    BadRequestError,
    ExperimentalWorkspaceAdapterListOkResponse,
    ExperimentalWorkspaceCreateRequest,
    ExperimentalWorkspaceStatusOkResponse,
    ExperimentalWorkspaceWarpBadRequestResponse,
    ExperimentalWorkspaceWarpRequest,
    Workspace,
)


class WorkspaceService(BaseService):
    """
    Service class for WorkspaceService operations.
    Provides methods to interact with WorkspaceService-related API endpoints.
    Inherits common functionality from BaseService including authentication and request handling.
    """

    @cast_models
    def experimental_workspace_adapter_list(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[ExperimentalWorkspaceAdapterListOkResponse]]:
        """List all available workspace adapters for the current project.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[ExperimentalWorkspaceAdapterListOkResponse]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace/adapter",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[
                ExperimentalWorkspaceAdapterListOkResponse._unmap(item)
                for item in response
            ],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def experimental_workspace_list(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[Workspace]]:
        """List all workspaces.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[Workspace]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[Workspace._unmap(item) for item in response],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def experimental_workspace_create(
        self,
        request_body: ExperimentalWorkspaceCreateRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> OpencodeResponse[Workspace]:
        """Create a workspace for the current project.

        :param request_body: The request body., defaults to None
        :type request_body: ExperimentalWorkspaceCreateRequest, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Workspace
        """

        Validator(ExperimentalWorkspaceCreateRequest).is_optional().validate(
            request_body
        )
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Workspace._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def experimental_workspace_sync_list(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> None:
        """Register missing workspaces returned by workspace adapters.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace/sync-list",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
        )

        self.send_request(serialized_request)

    @cast_models
    def experimental_workspace_status(
        self, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[List[ExperimentalWorkspaceStatusOkResponse]]:
        """Get connection status for workspaces in the current project.

        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: List[ExperimentalWorkspaceStatusOkResponse]
        """

        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace/status",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=[
                ExperimentalWorkspaceStatusOkResponse._unmap(item) for item in response
            ],
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def experimental_workspace_remove(
        self, id_: str, directory: str = SENTINEL, workspace: str = SENTINEL
    ) -> OpencodeResponse[Workspace]:
        """Remove an existing workspace.

        :param id_: id_
        :type id_: str
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: Workspace
        """

        Validator(str).pattern("^wrk").validate(id_)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace/{{id}}",
                [self.get_access_token()],
            )
            .add_path("id", id_)
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .add_error(400, BadRequestError)
            .serialize()
            .set_method("DELETE")
        )

        response, status, _ = self.send_request(serialized_request)
        return OpencodeResponse(
            data=Workspace._unmap(response),
            raw=self._last_response.raw,
            metadata=OpencodeMetadata(
                headers=dict(self._last_response.headers), status_code=status
            ),
        )

    @cast_models
    def experimental_workspace_warp(
        self,
        request_body: ExperimentalWorkspaceWarpRequest = None,
        directory: str = SENTINEL,
        workspace: str = SENTINEL,
    ) -> None:
        """Move a session's sync history into the target workspace, or detach it to the local project.

        :param request_body: The request body., defaults to None
        :type request_body: ExperimentalWorkspaceWarpRequest, optional
        :param directory: directory, defaults to None
        :type directory: str, optional
        :param workspace: workspace, defaults to None
        :type workspace: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: None
        """

        Validator(ExperimentalWorkspaceWarpRequest).is_optional().validate(request_body)
        Validator(str).is_optional().validate(directory)
        Validator(str).is_optional().validate(workspace)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/experimental/workspace/warp",
                [self.get_access_token()],
            )
            .add_query("directory", directory)
            .add_query("workspace", workspace)
            .serialize()
            .set_method("POST")
            .set_body(request_body)
        )

        response, status, content = self.send_request(serialized_request)
